package native

import (
	"strings"
	"testing"

	"github.com/eikster-dk/sqlc-gen-better-typescript/cmd/plugin/internal/config"
	"github.com/eikster-dk/sqlc-gen-better-typescript/cmd/plugin/internal/logger"
	"github.com/eikster-dk/sqlc-gen-better-typescript/cmd/plugin/internal/models"
)

func defaultCatalog() *models.Catalog {
	return &models.Catalog{}
}

func defaultConfig() config.Config {
	ext := ".js"
	return config.Config{Builder: "native", Driver: "pg", Validator: "zod", ImportExtension: &ext}
}

func TestNative_Build_ModelsFile(t *testing.T) {
	n := New(defaultConfig())
	log := logger.New(false)

	t.Run("generates exactly one file", func(t *testing.T) {
		files, err := n.Build(defaultCatalog(), nil, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(files) != 1 {
			t.Errorf("expected 1 file, got %d", len(files))
		}
	})

	t.Run("generated file is named models.ts", func(t *testing.T) {
		files, err := n.Build(defaultCatalog(), nil, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if files[0].Name != "models.ts" {
			t.Errorf("expected file name %q, got %q", "models.ts", files[0].Name)
		}
	})

	t.Run("models.ts imports ZodError from zod", func(t *testing.T) {
		files, err := n.Build(defaultCatalog(), nil, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		content := string(files[0].Content)
		if !strings.Contains(content, `import { ZodError } from "zod"`) {
			t.Errorf("expected ZodError import in models.ts, got:\n%s", content)
		}
	})

	t.Run("models.ts exports SqlClient interface", func(t *testing.T) {
		files, err := n.Build(defaultCatalog(), nil, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		content := string(files[0].Content)
		if !strings.Contains(content, "export interface SqlClient") {
			t.Errorf("expected SqlClient interface in models.ts, got:\n%s", content)
		}
	})

	t.Run("models.ts SqlClient has query method", func(t *testing.T) {
		files, err := n.Build(defaultCatalog(), nil, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		content := string(files[0].Content)
		if !strings.Contains(content, "query(") {
			t.Errorf("expected query method in SqlClient, got:\n%s", content)
		}
	})

	t.Run("models.ts exports QueryResult type", func(t *testing.T) {
		files, err := n.Build(defaultCatalog(), nil, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		content := string(files[0].Content)
		if !strings.Contains(content, "export type QueryResult<T>") {
			t.Errorf("expected QueryResult<T> type in models.ts, got:\n%s", content)
		}
	})

	t.Run("models.ts QueryResult has success true branch with data", func(t *testing.T) {
		files, err := n.Build(defaultCatalog(), nil, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		content := string(files[0].Content)
		if !strings.Contains(content, "success: true") || !strings.Contains(content, "data: T") {
			t.Errorf("expected success:true/data:T branch in QueryResult, got:\n%s", content)
		}
	})

	t.Run("models.ts QueryResult has success false branch with error and phase", func(t *testing.T) {
		files, err := n.Build(defaultCatalog(), nil, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		content := string(files[0].Content)
		if !strings.Contains(content, "success: false") || !strings.Contains(content, "error: ZodError") {
			t.Errorf("expected success:false/error:ZodError branch in QueryResult, got:\n%s", content)
		}
		if !strings.Contains(content, `phase: "input" | "output"`) {
			t.Errorf(`expected phase: "input" | "output" in QueryResult, got:\n%s`, content)
		}
	})

	t.Run("models.ts starts with generated-by comment", func(t *testing.T) {
		files, err := n.Build(defaultCatalog(), nil, log, "1.27.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		content := string(files[0].Content)
		if !strings.HasPrefix(content, "// Generated by sqlc") {
			t.Errorf("expected generated-by comment at start, got:\n%s", content)
		}
		if !strings.Contains(content, "1.27.0") {
			t.Errorf("expected sqlc version 1.27.0 in header, got:\n%s", content)
		}
	})
}

func TestNative_Build_WithQueries(t *testing.T) {
	n := New(defaultConfig())
	log := logger.New(false)

	t.Run("generates models.ts even with queries present", func(t *testing.T) {
		queries := []models.Query{
			{Name: "GetUser", SQL: "SELECT id FROM users WHERE id = $1", Command: ":one", Filename: "queries.sql"},
			{Name: "ListUsers", SQL: "SELECT id FROM users", Command: ":many", Filename: "queries.sql"},
		}
		files, err := n.Build(defaultCatalog(), queries, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		// models.ts + queriesRequests.ts + queriesResponses.ts + queriesQueries.ts
		hasModels := false
		for _, f := range files {
			if f.Name == "models.ts" {
				hasModels = true
				break
			}
		}
		if !hasModels {
			names := make([]string, len(files))
			for i, f := range files {
				names[i] = f.Name
			}
			t.Errorf("expected models.ts in output, got files: %v", names)
		}
	})

	t.Run("generates models.ts with populated catalog", func(t *testing.T) {
		catalog := &models.Catalog{
			Tables: []models.Table{
				{Name: "users", Columns: []models.Column{{Name: "id", Type: models.SqlType{Name: "serial"}}}},
			},
			Enums: []models.Enum{
				{Name: "role", Values: []models.EnumValue{{Name: "Admin", Value: "admin"}}},
			},
		}
		files, err := n.Build(catalog, nil, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(files) != 1 {
			t.Errorf("expected 1 file, got %d", len(files))
		}
	})
}

func TestNative_Build_ImportExtension(t *testing.T) {
	log := logger.New(false)

	t.Run("import_extension does not affect zod external import", func(t *testing.T) {
		for _, ext := range []string{".js", ".ts", ""} {
			extCopy := ext
			cfg := config.Config{Builder: "native", Driver: "pg", Validator: "zod", ImportExtension: &extCopy}
			n := New(cfg)
			files, err := n.Build(defaultCatalog(), nil, log, "1.0.0")
			if err != nil {
				t.Fatalf("ext=%q: unexpected error: %v", ext, err)
			}
			content := string(files[0].Content)
			// External imports from "zod" must never have an extension appended
			if !strings.Contains(content, `from "zod"`) {
				t.Errorf("ext=%q: expected import from \"zod\" (no extension), got:\n%s", ext, content)
			}
		}
	})

	t.Run("nil import_extension is accepted", func(t *testing.T) {
		cfg := config.Config{Builder: "native", Driver: "pg", Validator: "zod", ImportExtension: nil}
		n := New(cfg)
		files, err := n.Build(defaultCatalog(), nil, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(files) != 1 {
			t.Errorf("expected 1 file, got %d", len(files))
		}
	})
}

func TestNative_Build_VariousSqlcVersions(t *testing.T) {
	n := New(defaultConfig())
	log := logger.New(false)

	for _, version := range []string{"", "1.0.0", "2.3.4-beta", "v1.27.0"} {
		version := version
		t.Run("sqlc version "+version, func(t *testing.T) {
			files, err := n.Build(defaultCatalog(), nil, log, version)
			if err != nil {
				t.Errorf("unexpected error for sqlcVersion=%q: %v", version, err)
			}
			if len(files) != 1 {
				t.Errorf("expected 1 file for sqlcVersion=%q, got %d", version, len(files))
			}
		})
	}
}

func TestNative_Build_DebugLogging(t *testing.T) {
	t.Run("debug logging enabled does not cause error", func(t *testing.T) {
		n := New(defaultConfig())
		debugLog := logger.New(true)
		files, err := n.Build(defaultCatalog(), nil, debugLog, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(files) != 1 {
			t.Errorf("expected 1 file, got %d", len(files))
		}
	})
}

func TestNative_Build_NilCatalog(t *testing.T) {
	n := New(defaultConfig())
	log := logger.New(false)

	t.Run("nil catalog does not panic", func(t *testing.T) {
		files, err := n.Build(nil, nil, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(files) != 1 {
			t.Errorf("expected 1 file, got %d", len(files))
		}
		if files[0].Name != "models.ts" {
			t.Errorf("expected models.ts, got %q", files[0].Name)
		}
	})

	t.Run("nil catalog with queries does not panic", func(t *testing.T) {
		queries := []models.Query{
			{Name: "GetUser", SQL: "SELECT id FROM users WHERE id = $1", Command: ":one", Filename: "queries.sql"},
		}
		files, err := n.Build(nil, queries, log, "1.0.0")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		// Should produce models.ts + query files
		if len(files) == 0 {
			t.Errorf("expected at least 1 file, got 0")
		}
	})
}

func TestNative_Build_FullOutputSnapshot(t *testing.T) {
	n := New(defaultConfig())
	log := logger.New(false)

	files, err := n.Build(defaultCatalog(), nil, log, "1.27.0")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := string(files[0].Content)

	// The full output should match a known structure: header, import, interface, type.
	// Use line-by-line checks so diffs are easy to read.
	lines := strings.Split(strings.TrimRight(content, "\n"), "\n")

	expectations := []struct {
		lineIdx  int
		contains string
	}{
		{0, "// Generated by sqlc 1.27.0, plugin: sqlc-effect"},
		{1, `import { ZodError } from "zod"`},
		{3, "export interface SqlClient"},
		{4, "query(queryText: string"},
		{7, "export type QueryResult<T>"},
		{8, "success: true"},
		{9, "success: false"},
	}

	for _, exp := range expectations {
		if exp.lineIdx >= len(lines) {
			t.Errorf("expected at least %d lines, got %d", exp.lineIdx+1, len(lines))
			continue
		}
		if !strings.Contains(lines[exp.lineIdx], exp.contains) {
			t.Errorf("line %d: expected to contain %q, got %q", exp.lineIdx, exp.contains, lines[exp.lineIdx])
		}
	}

	// Verify the file ends with a newline (clean output)
	if !strings.HasSuffix(content, "\n") {
		t.Error("expected content to end with newline")
	}

	// Verify no triple newlines (clean whitespace)
	if strings.Contains(content, "\n\n\n") {
		t.Error("content contains three consecutive newlines")
	}
}

func TestNew(t *testing.T) {
	t.Run("New returns a non-nil Native", func(t *testing.T) {
		cfg := config.Config{Builder: "native"}
		n := New(cfg)
		if n == nil {
			t.Fatal("expected non-nil *Native")
		}
	})

	t.Run("config is stored correctly", func(t *testing.T) {
		cfg := config.Config{Builder: "native", Driver: "pg2", Validator: "valibot"}
		n := New(cfg)
		if n.cfg.Driver != "pg2" {
			t.Errorf("expected driver %q, got %q", "pg2", n.cfg.Driver)
		}
		if n.cfg.Validator != "valibot" {
			t.Errorf("expected validator %q, got %q", "valibot", n.cfg.Validator)
		}
	})
}
