# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: sqlc-gen-better-typescript

before:
  hooks:
    - go mod tidy

builds:
  - id: plugin
    main: ./cmd/plugin
    env:
      - CGO_ENABLED=0
    goos:
      - wasip1
    goarch:
      - wasm
    ldflags:
      - -s -w
      - -X github.com/eikster-dk/sqlc-gen-better-typescript/cmd/plugin/internal/version.Version={{.Version}}

archives:
  - id: dist
    formats: binary
    name_template: "{{ .ProjectName }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: eikster-dk
    name: sqlc-gen-better-typescript
  header: |
    ## sqlc-gen-better-typescript ({{ .Date }})

    To update to this version, use the following in your `sqlc.yaml`:

    ```yaml
    version: '2'
    plugins:
    - name: better-typescript
      wasm:
        url: https://github.com/eikster-dk/sqlc-gen-better-typescript/releases/download/{{ .Tag }}/sqlc-gen-better-typescript.wasm
        sha256: {{ trimsuffix .Checksums "  sqlc-gen-better-typescript.wasm\n" }}
    ```
