// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import type { SqlClient, QueryResult } from "./models.js"

import type { GetCustomerParams } from "./customersRequests.js"
import { GetCustomerParams as GetCustomerParamsSchema } from "./customersRequests.js"
import type { GetCustomerResult } from "./customersResponses.js"
import { GetCustomerResult as GetCustomerResultSchema } from "./customersResponses.js"

// GetCustomer
export async function getCustomer(client: SqlClient, params: GetCustomerParams): Promise<QueryResult<GetCustomerResult | null>> {
  const inputParsed = GetCustomerParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, email, name, phone, created_at, updated_at
FROM customers
WHERE id = $1`,
    [params.id]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = GetCustomerResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}
