// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { z } from "zod"

// GetCustomer - Parameters
export const GetCustomerParams = z.object({
  id: z.number(),
})

export type GetCustomerParams = z.infer<typeof GetCustomerParams>
