// Generated by sqlc v1.31.1, plugin: sqlc-effect dev
import type { SqlClient, QueryResult } from "./models.js"

import type { GetCustomerParams } from "./customersRequests.js"
import { GetCustomerParams as GetCustomerParamsSchema } from "./customersRequests.js"
import type { GetCustomerResult } from "./customersResponses.js"
import { GetCustomerResult as GetCustomerResultSchema } from "./customersResponses.js"

import type { GetCustomerByEmailParams } from "./customersRequests.js"
import { GetCustomerByEmailParams as GetCustomerByEmailParamsSchema } from "./customersRequests.js"
import type { GetCustomerByEmailResult } from "./customersResponses.js"
import { GetCustomerByEmailResult as GetCustomerByEmailResultSchema } from "./customersResponses.js"
import type { ListCustomersResult } from "./customersResponses.js"
import { ListCustomersResult as ListCustomersResultSchema } from "./customersResponses.js"

import type { ListCustomersPaginatedParams } from "./customersRequests.js"
import { ListCustomersPaginatedParams as ListCustomersPaginatedParamsSchema } from "./customersRequests.js"
import type { ListCustomersPaginatedResult } from "./customersResponses.js"
import { ListCustomersPaginatedResult as ListCustomersPaginatedResultSchema } from "./customersResponses.js"

import type { SearchCustomersByNameParams } from "./customersRequests.js"
import { SearchCustomersByNameParams as SearchCustomersByNameParamsSchema } from "./customersRequests.js"
import type { SearchCustomersByNameResult } from "./customersResponses.js"
import { SearchCustomersByNameResult as SearchCustomersByNameResultSchema } from "./customersResponses.js"

import type { CreateCustomerParams } from "./customersRequests.js"
import { CreateCustomerParams as CreateCustomerParamsSchema } from "./customersRequests.js"
import type { CreateCustomerResult } from "./customersResponses.js"
import { CreateCustomerResult as CreateCustomerResultSchema } from "./customersResponses.js"

import type { UpdateCustomerParams } from "./customersRequests.js"
import { UpdateCustomerParams as UpdateCustomerParamsSchema } from "./customersRequests.js"
import type { UpdateCustomerResult } from "./customersResponses.js"
import { UpdateCustomerResult as UpdateCustomerResultSchema } from "./customersResponses.js"

import type { PatchCustomerParams } from "./customersRequests.js"
import { PatchCustomerParams as PatchCustomerParamsSchema } from "./customersRequests.js"
import type { PatchCustomerResult } from "./customersResponses.js"
import { PatchCustomerResult as PatchCustomerResultSchema } from "./customersResponses.js"

import type { UpdateCustomerEmailParams } from "./customersRequests.js"
import { UpdateCustomerEmailParams as UpdateCustomerEmailParamsSchema } from "./customersRequests.js"

import type { DeleteCustomerParams } from "./customersRequests.js"
import { DeleteCustomerParams as DeleteCustomerParamsSchema } from "./customersRequests.js"
import type { CountCustomersResult } from "./customersResponses.js"
import { CountCustomersResult as CountCustomersResultSchema } from "./customersResponses.js"

import type { GetCustomersByIdsParams } from "./customersRequests.js"
import { GetCustomersByIdsParams as GetCustomersByIdsParamsSchema } from "./customersRequests.js"
import type { GetCustomersByIdsResult } from "./customersResponses.js"
import { GetCustomersByIdsResult as GetCustomersByIdsResultSchema } from "./customersResponses.js"

import type { GetCustomersByIdsSliceParams } from "./customersRequests.js"
import { GetCustomersByIdsSliceParams as GetCustomersByIdsSliceParamsSchema } from "./customersRequests.js"
import type { GetCustomersByIdsSliceResult } from "./customersResponses.js"
import { GetCustomersByIdsSliceResult as GetCustomersByIdsSliceResultSchema } from "./customersResponses.js"

import type { SearchCustomersAdvancedParams } from "./customersRequests.js"
import { SearchCustomersAdvancedParams as SearchCustomersAdvancedParamsSchema } from "./customersRequests.js"
import type { SearchCustomersAdvancedResult } from "./customersResponses.js"
import { SearchCustomersAdvancedResult as SearchCustomersAdvancedResultSchema } from "./customersResponses.js"

type QueryParam = { value: unknown; slice?: boolean }

function expandSqlSlices(sql: string, params: QueryParam[]): { sql: string; params: unknown[] } {
  const expandedParams: unknown[] = []
  const expandedSql = sql.replace(/\$(\d+)/g, (_match, positionText: string) => {
    const param = params[Number(positionText) - 1]
    if (!param) {
      return _match
    }
    if (!param.slice) {
      expandedParams.push(param.value)
      return `$${expandedParams.length}`
    }

    const values = param.value as readonly unknown[]
    if (values.length === 0) {
      return "NULL"
    }
    return values.map((value) => {
      expandedParams.push(value)
      return `$${expandedParams.length}`
    }).join(", ")
  })

  return { sql: expandedSql, params: expandedParams }
}

// GetCustomer
// SELECT id, email, name, phone, created_at, updated_at
// FROM customers
// WHERE id = $1
export async function getCustomer(client: SqlClient, params: GetCustomerParams): Promise<QueryResult<GetCustomerResult | null>> {
  const inputParsed = GetCustomerParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    "SELECT id, email, name, phone, created_at, updated_at\nFROM customers\nWHERE id = $1",
    [inputParsed.data.id]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = GetCustomerResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetCustomerByEmail
// SELECT id, email, name, phone, created_at, updated_at
// FROM customers
// WHERE email = $1
export async function getCustomerByEmail(client: SqlClient, params: GetCustomerByEmailParams): Promise<QueryResult<GetCustomerByEmailResult | null>> {
  const inputParsed = GetCustomerByEmailParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    "SELECT id, email, name, phone, created_at, updated_at\nFROM customers\nWHERE email = $1",
    [inputParsed.data.email]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = GetCustomerByEmailResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListCustomers
// SELECT id, email, name, phone, created_at, updated_at
// FROM customers
// ORDER BY created_at DESC
export async function listCustomers(client: SqlClient): Promise<QueryResult<ListCustomersResult[]>> {

  const result = await client.query(
    "SELECT id, email, name, phone, created_at, updated_at\nFROM customers\nORDER BY created_at DESC",
    []
  )

  const outputParsed = ListCustomersResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListCustomersPaginated
// SELECT id, email, name, phone, created_at, updated_at
// FROM customers
// ORDER BY created_at DESC
// LIMIT $1 OFFSET $2
export async function listCustomersPaginated(client: SqlClient, params: ListCustomersPaginatedParams): Promise<QueryResult<ListCustomersPaginatedResult[]>> {
  const inputParsed = ListCustomersPaginatedParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    "SELECT id, email, name, phone, created_at, updated_at\nFROM customers\nORDER BY created_at DESC\nLIMIT $1 OFFSET $2",
    [inputParsed.data.limit, inputParsed.data.offset]
  )

  const outputParsed = ListCustomersPaginatedResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// SearchCustomersByName
// SELECT id, email, name, phone, created_at, updated_at
// FROM customers
// WHERE name ILIKE '%' || $1 || '%'
// ORDER BY name
export async function searchCustomersByName(client: SqlClient, params: SearchCustomersByNameParams): Promise<QueryResult<SearchCustomersByNameResult[]>> {
  const inputParsed = SearchCustomersByNameParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    "SELECT id, email, name, phone, created_at, updated_at\nFROM customers\nWHERE name ILIKE '%' || $1 || '%'\nORDER BY name",
    [inputParsed.data.arg1]
  )

  const outputParsed = SearchCustomersByNameResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// CreateCustomer
// INSERT INTO customers (email, name, phone)
// VALUES ($1, $2, $3)
// RETURNING id, email, name, phone, created_at, updated_at
export async function createCustomer(client: SqlClient, params: CreateCustomerParams): Promise<QueryResult<CreateCustomerResult | null>> {
  const inputParsed = CreateCustomerParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    "INSERT INTO customers (email, name, phone)\nVALUES ($1, $2, $3)\nRETURNING id, email, name, phone, created_at, updated_at",
    [inputParsed.data.email, inputParsed.data.name, inputParsed.data.phone]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = CreateCustomerResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// UpdateCustomer
// UPDATE customers
// SET email = $2, name = $3, phone = $4, updated_at = NOW()
// WHERE id = $1
// RETURNING id, email, name, phone, created_at, updated_at
export async function updateCustomer(client: SqlClient, params: UpdateCustomerParams): Promise<QueryResult<UpdateCustomerResult | null>> {
  const inputParsed = UpdateCustomerParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    "UPDATE customers\nSET email = $2, name = $3, phone = $4, updated_at = NOW()\nWHERE id = $1\nRETURNING id, email, name, phone, created_at, updated_at",
    [inputParsed.data.id, inputParsed.data.email, inputParsed.data.name, inputParsed.data.phone]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = UpdateCustomerResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// PatchCustomer
// UPDATE customers
// SET
//   email = COALESCE($1, email),
//   name = COALESCE($2, name),
//   phone = COALESCE($3, phone),
//   updated_at = NOW()
// WHERE id = $4
// RETURNING id, email, name, phone, created_at, updated_at
export async function patchCustomer(client: SqlClient, params: PatchCustomerParams): Promise<QueryResult<PatchCustomerResult | null>> {
  const inputParsed = PatchCustomerParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    "UPDATE customers\nSET\n  email = COALESCE($1, email),\n  name = COALESCE($2, name),\n  phone = COALESCE($3, phone),\n  updated_at = NOW()\nWHERE id = $4\nRETURNING id, email, name, phone, created_at, updated_at",
    [inputParsed.data.email, inputParsed.data.name, inputParsed.data.phone, inputParsed.data.id]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = PatchCustomerResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// UpdateCustomerEmail
// UPDATE customers
// SET email = $2, updated_at = NOW()
// WHERE id = $1
export async function updateCustomerEmail(client: SqlClient, params: UpdateCustomerEmailParams): Promise<QueryResult<void>> {
  const inputParsed = UpdateCustomerEmailParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  await client.query(
    "UPDATE customers\nSET email = $2, updated_at = NOW()\nWHERE id = $1",
    [inputParsed.data.id, inputParsed.data.email]
  )

  return { success: true, data: undefined }
}

// DeleteCustomer
// DELETE FROM customers
// WHERE id = $1
export async function deleteCustomer(client: SqlClient, params: DeleteCustomerParams): Promise<QueryResult<void>> {
  const inputParsed = DeleteCustomerParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  await client.query(
    "DELETE FROM customers\nWHERE id = $1",
    [inputParsed.data.id]
  )

  return { success: true, data: undefined }
}

// CountCustomers
// SELECT COUNT(*) AS total
// FROM customers
export async function countCustomers(client: SqlClient): Promise<QueryResult<CountCustomersResult | null>> {

  const result = await client.query(
    "SELECT COUNT(*) AS total\nFROM customers",
    []
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = CountCustomersResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetCustomersByIds
// SELECT id, email, name, phone, created_at, updated_at
// FROM customers
// WHERE id = ANY($1::int[])
export async function getCustomersByIds(client: SqlClient, params: GetCustomersByIdsParams): Promise<QueryResult<GetCustomersByIdsResult[]>> {
  const inputParsed = GetCustomersByIdsParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    "SELECT id, email, name, phone, created_at, updated_at\nFROM customers\nWHERE id = ANY($1::int[])",
    [inputParsed.data.ids]
  )

  const outputParsed = GetCustomersByIdsResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetCustomersByIdsSlice
// SELECT id, email, name, phone, created_at, updated_at
// FROM customers
// WHERE id IN ($1)
// ORDER BY id
export async function getCustomersByIdsSlice(client: SqlClient, params: GetCustomersByIdsSliceParams): Promise<QueryResult<GetCustomersByIdsSliceResult[]>> {
  const inputParsed = GetCustomersByIdsSliceParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const query = expandSqlSlices("SELECT id, email, name, phone, created_at, updated_at\nFROM customers\nWHERE id IN ($1)\nORDER BY id", [{ value: inputParsed.data.ids, slice: true }])
  const result = await client.query(
    query.sql,
    query.params
  )

  const outputParsed = GetCustomersByIdsSliceResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// SearchCustomersAdvanced
// SELECT id, email, name, phone, created_at, updated_at
// FROM customers
// WHERE (name ILIKE '%' || $2 || '%' OR email ILIKE '%' || $2 || '%')
//   AND ($3::text IS NULL OR phone = $3)
//   AND id > $1
//   AND id IN ($4)
// ORDER BY id
export async function searchCustomersAdvanced(client: SqlClient, params: SearchCustomersAdvancedParams): Promise<QueryResult<SearchCustomersAdvancedResult[]>> {
  const inputParsed = SearchCustomersAdvancedParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const query = expandSqlSlices("SELECT id, email, name, phone, created_at, updated_at\nFROM customers\nWHERE (name ILIKE '%' || $2 || '%' OR email ILIKE '%' || $2 || '%')\n  AND ($3::text IS NULL OR phone = $3)\n  AND id > $1\n  AND id IN ($4)\nORDER BY id", [{ value: inputParsed.data.id, slice: false }, { value: inputParsed.data.term, slice: false }, { value: inputParsed.data.phone, slice: false }, { value: inputParsed.data.ids, slice: true }])
  const result = await client.query(
    query.sql,
    query.params
  )

  const outputParsed = SearchCustomersAdvancedResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}
