// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { z } from "zod"

// GetCustomer - Result
export const GetCustomerResult = z.object({
  id: z.number(),
  email: z.string(),
  name: z.string(),
  phone: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetCustomerResult = z.infer<typeof GetCustomerResult>
