// Generated by sqlc v1.31.1, plugin: sqlc-effect dev
import { z } from "zod"

// GetCustomer - Row
export const GetCustomerRow = z.object({
  id: z.number(),
  email: z.string(),
  name: z.string(),
  phone: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetCustomerRow = z.infer<typeof GetCustomerRow>

// GetCustomer - Result
export const GetCustomerResult = GetCustomerRow.transform((row) => ({
  id: row.id,
  email: row.email,
  name: row.name,
  phone: row.phone,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type GetCustomerResult = z.infer<typeof GetCustomerResult>

// GetCustomerByEmail - Row
export const GetCustomerByEmailRow = z.object({
  id: z.number(),
  email: z.string(),
  name: z.string(),
  phone: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetCustomerByEmailRow = z.infer<typeof GetCustomerByEmailRow>

// GetCustomerByEmail - Result
export const GetCustomerByEmailResult = GetCustomerByEmailRow.transform((row) => ({
  id: row.id,
  email: row.email,
  name: row.name,
  phone: row.phone,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type GetCustomerByEmailResult = z.infer<typeof GetCustomerByEmailResult>

// ListCustomers - Row
export const ListCustomersRow = z.object({
  id: z.number(),
  email: z.string(),
  name: z.string(),
  phone: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListCustomersRow = z.infer<typeof ListCustomersRow>

// ListCustomers - Result
export const ListCustomersResult = ListCustomersRow.transform((row) => ({
  id: row.id,
  email: row.email,
  name: row.name,
  phone: row.phone,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListCustomersResult = z.infer<typeof ListCustomersResult>

// ListCustomersPaginated - Row
export const ListCustomersPaginatedRow = z.object({
  id: z.number(),
  email: z.string(),
  name: z.string(),
  phone: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListCustomersPaginatedRow = z.infer<typeof ListCustomersPaginatedRow>

// ListCustomersPaginated - Result
export const ListCustomersPaginatedResult = ListCustomersPaginatedRow.transform((row) => ({
  id: row.id,
  email: row.email,
  name: row.name,
  phone: row.phone,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListCustomersPaginatedResult = z.infer<typeof ListCustomersPaginatedResult>

// SearchCustomersByName - Row
export const SearchCustomersByNameRow = z.object({
  id: z.number(),
  email: z.string(),
  name: z.string(),
  phone: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type SearchCustomersByNameRow = z.infer<typeof SearchCustomersByNameRow>

// SearchCustomersByName - Result
export const SearchCustomersByNameResult = SearchCustomersByNameRow.transform((row) => ({
  id: row.id,
  email: row.email,
  name: row.name,
  phone: row.phone,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type SearchCustomersByNameResult = z.infer<typeof SearchCustomersByNameResult>

// CreateCustomer - Row
export const CreateCustomerRow = z.object({
  id: z.number(),
  email: z.string(),
  name: z.string(),
  phone: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type CreateCustomerRow = z.infer<typeof CreateCustomerRow>

// CreateCustomer - Result
export const CreateCustomerResult = CreateCustomerRow.transform((row) => ({
  id: row.id,
  email: row.email,
  name: row.name,
  phone: row.phone,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type CreateCustomerResult = z.infer<typeof CreateCustomerResult>

// UpdateCustomer - Row
export const UpdateCustomerRow = z.object({
  id: z.number(),
  email: z.string(),
  name: z.string(),
  phone: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type UpdateCustomerRow = z.infer<typeof UpdateCustomerRow>

// UpdateCustomer - Result
export const UpdateCustomerResult = UpdateCustomerRow.transform((row) => ({
  id: row.id,
  email: row.email,
  name: row.name,
  phone: row.phone,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type UpdateCustomerResult = z.infer<typeof UpdateCustomerResult>

// PatchCustomer - Row
export const PatchCustomerRow = z.object({
  id: z.number(),
  email: z.string(),
  name: z.string(),
  phone: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type PatchCustomerRow = z.infer<typeof PatchCustomerRow>

// PatchCustomer - Result
export const PatchCustomerResult = PatchCustomerRow.transform((row) => ({
  id: row.id,
  email: row.email,
  name: row.name,
  phone: row.phone,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type PatchCustomerResult = z.infer<typeof PatchCustomerResult>

// CountCustomers - Row
export const CountCustomersRow = z.object({
  total: z.coerce.bigint(),
})

export type CountCustomersRow = z.infer<typeof CountCustomersRow>

// CountCustomers - Result
export const CountCustomersResult = CountCustomersRow.transform((row) => ({
  total: row.total,
}))

export type CountCustomersResult = z.infer<typeof CountCustomersResult>

// GetCustomersByIds - Row
export const GetCustomersByIdsRow = z.object({
  id: z.number(),
  email: z.string(),
  name: z.string(),
  phone: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetCustomersByIdsRow = z.infer<typeof GetCustomersByIdsRow>

// GetCustomersByIds - Result
export const GetCustomersByIdsResult = GetCustomersByIdsRow.transform((row) => ({
  id: row.id,
  email: row.email,
  name: row.name,
  phone: row.phone,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type GetCustomersByIdsResult = z.infer<typeof GetCustomersByIdsResult>

// GetCustomersByIdsSlice - Row
export const GetCustomersByIdsSliceRow = z.object({
  id: z.number(),
  email: z.string(),
  name: z.string(),
  phone: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetCustomersByIdsSliceRow = z.infer<typeof GetCustomersByIdsSliceRow>

// GetCustomersByIdsSlice - Result
export const GetCustomersByIdsSliceResult = GetCustomersByIdsSliceRow.transform((row) => ({
  id: row.id,
  email: row.email,
  name: row.name,
  phone: row.phone,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type GetCustomersByIdsSliceResult = z.infer<typeof GetCustomersByIdsSliceResult>

// SearchCustomersAdvanced - Row
export const SearchCustomersAdvancedRow = z.object({
  id: z.number(),
  email: z.string(),
  name: z.string(),
  phone: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type SearchCustomersAdvancedRow = z.infer<typeof SearchCustomersAdvancedRow>

// SearchCustomersAdvanced - Result
export const SearchCustomersAdvancedResult = SearchCustomersAdvancedRow.transform((row) => ({
  id: row.id,
  email: row.email,
  name: row.name,
  phone: row.phone,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type SearchCustomersAdvancedResult = z.infer<typeof SearchCustomersAdvancedResult>
