// Generated by sqlc v1.31.1, plugin: sqlc-effect dev
import { z } from "zod"

// GetOrderWithCustomerEmbed - Row
export const GetOrderWithCustomerEmbedRow = z.object({
  orders_id: z.number(),
  orders_customer_id: z.number(),
  orders_status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  orders_total_cents: z.number(),
  orders_shipping_address: z.string().nullable(),
  orders_billing_address: z.string().nullable(),
  orders_notes: z.string().nullable(),
  orders_created_at: z.coerce.date(),
  orders_updated_at: z.coerce.date(),
  orders_search_vector: z.unknown().nullable(),
  customers_id: z.number(),
  customers_email: z.string(),
  customers_name: z.string(),
  customers_phone: z.string().nullable(),
  customers_created_at: z.coerce.date(),
  customers_updated_at: z.coerce.date(),
})

export type GetOrderWithCustomerEmbedRow = z.infer<typeof GetOrderWithCustomerEmbedRow>

// GetOrderWithCustomerEmbed - Result
export const GetOrderWithCustomerEmbedResult = GetOrderWithCustomerEmbedRow.transform((row) => ({
  order: {
    id: row.orders_id,
    customer_id: row.orders_customer_id,
    status: row.orders_status,
    total_cents: row.orders_total_cents,
    shipping_address: row.orders_shipping_address,
    billing_address: row.orders_billing_address,
    notes: row.orders_notes,
    created_at: row.orders_created_at,
    updated_at: row.orders_updated_at,
    search_vector: row.orders_search_vector,
  },
  customer: {
    id: row.customers_id,
    email: row.customers_email,
    name: row.customers_name,
    phone: row.customers_phone,
    created_at: row.customers_created_at,
    updated_at: row.customers_updated_at,
  },
}))

export type GetOrderWithCustomerEmbedResult = z.infer<typeof GetOrderWithCustomerEmbedResult>

// ListOrdersWithCustomerEmbed - Row
export const ListOrdersWithCustomerEmbedRow = z.object({
  orders_id: z.number(),
  orders_customer_id: z.number(),
  orders_status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  orders_total_cents: z.number(),
  orders_shipping_address: z.string().nullable(),
  orders_billing_address: z.string().nullable(),
  orders_notes: z.string().nullable(),
  orders_created_at: z.coerce.date(),
  orders_updated_at: z.coerce.date(),
  orders_search_vector: z.unknown().nullable(),
  customers_id: z.number(),
  customers_email: z.string(),
  customers_name: z.string(),
  customers_phone: z.string().nullable(),
  customers_created_at: z.coerce.date(),
  customers_updated_at: z.coerce.date(),
})

export type ListOrdersWithCustomerEmbedRow = z.infer<typeof ListOrdersWithCustomerEmbedRow>

// ListOrdersWithCustomerEmbed - Result
export const ListOrdersWithCustomerEmbedResult = ListOrdersWithCustomerEmbedRow.transform((row) => ({
  order: {
    id: row.orders_id,
    customer_id: row.orders_customer_id,
    status: row.orders_status,
    total_cents: row.orders_total_cents,
    shipping_address: row.orders_shipping_address,
    billing_address: row.orders_billing_address,
    notes: row.orders_notes,
    created_at: row.orders_created_at,
    updated_at: row.orders_updated_at,
    search_vector: row.orders_search_vector,
  },
  customer: {
    id: row.customers_id,
    email: row.customers_email,
    name: row.customers_name,
    phone: row.customers_phone,
    created_at: row.customers_created_at,
    updated_at: row.customers_updated_at,
  },
}))

export type ListOrdersWithCustomerEmbedResult = z.infer<typeof ListOrdersWithCustomerEmbedResult>
