// Generated by sqlc v1.31.1, plugin: sqlc-effect dev
import { z } from "zod"
import { CustomersRow, OrderStatus, OrdersRow } from "./models.js"

// GetOrderWithCustomerEmbed - Parameters
export const GetOrderWithCustomerEmbedParams = z.object({
  id: z.number(),
})

export type GetOrderWithCustomerEmbedParams = z.infer<typeof GetOrderWithCustomerEmbedParams>
