// Generated by sqlc v1.31.1, plugin: sqlc-effect dev
import type { SqlClient, QueryResult } from "./models.js"

import type { GetOrderWithCustomerEmbedParams } from "./embedRequests.js"
import { GetOrderWithCustomerEmbedParams as GetOrderWithCustomerEmbedParamsSchema } from "./embedRequests.js"
import type { GetOrderWithCustomerEmbedResult } from "./embedResponses.js"
import { GetOrderWithCustomerEmbedResult as GetOrderWithCustomerEmbedResultSchema } from "./embedResponses.js"
import type { ListOrdersWithCustomerEmbedResult } from "./embedResponses.js"
import { ListOrdersWithCustomerEmbedResult as ListOrdersWithCustomerEmbedResultSchema } from "./embedResponses.js"

// GetOrderWithCustomerEmbed
//
// SELECT orders.id AS orders_id, orders.customer_id AS orders_customer_id, orders.status AS orders_status, orders.total_cents AS orders_total_cents, orders.shipping_address AS orders_shipping_address, orders.billing_address AS orders_billing_address, orders.notes AS orders_notes, orders.created_at AS orders_created_at, orders.updated_at AS orders_updated_at, orders.search_vector AS orders_search_vector, customers.id AS customers_id, customers.email AS customers_email, customers.name AS customers_name, customers.phone AS customers_phone, customers.created_at AS customers_created_at, customers.updated_at AS customers_updated_at
// FROM orders
// JOIN customers ON orders.customer_id = customers.id
// WHERE orders.id = $1
export async function getOrderWithCustomerEmbed(client: SqlClient, params: GetOrderWithCustomerEmbedParams): Promise<QueryResult<GetOrderWithCustomerEmbedResult | null>> {
  const inputParsed = GetOrderWithCustomerEmbedParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    "\nSELECT orders.id AS orders_id, orders.customer_id AS orders_customer_id, orders.status AS orders_status, orders.total_cents AS orders_total_cents, orders.shipping_address AS orders_shipping_address, orders.billing_address AS orders_billing_address, orders.notes AS orders_notes, orders.created_at AS orders_created_at, orders.updated_at AS orders_updated_at, orders.search_vector AS orders_search_vector, customers.id AS customers_id, customers.email AS customers_email, customers.name AS customers_name, customers.phone AS customers_phone, customers.created_at AS customers_created_at, customers.updated_at AS customers_updated_at\nFROM orders\nJOIN customers ON orders.customer_id = customers.id\nWHERE orders.id = $1",
    [inputParsed.data.id]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = GetOrderWithCustomerEmbedResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListOrdersWithCustomerEmbed
// SELECT orders.id AS orders_id, orders.customer_id AS orders_customer_id, orders.status AS orders_status, orders.total_cents AS orders_total_cents, orders.shipping_address AS orders_shipping_address, orders.billing_address AS orders_billing_address, orders.notes AS orders_notes, orders.created_at AS orders_created_at, orders.updated_at AS orders_updated_at, orders.search_vector AS orders_search_vector, customers.id AS customers_id, customers.email AS customers_email, customers.name AS customers_name, customers.phone AS customers_phone, customers.created_at AS customers_created_at, customers.updated_at AS customers_updated_at
// FROM orders
// JOIN customers ON orders.customer_id = customers.id
// ORDER BY orders.created_at DESC
export async function listOrdersWithCustomerEmbed(client: SqlClient): Promise<QueryResult<ListOrdersWithCustomerEmbedResult[]>> {

  const result = await client.query(
    "SELECT orders.id AS orders_id, orders.customer_id AS orders_customer_id, orders.status AS orders_status, orders.total_cents AS orders_total_cents, orders.shipping_address AS orders_shipping_address, orders.billing_address AS orders_billing_address, orders.notes AS orders_notes, orders.created_at AS orders_created_at, orders.updated_at AS orders_updated_at, orders.search_vector AS orders_search_vector, customers.id AS customers_id, customers.email AS customers_email, customers.name AS customers_name, customers.phone AS customers_phone, customers.created_at AS customers_created_at, customers.updated_at AS customers_updated_at\nFROM orders\nJOIN customers ON orders.customer_id = customers.id\nORDER BY orders.created_at DESC",
    []
  )

  const outputParsed = ListOrdersWithCustomerEmbedResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}
