// Generated by sqlc v1.31.1, plugin: sqlc-effect dev
import { z, ZodError } from "zod"

export const OrderStatus = z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")])
export type OrderStatus = z.infer<typeof OrderStatus>

export interface SqlQueryResult {
  rows: unknown[]
  rowCount?: number | null
  command?: string
}

export interface SqlClient {
  query(queryText: string, values?: unknown[]): Promise<SqlQueryResult>
}

export interface SqlExecResult {
  command: string
  rowCount: number
}

export type QueryResult<T> =
  | { success: true; data: T }
  | { success: false; error: ZodError; phase: "input" | "output" }
