// Generated by sqlc v1.31.1, plugin: sqlc-effect dev
import { ZodError } from "zod"

export interface SqlClient {
  query(queryText: string, values?: unknown[]): Promise<{ rows: unknown[]; rowCount?: number | null }>
}

export type QueryResult<T> =
  | { success: true; data: T }
  | { success: false; error: ZodError; phase: "input" | "output" }
