// Generated by sqlc v1.31.1, plugin: sqlc-effect dev
import { ZodError } from "zod"

export interface SqlQueryResult {
  rows: unknown[]
  rowCount?: number | null
  command?: string
}

export interface SqlClient {
  query(queryText: string, values?: unknown[]): Promise<SqlQueryResult>
}

export interface SqlExecResult {
  command: string
  rowCount: number
}

export type QueryResult<T> =
  | { success: true; data: T }
  | { success: false; error: ZodError; phase: "input" | "output" }
