// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import type { SqlClient, QueryResult } from "./models.js"

import type { GetOrderParams } from "./ordersRequests.js"
import { GetOrderParams as GetOrderParamsSchema } from "./ordersRequests.js"
import type { GetOrderResult } from "./ordersResponses.js"
import { GetOrderResult as GetOrderResultSchema } from "./ordersResponses.js"

import type { GetOrderWithCustomerParams } from "./ordersRequests.js"
import { GetOrderWithCustomerParams as GetOrderWithCustomerParamsSchema } from "./ordersRequests.js"
import type { GetOrderWithCustomerResult } from "./ordersResponses.js"
import { GetOrderWithCustomerResult as GetOrderWithCustomerResultSchema } from "./ordersResponses.js"
import type { ListOrdersResult } from "./ordersResponses.js"
import { ListOrdersResult as ListOrdersResultSchema } from "./ordersResponses.js"

import type { ListOrdersByCustomerParams } from "./ordersRequests.js"
import { ListOrdersByCustomerParams as ListOrdersByCustomerParamsSchema } from "./ordersRequests.js"
import type { ListOrdersByCustomerResult } from "./ordersResponses.js"
import { ListOrdersByCustomerResult as ListOrdersByCustomerResultSchema } from "./ordersResponses.js"

import type { ListOrdersByStatusParams } from "./ordersRequests.js"
import { ListOrdersByStatusParams as ListOrdersByStatusParamsSchema } from "./ordersRequests.js"
import type { ListOrdersByStatusResult } from "./ordersResponses.js"
import { ListOrdersByStatusResult as ListOrdersByStatusResultSchema } from "./ordersResponses.js"

import type { ListOrdersPaginatedParams } from "./ordersRequests.js"
import { ListOrdersPaginatedParams as ListOrdersPaginatedParamsSchema } from "./ordersRequests.js"
import type { ListOrdersPaginatedResult } from "./ordersResponses.js"
import { ListOrdersPaginatedResult as ListOrdersPaginatedResultSchema } from "./ordersResponses.js"

import type { ListOrdersByDateRangeParams } from "./ordersRequests.js"
import { ListOrdersByDateRangeParams as ListOrdersByDateRangeParamsSchema } from "./ordersRequests.js"
import type { ListOrdersByDateRangeResult } from "./ordersResponses.js"
import { ListOrdersByDateRangeResult as ListOrdersByDateRangeResultSchema } from "./ordersResponses.js"

import type { ListOrdersByDateRangeNamedParams } from "./ordersRequests.js"
import { ListOrdersByDateRangeNamedParams as ListOrdersByDateRangeNamedParamsSchema } from "./ordersRequests.js"
import type { ListOrdersByDateRangeNamedResult } from "./ordersResponses.js"
import { ListOrdersByDateRangeNamedResult as ListOrdersByDateRangeNamedResultSchema } from "./ordersResponses.js"

import type { ListRecentOrdersWithCustomerParams } from "./ordersRequests.js"
import { ListRecentOrdersWithCustomerParams as ListRecentOrdersWithCustomerParamsSchema } from "./ordersRequests.js"
import type { ListRecentOrdersWithCustomerResult } from "./ordersResponses.js"
import { ListRecentOrdersWithCustomerResult as ListRecentOrdersWithCustomerResultSchema } from "./ordersResponses.js"

import type { SearchOrdersParams } from "./ordersRequests.js"
import { SearchOrdersParams as SearchOrdersParamsSchema } from "./ordersRequests.js"
import type { SearchOrdersResult } from "./ordersResponses.js"
import { SearchOrdersResult as SearchOrdersResultSchema } from "./ordersResponses.js"

import type { CreateOrderParams } from "./ordersRequests.js"
import { CreateOrderParams as CreateOrderParamsSchema } from "./ordersRequests.js"
import type { CreateOrderResult } from "./ordersResponses.js"
import { CreateOrderResult as CreateOrderResultSchema } from "./ordersResponses.js"

import type { UpdateOrderStatusParams } from "./ordersRequests.js"
import { UpdateOrderStatusParams as UpdateOrderStatusParamsSchema } from "./ordersRequests.js"

import type { UpdateOrderAddressesParams } from "./ordersRequests.js"
import { UpdateOrderAddressesParams as UpdateOrderAddressesParamsSchema } from "./ordersRequests.js"

import type { UpdateOrderTotalParams } from "./ordersRequests.js"
import { UpdateOrderTotalParams as UpdateOrderTotalParamsSchema } from "./ordersRequests.js"

import type { DeleteOrderParams } from "./ordersRequests.js"
import { DeleteOrderParams as DeleteOrderParamsSchema } from "./ordersRequests.js"
import type { CountOrdersByStatusResult } from "./ordersResponses.js"
import { CountOrdersByStatusResult as CountOrdersByStatusResultSchema } from "./ordersResponses.js"

import type { GetCustomerOrderStatsParams } from "./ordersRequests.js"
import { GetCustomerOrderStatsParams as GetCustomerOrderStatsParamsSchema } from "./ordersRequests.js"
import type { GetCustomerOrderStatsResult } from "./ordersResponses.js"
import { GetCustomerOrderStatsResult as GetCustomerOrderStatsResultSchema } from "./ordersResponses.js"

import type { GetOrdersWithLineCountParams } from "./ordersRequests.js"
import { GetOrdersWithLineCountParams as GetOrdersWithLineCountParamsSchema } from "./ordersRequests.js"
import type { GetOrdersWithLineCountResult } from "./ordersResponses.js"
import { GetOrdersWithLineCountResult as GetOrdersWithLineCountResultSchema } from "./ordersResponses.js"

import type { GetOrderLineParams } from "./ordersRequests.js"
import { GetOrderLineParams as GetOrderLineParamsSchema } from "./ordersRequests.js"
import type { GetOrderLineResult } from "./ordersResponses.js"
import { GetOrderLineResult as GetOrderLineResultSchema } from "./ordersResponses.js"

import type { ListOrderLinesParams } from "./ordersRequests.js"
import { ListOrderLinesParams as ListOrderLinesParamsSchema } from "./ordersRequests.js"
import type { ListOrderLinesResult } from "./ordersResponses.js"
import { ListOrderLinesResult as ListOrderLinesResultSchema } from "./ordersResponses.js"

import type { ListOrderLinesWithProductParams } from "./ordersRequests.js"
import { ListOrderLinesWithProductParams as ListOrderLinesWithProductParamsSchema } from "./ordersRequests.js"
import type { ListOrderLinesWithProductResult } from "./ordersResponses.js"
import { ListOrderLinesWithProductResult as ListOrderLinesWithProductResultSchema } from "./ordersResponses.js"

import type { GetFullOrderDetailsParams } from "./ordersRequests.js"
import { GetFullOrderDetailsParams as GetFullOrderDetailsParamsSchema } from "./ordersRequests.js"
import type { GetFullOrderDetailsResult } from "./ordersResponses.js"
import { GetFullOrderDetailsResult as GetFullOrderDetailsResultSchema } from "./ordersResponses.js"

import type { CreateOrderLineParams } from "./ordersRequests.js"
import { CreateOrderLineParams as CreateOrderLineParamsSchema } from "./ordersRequests.js"
import type { CreateOrderLineResult } from "./ordersResponses.js"
import { CreateOrderLineResult as CreateOrderLineResultSchema } from "./ordersResponses.js"

import type { UpdateOrderLineQuantityParams } from "./ordersRequests.js"
import { UpdateOrderLineQuantityParams as UpdateOrderLineQuantityParamsSchema } from "./ordersRequests.js"

import type { DeleteOrderLineParams } from "./ordersRequests.js"
import { DeleteOrderLineParams as DeleteOrderLineParamsSchema } from "./ordersRequests.js"

import type { DeleteOrderLinesParams } from "./ordersRequests.js"
import { DeleteOrderLinesParams as DeleteOrderLinesParamsSchema } from "./ordersRequests.js"

import type { GetOrderLineTotalParams } from "./ordersRequests.js"
import { GetOrderLineTotalParams as GetOrderLineTotalParamsSchema } from "./ordersRequests.js"
import type { GetOrderLineTotalResult } from "./ordersResponses.js"
import { GetOrderLineTotalResult as GetOrderLineTotalResultSchema } from "./ordersResponses.js"

import type { GetProductSalesStatsParams } from "./ordersRequests.js"
import { GetProductSalesStatsParams as GetProductSalesStatsParamsSchema } from "./ordersRequests.js"
import type { GetProductSalesStatsResult } from "./ordersResponses.js"
import { GetProductSalesStatsResult as GetProductSalesStatsResultSchema } from "./ordersResponses.js"

import type { GetTopSellingProductsParams } from "./ordersRequests.js"
import { GetTopSellingProductsParams as GetTopSellingProductsParamsSchema } from "./ordersRequests.js"
import type { GetTopSellingProductsResult } from "./ordersResponses.js"
import { GetTopSellingProductsResult as GetTopSellingProductsResultSchema } from "./ordersResponses.js"

import type { GetOrdersByProductIdsParams } from "./ordersRequests.js"
import { GetOrdersByProductIdsParams as GetOrdersByProductIdsParamsSchema } from "./ordersRequests.js"
import type { GetOrdersByProductIdsResult } from "./ordersResponses.js"
import { GetOrdersByProductIdsResult as GetOrdersByProductIdsResultSchema } from "./ordersResponses.js"

// GetOrder
// SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
// FROM orders
// WHERE id = $1
export async function getOrder(client: SqlClient, params: GetOrderParams): Promise<QueryResult<GetOrderResult | null>> {
  const inputParsed = GetOrderParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
WHERE id = $1`,
    [inputParsed.data.id]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = GetOrderResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetOrderWithCustomer
// SELECT
//     o.id, o.status, o.total_cents, o.shipping_address, o.billing_address, o.notes, o.created_at, o.updated_at,
//     c.id AS customer_id, c.email AS customer_email, c.name AS customer_name, c.phone AS customer_phone
// FROM orders o
// JOIN customers c ON o.customer_id = c.id
// WHERE o.id = $1
export async function getOrderWithCustomer(client: SqlClient, params: GetOrderWithCustomerParams): Promise<QueryResult<GetOrderWithCustomerResult | null>> {
  const inputParsed = GetOrderWithCustomerParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT
    o.id, o.status, o.total_cents, o.shipping_address, o.billing_address, o.notes, o.created_at, o.updated_at,
    c.id AS customer_id, c.email AS customer_email, c.name AS customer_name, c.phone AS customer_phone
FROM orders o
JOIN customers c ON o.customer_id = c.id
WHERE o.id = $1`,
    [inputParsed.data.id]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = GetOrderWithCustomerResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListOrders
// SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
// FROM orders
// ORDER BY created_at DESC
export async function listOrders(client: SqlClient): Promise<QueryResult<ListOrdersResult[]>> {
  const result = await client.query(
    `SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
ORDER BY created_at DESC`,
    []
  )

  const outputParsed = ListOrdersResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListOrdersByCustomer
// SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
// FROM orders
// WHERE customer_id = $1
// ORDER BY created_at DESC
export async function listOrdersByCustomer(client: SqlClient, params: ListOrdersByCustomerParams): Promise<QueryResult<ListOrdersByCustomerResult[]>> {
  const inputParsed = ListOrdersByCustomerParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
WHERE customer_id = $1
ORDER BY created_at DESC`,
    [inputParsed.data.customerId]
  )

  const outputParsed = ListOrdersByCustomerResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListOrdersByStatus
// SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
// FROM orders
// WHERE status = $1
// ORDER BY created_at DESC
export async function listOrdersByStatus(client: SqlClient, params: ListOrdersByStatusParams): Promise<QueryResult<ListOrdersByStatusResult[]>> {
  const inputParsed = ListOrdersByStatusParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
WHERE status = $1
ORDER BY created_at DESC`,
    [inputParsed.data.status]
  )

  const outputParsed = ListOrdersByStatusResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListOrdersPaginated
// SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
// FROM orders
// ORDER BY created_at DESC
// LIMIT $1 OFFSET $2
export async function listOrdersPaginated(client: SqlClient, params: ListOrdersPaginatedParams): Promise<QueryResult<ListOrdersPaginatedResult[]>> {
  const inputParsed = ListOrdersPaginatedParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
ORDER BY created_at DESC
LIMIT $1 OFFSET $2`,
    [inputParsed.data.limit, inputParsed.data.offset]
  )

  const outputParsed = ListOrdersPaginatedResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListOrdersByDateRange
// SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
// FROM orders
// WHERE created_at >= $1 AND created_at < $2
// ORDER BY created_at DESC
export async function listOrdersByDateRange(client: SqlClient, params: ListOrdersByDateRangeParams): Promise<QueryResult<ListOrdersByDateRangeResult[]>> {
  const inputParsed = ListOrdersByDateRangeParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
WHERE created_at >= $1 AND created_at < $2
ORDER BY created_at DESC`,
    [inputParsed.data.createdAt, inputParsed.data.createdAt2]
  )

  const outputParsed = ListOrdersByDateRangeResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListOrdersByDateRangeNamed
// SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
// FROM orders
// WHERE created_at >= $1 AND created_at < $2
// ORDER BY created_at DESC
export async function listOrdersByDateRangeNamed(client: SqlClient, params: ListOrdersByDateRangeNamedParams): Promise<QueryResult<ListOrdersByDateRangeNamedResult[]>> {
  const inputParsed = ListOrdersByDateRangeNamedParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
WHERE created_at >= $1 AND created_at < $2
ORDER BY created_at DESC`,
    [inputParsed.data.startDate, inputParsed.data.endDate]
  )

  const outputParsed = ListOrdersByDateRangeNamedResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListRecentOrdersWithCustomer
// SELECT
//     o.id, o.status, o.total_cents, o.created_at,
//     c.name AS customer_name, c.email AS customer_email
// FROM orders o
// JOIN customers c ON o.customer_id = c.id
// ORDER BY o.created_at DESC
// LIMIT $1
export async function listRecentOrdersWithCustomer(client: SqlClient, params: ListRecentOrdersWithCustomerParams): Promise<QueryResult<ListRecentOrdersWithCustomerResult[]>> {
  const inputParsed = ListRecentOrdersWithCustomerParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT
    o.id, o.status, o.total_cents, o.created_at,
    c.name AS customer_name, c.email AS customer_email
FROM orders o
JOIN customers c ON o.customer_id = c.id
ORDER BY o.created_at DESC
LIMIT $1`,
    [inputParsed.data.limit]
  )

  const outputParsed = ListRecentOrdersWithCustomerResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// SearchOrders
// SELECT id, customer_id, status, total_cents, shipping_address, notes, created_at
// FROM orders
// WHERE search_vector @@ websearch_to_tsquery('english', $1)
// ORDER BY created_at DESC
export async function searchOrders(client: SqlClient, params: SearchOrdersParams): Promise<QueryResult<SearchOrdersResult[]>> {
  const inputParsed = SearchOrdersParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, customer_id, status, total_cents, shipping_address, notes, created_at
FROM orders
WHERE search_vector @@ websearch_to_tsquery('english', $1)
ORDER BY created_at DESC`,
    [inputParsed.data.websearchToTsquery]
  )

  const outputParsed = SearchOrdersResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// CreateOrder
// INSERT INTO orders (customer_id, status, shipping_address, billing_address, notes)
// VALUES ($1, $2, $3, $4, $5)
// RETURNING id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
export async function createOrder(client: SqlClient, params: CreateOrderParams): Promise<QueryResult<CreateOrderResult | null>> {
  const inputParsed = CreateOrderParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `INSERT INTO orders (customer_id, status, shipping_address, billing_address, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at`,
    [inputParsed.data.customerId, inputParsed.data.status, inputParsed.data.shippingAddress, inputParsed.data.billingAddress, inputParsed.data.notes]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = CreateOrderResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// UpdateOrderStatus
// UPDATE orders
// SET status = $2, updated_at = NOW()
// WHERE id = $1
export async function updateOrderStatus(client: SqlClient, params: UpdateOrderStatusParams): Promise<QueryResult<void>> {
  const inputParsed = UpdateOrderStatusParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  await client.query(
    `UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1`,
    [inputParsed.data.id, inputParsed.data.status]
  )

  return { success: true, data: undefined }
}

// UpdateOrderAddresses
// UPDATE orders
// SET shipping_address = $2, billing_address = $3, updated_at = NOW()
// WHERE id = $1
export async function updateOrderAddresses(client: SqlClient, params: UpdateOrderAddressesParams): Promise<QueryResult<void>> {
  const inputParsed = UpdateOrderAddressesParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  await client.query(
    `UPDATE orders
SET shipping_address = $2, billing_address = $3, updated_at = NOW()
WHERE id = $1`,
    [inputParsed.data.id, inputParsed.data.shippingAddress, inputParsed.data.billingAddress]
  )

  return { success: true, data: undefined }
}

// UpdateOrderTotal
// UPDATE orders
// SET total_cents = (
//     SELECT COALESCE(SUM((unit_price_cents * quantity) - discount_cents), 0)
//     FROM order_lines
//     WHERE order_id = $1
// ), updated_at = NOW()
// WHERE id = $1
export async function updateOrderTotal(client: SqlClient, params: UpdateOrderTotalParams): Promise<QueryResult<void>> {
  const inputParsed = UpdateOrderTotalParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  await client.query(
    `UPDATE orders
SET total_cents = (
    SELECT COALESCE(SUM((unit_price_cents * quantity) - discount_cents), 0)
    FROM order_lines
    WHERE order_id = $1
), updated_at = NOW()
WHERE id = $1`,
    [inputParsed.data.orderId]
  )

  return { success: true, data: undefined }
}

// DeleteOrder
// DELETE FROM orders
// WHERE id = $1
export async function deleteOrder(client: SqlClient, params: DeleteOrderParams): Promise<QueryResult<void>> {
  const inputParsed = DeleteOrderParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  await client.query(
    `DELETE FROM orders
WHERE id = $1`,
    [inputParsed.data.id]
  )

  return { success: true, data: undefined }
}

// CountOrdersByStatus
// SELECT status, COUNT(*) AS order_count
// FROM orders
// GROUP BY status
// ORDER BY order_count DESC
export async function countOrdersByStatus(client: SqlClient): Promise<QueryResult<CountOrdersByStatusResult[]>> {
  const result = await client.query(
    `SELECT status, COUNT(*) AS order_count
FROM orders
GROUP BY status
ORDER BY order_count DESC`,
    []
  )

  const outputParsed = CountOrdersByStatusResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetCustomerOrderStats
// SELECT
//     COUNT(*) AS total_orders,
//     COALESCE(SUM(total_cents), 0) AS total_spent,
//     COALESCE(AVG(total_cents), 0) AS avg_order_value
// FROM orders
// WHERE customer_id = $1
export async function getCustomerOrderStats(client: SqlClient, params: GetCustomerOrderStatsParams): Promise<QueryResult<GetCustomerOrderStatsResult | null>> {
  const inputParsed = GetCustomerOrderStatsParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT
    COUNT(*) AS total_orders,
    COALESCE(SUM(total_cents), 0) AS total_spent,
    COALESCE(AVG(total_cents), 0) AS avg_order_value
FROM orders
WHERE customer_id = $1`,
    [inputParsed.data.customerId]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = GetCustomerOrderStatsResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetOrdersWithLineCount
// SELECT
//     o.id, o.customer_id, o.status, o.total_cents, o.created_at,
//     COUNT(ol.id) AS line_count
// FROM orders o
// LEFT JOIN order_lines ol ON o.id = ol.order_id
// GROUP BY o.id
// ORDER BY o.created_at DESC
// LIMIT $1 OFFSET $2
export async function getOrdersWithLineCount(client: SqlClient, params: GetOrdersWithLineCountParams): Promise<QueryResult<GetOrdersWithLineCountResult[]>> {
  const inputParsed = GetOrdersWithLineCountParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT
    o.id, o.customer_id, o.status, o.total_cents, o.created_at,
    COUNT(ol.id) AS line_count
FROM orders o
LEFT JOIN order_lines ol ON o.id = ol.order_id
GROUP BY o.id
ORDER BY o.created_at DESC
LIMIT $1 OFFSET $2`,
    [inputParsed.data.limit, inputParsed.data.offset]
  )

  const outputParsed = GetOrdersWithLineCountResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetOrderLine
//
// SELECT id, order_id, product_id, quantity, unit_price_cents, discount_cents, created_at
// FROM order_lines
// WHERE id = $1
export async function getOrderLine(client: SqlClient, params: GetOrderLineParams): Promise<QueryResult<GetOrderLineResult | null>> {
  const inputParsed = GetOrderLineParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `
SELECT id, order_id, product_id, quantity, unit_price_cents, discount_cents, created_at
FROM order_lines
WHERE id = $1`,
    [inputParsed.data.id]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = GetOrderLineResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListOrderLines
// SELECT id, order_id, product_id, quantity, unit_price_cents, discount_cents, created_at
// FROM order_lines
// WHERE order_id = $1
// ORDER BY created_at
export async function listOrderLines(client: SqlClient, params: ListOrderLinesParams): Promise<QueryResult<ListOrderLinesResult[]>> {
  const inputParsed = ListOrderLinesParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, order_id, product_id, quantity, unit_price_cents, discount_cents, created_at
FROM order_lines
WHERE order_id = $1
ORDER BY created_at`,
    [inputParsed.data.orderId]
  )

  const outputParsed = ListOrderLinesResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListOrderLinesWithProduct
// SELECT
//     ol.id, ol.order_id, ol.quantity, ol.unit_price_cents, ol.discount_cents, ol.created_at,
//     p.id AS product_id, p.sku AS product_sku, p.name AS product_name
// FROM order_lines ol
// JOIN products p ON ol.product_id = p.id
// WHERE ol.order_id = $1
// ORDER BY ol.created_at
export async function listOrderLinesWithProduct(client: SqlClient, params: ListOrderLinesWithProductParams): Promise<QueryResult<ListOrderLinesWithProductResult[]>> {
  const inputParsed = ListOrderLinesWithProductParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT
    ol.id, ol.order_id, ol.quantity, ol.unit_price_cents, ol.discount_cents, ol.created_at,
    p.id AS product_id, p.sku AS product_sku, p.name AS product_name
FROM order_lines ol
JOIN products p ON ol.product_id = p.id
WHERE ol.order_id = $1
ORDER BY ol.created_at`,
    [inputParsed.data.orderId]
  )

  const outputParsed = ListOrderLinesWithProductResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetFullOrderDetails
// SELECT
//     o.id AS order_id, o.status, o.total_cents AS order_total, o.shipping_address, o.created_at AS order_date,
//     c.id AS customer_id, c.name AS customer_name, c.email AS customer_email,
//     ol.id AS line_id, ol.quantity, ol.unit_price_cents, ol.discount_cents,
//     p.id AS product_id, p.sku, p.name AS product_name
// FROM orders o
// JOIN customers c ON o.customer_id = c.id
// JOIN order_lines ol ON o.id = ol.order_id
// JOIN products p ON ol.product_id = p.id
// WHERE o.id = $1
// ORDER BY ol.created_at
export async function getFullOrderDetails(client: SqlClient, params: GetFullOrderDetailsParams): Promise<QueryResult<GetFullOrderDetailsResult[]>> {
  const inputParsed = GetFullOrderDetailsParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT
    o.id AS order_id, o.status, o.total_cents AS order_total, o.shipping_address, o.created_at AS order_date,
    c.id AS customer_id, c.name AS customer_name, c.email AS customer_email,
    ol.id AS line_id, ol.quantity, ol.unit_price_cents, ol.discount_cents,
    p.id AS product_id, p.sku, p.name AS product_name
FROM orders o
JOIN customers c ON o.customer_id = c.id
JOIN order_lines ol ON o.id = ol.order_id
JOIN products p ON ol.product_id = p.id
WHERE o.id = $1
ORDER BY ol.created_at`,
    [inputParsed.data.id]
  )

  const outputParsed = GetFullOrderDetailsResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// CreateOrderLine
// INSERT INTO order_lines (order_id, product_id, quantity, unit_price_cents, discount_cents)
// VALUES ($1, $2, $3, $4, $5)
// RETURNING id, order_id, product_id, quantity, unit_price_cents, discount_cents, created_at
export async function createOrderLine(client: SqlClient, params: CreateOrderLineParams): Promise<QueryResult<CreateOrderLineResult | null>> {
  const inputParsed = CreateOrderLineParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `INSERT INTO order_lines (order_id, product_id, quantity, unit_price_cents, discount_cents)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, product_id, quantity, unit_price_cents, discount_cents, created_at`,
    [inputParsed.data.orderId, inputParsed.data.productId, inputParsed.data.quantity, inputParsed.data.unitPriceCents, inputParsed.data.discountCents]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = CreateOrderLineResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// UpdateOrderLineQuantity
// UPDATE order_lines
// SET quantity = $2
// WHERE id = $1
export async function updateOrderLineQuantity(client: SqlClient, params: UpdateOrderLineQuantityParams): Promise<QueryResult<void>> {
  const inputParsed = UpdateOrderLineQuantityParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  await client.query(
    `UPDATE order_lines
SET quantity = $2
WHERE id = $1`,
    [inputParsed.data.id, inputParsed.data.quantity]
  )

  return { success: true, data: undefined }
}

// DeleteOrderLine
// DELETE FROM order_lines
// WHERE id = $1
export async function deleteOrderLine(client: SqlClient, params: DeleteOrderLineParams): Promise<QueryResult<void>> {
  const inputParsed = DeleteOrderLineParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  await client.query(
    `DELETE FROM order_lines
WHERE id = $1`,
    [inputParsed.data.id]
  )

  return { success: true, data: undefined }
}

// DeleteOrderLines
// DELETE FROM order_lines
// WHERE order_id = $1
export async function deleteOrderLines(client: SqlClient, params: DeleteOrderLinesParams): Promise<QueryResult<number>> {
  const inputParsed = DeleteOrderLinesParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `DELETE FROM order_lines
WHERE order_id = $1`,
    [inputParsed.data.orderId]
  )

  return { success: true, data: result.rowCount || 0 }
}

// GetOrderLineTotal
// SELECT
//     COALESCE(SUM((unit_price_cents * quantity) - discount_cents), 0) AS total
// FROM order_lines
// WHERE order_id = $1
export async function getOrderLineTotal(client: SqlClient, params: GetOrderLineTotalParams): Promise<QueryResult<GetOrderLineTotalResult | null>> {
  const inputParsed = GetOrderLineTotalParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT
    COALESCE(SUM((unit_price_cents * quantity) - discount_cents), 0) AS total
FROM order_lines
WHERE order_id = $1`,
    [inputParsed.data.orderId]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = GetOrderLineTotalResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetProductSalesStats
// SELECT
//     p.id, p.sku, p.name,
//     COALESCE(SUM(ol.quantity), 0) AS total_sold,
//     COALESCE(SUM(ol.quantity * ol.unit_price_cents), 0) AS total_revenue
// FROM products p
// LEFT JOIN order_lines ol ON p.id = ol.product_id
// WHERE p.id = $1
// GROUP BY p.id
export async function getProductSalesStats(client: SqlClient, params: GetProductSalesStatsParams): Promise<QueryResult<GetProductSalesStatsResult | null>> {
  const inputParsed = GetProductSalesStatsParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT
    p.id, p.sku, p.name,
    COALESCE(SUM(ol.quantity), 0) AS total_sold,
    COALESCE(SUM(ol.quantity * ol.unit_price_cents), 0) AS total_revenue
FROM products p
LEFT JOIN order_lines ol ON p.id = ol.product_id
WHERE p.id = $1
GROUP BY p.id`,
    [inputParsed.data.id]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = GetProductSalesStatsResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetTopSellingProducts
// SELECT
//     p.id, p.sku, p.name, p.category,
//     SUM(ol.quantity) AS total_sold,
//     SUM(ol.quantity * ol.unit_price_cents) AS total_revenue
// FROM products p
// JOIN order_lines ol ON p.id = ol.product_id
// GROUP BY p.id
// ORDER BY total_sold DESC
// LIMIT $1
export async function getTopSellingProducts(client: SqlClient, params: GetTopSellingProductsParams): Promise<QueryResult<GetTopSellingProductsResult[]>> {
  const inputParsed = GetTopSellingProductsParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT
    p.id, p.sku, p.name, p.category,
    SUM(ol.quantity) AS total_sold,
    SUM(ol.quantity * ol.unit_price_cents) AS total_revenue
FROM products p
JOIN order_lines ol ON p.id = ol.product_id
GROUP BY p.id
ORDER BY total_sold DESC
LIMIT $1`,
    [inputParsed.data.limit]
  )

  const outputParsed = GetTopSellingProductsResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetOrdersByProductIds
// SELECT DISTINCT o.id, o.customer_id, o.status, o.total_cents, o.created_at
// FROM orders o
// JOIN order_lines ol ON o.id = ol.order_id
// WHERE ol.product_id = ANY($1::int[])
// ORDER BY o.created_at DESC
export async function getOrdersByProductIds(client: SqlClient, params: GetOrdersByProductIdsParams): Promise<QueryResult<GetOrdersByProductIdsResult[]>> {
  const inputParsed = GetOrdersByProductIdsParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT DISTINCT o.id, o.customer_id, o.status, o.total_cents, o.created_at
FROM orders o
JOIN order_lines ol ON o.id = ol.order_id
WHERE ol.product_id = ANY($1::int[])
ORDER BY o.created_at DESC`,
    [inputParsed.data.productIds]
  )

  const outputParsed = GetOrdersByProductIdsResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}
