// Generated by sqlc v1.31.1, plugin: sqlc-effect dev
import { z } from "zod"

// GetOrder - Row
export const GetOrderRow = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetOrderRow = z.infer<typeof GetOrderRow>

// GetOrder - Result
export const GetOrderResult = GetOrderRow.transform((row) => ({
  id: row.id,
  customer_id: row.customer_id,
  status: row.status,
  total_cents: row.total_cents,
  shipping_address: row.shipping_address,
  billing_address: row.billing_address,
  notes: row.notes,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type GetOrderResult = z.infer<typeof GetOrderResult>

// GetOrderWithCustomer - Row
export const GetOrderWithCustomerRow = z.object({
  id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
  customer_id: z.number(),
  customer_email: z.string(),
  customer_name: z.string(),
  customer_phone: z.string().nullable(),
})

export type GetOrderWithCustomerRow = z.infer<typeof GetOrderWithCustomerRow>

// GetOrderWithCustomer - Result
export const GetOrderWithCustomerResult = GetOrderWithCustomerRow.transform((row) => ({
  id: row.id,
  status: row.status,
  total_cents: row.total_cents,
  shipping_address: row.shipping_address,
  billing_address: row.billing_address,
  notes: row.notes,
  created_at: row.created_at,
  updated_at: row.updated_at,
  customer_id: row.customer_id,
  customer_email: row.customer_email,
  customer_name: row.customer_name,
  customer_phone: row.customer_phone,
}))

export type GetOrderWithCustomerResult = z.infer<typeof GetOrderWithCustomerResult>

// ListOrders - Row
export const ListOrdersRow = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListOrdersRow = z.infer<typeof ListOrdersRow>

// ListOrders - Result
export const ListOrdersResult = ListOrdersRow.transform((row) => ({
  id: row.id,
  customer_id: row.customer_id,
  status: row.status,
  total_cents: row.total_cents,
  shipping_address: row.shipping_address,
  billing_address: row.billing_address,
  notes: row.notes,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListOrdersResult = z.infer<typeof ListOrdersResult>

// ListOrdersByCustomer - Row
export const ListOrdersByCustomerRow = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListOrdersByCustomerRow = z.infer<typeof ListOrdersByCustomerRow>

// ListOrdersByCustomer - Result
export const ListOrdersByCustomerResult = ListOrdersByCustomerRow.transform((row) => ({
  id: row.id,
  customer_id: row.customer_id,
  status: row.status,
  total_cents: row.total_cents,
  shipping_address: row.shipping_address,
  billing_address: row.billing_address,
  notes: row.notes,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListOrdersByCustomerResult = z.infer<typeof ListOrdersByCustomerResult>

// ListOrdersByStatus - Row
export const ListOrdersByStatusRow = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListOrdersByStatusRow = z.infer<typeof ListOrdersByStatusRow>

// ListOrdersByStatus - Result
export const ListOrdersByStatusResult = ListOrdersByStatusRow.transform((row) => ({
  id: row.id,
  customer_id: row.customer_id,
  status: row.status,
  total_cents: row.total_cents,
  shipping_address: row.shipping_address,
  billing_address: row.billing_address,
  notes: row.notes,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListOrdersByStatusResult = z.infer<typeof ListOrdersByStatusResult>

// ListOrdersPaginated - Row
export const ListOrdersPaginatedRow = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListOrdersPaginatedRow = z.infer<typeof ListOrdersPaginatedRow>

// ListOrdersPaginated - Result
export const ListOrdersPaginatedResult = ListOrdersPaginatedRow.transform((row) => ({
  id: row.id,
  customer_id: row.customer_id,
  status: row.status,
  total_cents: row.total_cents,
  shipping_address: row.shipping_address,
  billing_address: row.billing_address,
  notes: row.notes,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListOrdersPaginatedResult = z.infer<typeof ListOrdersPaginatedResult>

// ListOrdersByDateRange - Row
export const ListOrdersByDateRangeRow = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListOrdersByDateRangeRow = z.infer<typeof ListOrdersByDateRangeRow>

// ListOrdersByDateRange - Result
export const ListOrdersByDateRangeResult = ListOrdersByDateRangeRow.transform((row) => ({
  id: row.id,
  customer_id: row.customer_id,
  status: row.status,
  total_cents: row.total_cents,
  shipping_address: row.shipping_address,
  billing_address: row.billing_address,
  notes: row.notes,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListOrdersByDateRangeResult = z.infer<typeof ListOrdersByDateRangeResult>

// ListOrdersByDateRangeNamed - Row
export const ListOrdersByDateRangeNamedRow = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListOrdersByDateRangeNamedRow = z.infer<typeof ListOrdersByDateRangeNamedRow>

// ListOrdersByDateRangeNamed - Result
export const ListOrdersByDateRangeNamedResult = ListOrdersByDateRangeNamedRow.transform((row) => ({
  id: row.id,
  customer_id: row.customer_id,
  status: row.status,
  total_cents: row.total_cents,
  shipping_address: row.shipping_address,
  billing_address: row.billing_address,
  notes: row.notes,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListOrdersByDateRangeNamedResult = z.infer<typeof ListOrdersByDateRangeNamedResult>

// ListRecentOrdersWithCustomer - Row
export const ListRecentOrdersWithCustomerRow = z.object({
  id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  created_at: z.coerce.date(),
  customer_name: z.string(),
  customer_email: z.string(),
})

export type ListRecentOrdersWithCustomerRow = z.infer<typeof ListRecentOrdersWithCustomerRow>

// ListRecentOrdersWithCustomer - Result
export const ListRecentOrdersWithCustomerResult = ListRecentOrdersWithCustomerRow.transform((row) => ({
  id: row.id,
  status: row.status,
  total_cents: row.total_cents,
  created_at: row.created_at,
  customer_name: row.customer_name,
  customer_email: row.customer_email,
}))

export type ListRecentOrdersWithCustomerResult = z.infer<typeof ListRecentOrdersWithCustomerResult>

// SearchOrders - Row
export const SearchOrdersRow = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
})

export type SearchOrdersRow = z.infer<typeof SearchOrdersRow>

// SearchOrders - Result
export const SearchOrdersResult = SearchOrdersRow.transform((row) => ({
  id: row.id,
  customer_id: row.customer_id,
  status: row.status,
  total_cents: row.total_cents,
  shipping_address: row.shipping_address,
  notes: row.notes,
  created_at: row.created_at,
}))

export type SearchOrdersResult = z.infer<typeof SearchOrdersResult>

// CreateOrder - Row
export const CreateOrderRow = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type CreateOrderRow = z.infer<typeof CreateOrderRow>

// CreateOrder - Result
export const CreateOrderResult = CreateOrderRow.transform((row) => ({
  id: row.id,
  customer_id: row.customer_id,
  status: row.status,
  total_cents: row.total_cents,
  shipping_address: row.shipping_address,
  billing_address: row.billing_address,
  notes: row.notes,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type CreateOrderResult = z.infer<typeof CreateOrderResult>

// CountOrdersByStatus - Row
export const CountOrdersByStatusRow = z.object({
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  order_count: z.coerce.bigint(),
})

export type CountOrdersByStatusRow = z.infer<typeof CountOrdersByStatusRow>

// CountOrdersByStatus - Result
export const CountOrdersByStatusResult = CountOrdersByStatusRow.transform((row) => ({
  status: row.status,
  order_count: row.order_count,
}))

export type CountOrdersByStatusResult = z.infer<typeof CountOrdersByStatusResult>

// GetCustomerOrderStats - Row
export const GetCustomerOrderStatsRow = z.object({
  total_orders: z.coerce.bigint(),
  total_spent: z.unknown().nullable(),
  avg_order_value: z.unknown().nullable(),
})

export type GetCustomerOrderStatsRow = z.infer<typeof GetCustomerOrderStatsRow>

// GetCustomerOrderStats - Result
export const GetCustomerOrderStatsResult = GetCustomerOrderStatsRow.transform((row) => ({
  total_orders: row.total_orders,
  total_spent: row.total_spent,
  avg_order_value: row.avg_order_value,
}))

export type GetCustomerOrderStatsResult = z.infer<typeof GetCustomerOrderStatsResult>

// GetOrdersWithLineCount - Row
export const GetOrdersWithLineCountRow = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  created_at: z.coerce.date(),
  line_count: z.coerce.bigint(),
})

export type GetOrdersWithLineCountRow = z.infer<typeof GetOrdersWithLineCountRow>

// GetOrdersWithLineCount - Result
export const GetOrdersWithLineCountResult = GetOrdersWithLineCountRow.transform((row) => ({
  id: row.id,
  customer_id: row.customer_id,
  status: row.status,
  total_cents: row.total_cents,
  created_at: row.created_at,
  line_count: row.line_count,
}))

export type GetOrdersWithLineCountResult = z.infer<typeof GetOrdersWithLineCountResult>

// GetOrderLine - Row
export const GetOrderLineRow = z.object({
  id: z.number(),
  order_id: z.number(),
  product_id: z.number(),
  quantity: z.number(),
  unit_price_cents: z.number(),
  discount_cents: z.number(),
  created_at: z.coerce.date(),
})

export type GetOrderLineRow = z.infer<typeof GetOrderLineRow>

// GetOrderLine - Result
export const GetOrderLineResult = GetOrderLineRow.transform((row) => ({
  id: row.id,
  order_id: row.order_id,
  product_id: row.product_id,
  quantity: row.quantity,
  unit_price_cents: row.unit_price_cents,
  discount_cents: row.discount_cents,
  created_at: row.created_at,
}))

export type GetOrderLineResult = z.infer<typeof GetOrderLineResult>

// ListOrderLines - Row
export const ListOrderLinesRow = z.object({
  id: z.number(),
  order_id: z.number(),
  product_id: z.number(),
  quantity: z.number(),
  unit_price_cents: z.number(),
  discount_cents: z.number(),
  created_at: z.coerce.date(),
})

export type ListOrderLinesRow = z.infer<typeof ListOrderLinesRow>

// ListOrderLines - Result
export const ListOrderLinesResult = ListOrderLinesRow.transform((row) => ({
  id: row.id,
  order_id: row.order_id,
  product_id: row.product_id,
  quantity: row.quantity,
  unit_price_cents: row.unit_price_cents,
  discount_cents: row.discount_cents,
  created_at: row.created_at,
}))

export type ListOrderLinesResult = z.infer<typeof ListOrderLinesResult>

// ListOrderLinesWithProduct - Row
export const ListOrderLinesWithProductRow = z.object({
  id: z.number(),
  order_id: z.number(),
  quantity: z.number(),
  unit_price_cents: z.number(),
  discount_cents: z.number(),
  created_at: z.coerce.date(),
  product_id: z.number(),
  product_sku: z.string(),
  product_name: z.string(),
})

export type ListOrderLinesWithProductRow = z.infer<typeof ListOrderLinesWithProductRow>

// ListOrderLinesWithProduct - Result
export const ListOrderLinesWithProductResult = ListOrderLinesWithProductRow.transform((row) => ({
  id: row.id,
  order_id: row.order_id,
  quantity: row.quantity,
  unit_price_cents: row.unit_price_cents,
  discount_cents: row.discount_cents,
  created_at: row.created_at,
  product_id: row.product_id,
  product_sku: row.product_sku,
  product_name: row.product_name,
}))

export type ListOrderLinesWithProductResult = z.infer<typeof ListOrderLinesWithProductResult>

// GetFullOrderDetails - Row
export const GetFullOrderDetailsRow = z.object({
  order_id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  order_total: z.number(),
  shipping_address: z.string().nullable(),
  order_date: z.coerce.date(),
  customer_id: z.number(),
  customer_name: z.string(),
  customer_email: z.string(),
  line_id: z.number(),
  quantity: z.number(),
  unit_price_cents: z.number(),
  discount_cents: z.number(),
  product_id: z.number(),
  sku: z.string(),
  product_name: z.string(),
})

export type GetFullOrderDetailsRow = z.infer<typeof GetFullOrderDetailsRow>

// GetFullOrderDetails - Result
export const GetFullOrderDetailsResult = GetFullOrderDetailsRow.transform((row) => ({
  order_id: row.order_id,
  status: row.status,
  order_total: row.order_total,
  shipping_address: row.shipping_address,
  order_date: row.order_date,
  customer_id: row.customer_id,
  customer_name: row.customer_name,
  customer_email: row.customer_email,
  line_id: row.line_id,
  quantity: row.quantity,
  unit_price_cents: row.unit_price_cents,
  discount_cents: row.discount_cents,
  product_id: row.product_id,
  sku: row.sku,
  product_name: row.product_name,
}))

export type GetFullOrderDetailsResult = z.infer<typeof GetFullOrderDetailsResult>

// CreateOrderLine - Row
export const CreateOrderLineRow = z.object({
  id: z.number(),
  order_id: z.number(),
  product_id: z.number(),
  quantity: z.number(),
  unit_price_cents: z.number(),
  discount_cents: z.number(),
  created_at: z.coerce.date(),
})

export type CreateOrderLineRow = z.infer<typeof CreateOrderLineRow>

// CreateOrderLine - Result
export const CreateOrderLineResult = CreateOrderLineRow.transform((row) => ({
  id: row.id,
  order_id: row.order_id,
  product_id: row.product_id,
  quantity: row.quantity,
  unit_price_cents: row.unit_price_cents,
  discount_cents: row.discount_cents,
  created_at: row.created_at,
}))

export type CreateOrderLineResult = z.infer<typeof CreateOrderLineResult>

// GetOrderLineTotal - Row
export const GetOrderLineTotalRow = z.object({
  total: z.unknown().nullable(),
})

export type GetOrderLineTotalRow = z.infer<typeof GetOrderLineTotalRow>

// GetOrderLineTotal - Result
export const GetOrderLineTotalResult = GetOrderLineTotalRow.transform((row) => ({
  total: row.total,
}))

export type GetOrderLineTotalResult = z.infer<typeof GetOrderLineTotalResult>

// GetProductSalesStats - Row
export const GetProductSalesStatsRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  total_sold: z.unknown().nullable(),
  total_revenue: z.unknown().nullable(),
})

export type GetProductSalesStatsRow = z.infer<typeof GetProductSalesStatsRow>

// GetProductSalesStats - Result
export const GetProductSalesStatsResult = GetProductSalesStatsRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  total_sold: row.total_sold,
  total_revenue: row.total_revenue,
}))

export type GetProductSalesStatsResult = z.infer<typeof GetProductSalesStatsResult>

// GetTopSellingProducts - Row
export const GetTopSellingProductsRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  category: z.string().nullable(),
  total_sold: z.coerce.bigint(),
  total_revenue: z.coerce.bigint(),
})

export type GetTopSellingProductsRow = z.infer<typeof GetTopSellingProductsRow>

// GetTopSellingProducts - Result
export const GetTopSellingProductsResult = GetTopSellingProductsRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  category: row.category,
  total_sold: row.total_sold,
  total_revenue: row.total_revenue,
}))

export type GetTopSellingProductsResult = z.infer<typeof GetTopSellingProductsResult>

// GetOrdersByProductIds - Row
export const GetOrdersByProductIdsRow = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  total_cents: z.number(),
  created_at: z.coerce.date(),
})

export type GetOrdersByProductIdsRow = z.infer<typeof GetOrdersByProductIdsRow>

// GetOrdersByProductIds - Result
export const GetOrdersByProductIdsResult = GetOrdersByProductIdsRow.transform((row) => ({
  id: row.id,
  customer_id: row.customer_id,
  status: row.status,
  total_cents: row.total_cents,
  created_at: row.created_at,
}))

export type GetOrdersByProductIdsResult = z.infer<typeof GetOrdersByProductIdsResult>
