// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { z } from "zod"

// GetOrder - Result
export const GetOrderResult = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetOrderResult = z.infer<typeof GetOrderResult>

// GetOrderWithCustomer - Result
export const GetOrderWithCustomerResult = z.object({
  id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
  customer_id: z.number(),
  customer_email: z.string(),
  customer_name: z.string(),
  customer_phone: z.string().nullable(),
})

export type GetOrderWithCustomerResult = z.infer<typeof GetOrderWithCustomerResult>

// ListOrders - Result
export const ListOrdersResult = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListOrdersResult = z.infer<typeof ListOrdersResult>

// ListOrdersByCustomer - Result
export const ListOrdersByCustomerResult = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListOrdersByCustomerResult = z.infer<typeof ListOrdersByCustomerResult>

// ListOrdersByStatus - Result
export const ListOrdersByStatusResult = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListOrdersByStatusResult = z.infer<typeof ListOrdersByStatusResult>

// ListOrdersPaginated - Result
export const ListOrdersPaginatedResult = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListOrdersPaginatedResult = z.infer<typeof ListOrdersPaginatedResult>

// ListOrdersByDateRange - Result
export const ListOrdersByDateRangeResult = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListOrdersByDateRangeResult = z.infer<typeof ListOrdersByDateRangeResult>

// ListOrdersByDateRangeNamed - Result
export const ListOrdersByDateRangeNamedResult = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListOrdersByDateRangeNamedResult = z.infer<typeof ListOrdersByDateRangeNamedResult>

// ListRecentOrdersWithCustomer - Result
export const ListRecentOrdersWithCustomerResult = z.object({
  id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  created_at: z.coerce.date(),
  customer_name: z.string(),
  customer_email: z.string(),
})

export type ListRecentOrdersWithCustomerResult = z.infer<typeof ListRecentOrdersWithCustomerResult>

// SearchOrders - Result
export const SearchOrdersResult = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
})

export type SearchOrdersResult = z.infer<typeof SearchOrdersResult>

// CreateOrder - Result
export const CreateOrderResult = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  shipping_address: z.string().nullable(),
  billing_address: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type CreateOrderResult = z.infer<typeof CreateOrderResult>

// CountOrdersByStatus - Result
export const CountOrdersByStatusResult = z.object({
  status: z.string(),
  order_count: z.coerce.bigint(),
})

export type CountOrdersByStatusResult = z.infer<typeof CountOrdersByStatusResult>

// GetCustomerOrderStats - Result
export const GetCustomerOrderStatsResult = z.object({
  total_orders: z.coerce.bigint(),
  total_spent: z.unknown().nullable(),
  avg_order_value: z.unknown().nullable(),
})

export type GetCustomerOrderStatsResult = z.infer<typeof GetCustomerOrderStatsResult>

// GetOrdersWithLineCount - Result
export const GetOrdersWithLineCountResult = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  created_at: z.coerce.date(),
  line_count: z.coerce.bigint(),
})

export type GetOrdersWithLineCountResult = z.infer<typeof GetOrdersWithLineCountResult>

// GetOrderLine - Result
export const GetOrderLineResult = z.object({
  id: z.number(),
  order_id: z.number(),
  product_id: z.number(),
  quantity: z.number(),
  unit_price_cents: z.number(),
  discount_cents: z.number(),
  created_at: z.coerce.date(),
})

export type GetOrderLineResult = z.infer<typeof GetOrderLineResult>

// ListOrderLines - Result
export const ListOrderLinesResult = z.object({
  id: z.number(),
  order_id: z.number(),
  product_id: z.number(),
  quantity: z.number(),
  unit_price_cents: z.number(),
  discount_cents: z.number(),
  created_at: z.coerce.date(),
})

export type ListOrderLinesResult = z.infer<typeof ListOrderLinesResult>

// ListOrderLinesWithProduct - Result
export const ListOrderLinesWithProductResult = z.object({
  id: z.number(),
  order_id: z.number(),
  quantity: z.number(),
  unit_price_cents: z.number(),
  discount_cents: z.number(),
  created_at: z.coerce.date(),
  product_id: z.number(),
  product_sku: z.string(),
  product_name: z.string(),
})

export type ListOrderLinesWithProductResult = z.infer<typeof ListOrderLinesWithProductResult>

// GetFullOrderDetails - Result
export const GetFullOrderDetailsResult = z.object({
  order_id: z.number(),
  status: z.string(),
  order_total: z.number(),
  shipping_address: z.string().nullable(),
  order_date: z.coerce.date(),
  customer_id: z.number(),
  customer_name: z.string(),
  customer_email: z.string(),
  line_id: z.number(),
  quantity: z.number(),
  unit_price_cents: z.number(),
  discount_cents: z.number(),
  product_id: z.number(),
  sku: z.string(),
  product_name: z.string(),
})

export type GetFullOrderDetailsResult = z.infer<typeof GetFullOrderDetailsResult>

// CreateOrderLine - Result
export const CreateOrderLineResult = z.object({
  id: z.number(),
  order_id: z.number(),
  product_id: z.number(),
  quantity: z.number(),
  unit_price_cents: z.number(),
  discount_cents: z.number(),
  created_at: z.coerce.date(),
})

export type CreateOrderLineResult = z.infer<typeof CreateOrderLineResult>

// GetOrderLineTotal - Result
export const GetOrderLineTotalResult = z.object({
  total: z.unknown().nullable(),
})

export type GetOrderLineTotalResult = z.infer<typeof GetOrderLineTotalResult>

// GetProductSalesStats - Result
export const GetProductSalesStatsResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  total_sold: z.unknown().nullable(),
  total_revenue: z.unknown().nullable(),
})

export type GetProductSalesStatsResult = z.infer<typeof GetProductSalesStatsResult>

// GetTopSellingProducts - Result
export const GetTopSellingProductsResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  category: z.string().nullable(),
  total_sold: z.coerce.bigint(),
  total_revenue: z.coerce.bigint(),
})

export type GetTopSellingProductsResult = z.infer<typeof GetTopSellingProductsResult>

// GetOrdersByProductIds - Result
export const GetOrdersByProductIdsResult = z.object({
  id: z.number(),
  customer_id: z.number(),
  status: z.string(),
  total_cents: z.number(),
  created_at: z.coerce.date(),
})

export type GetOrdersByProductIdsResult = z.infer<typeof GetOrdersByProductIdsResult>
