// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { z } from "zod"

// GetOrder - Parameters
export const GetOrderParams = z.object({
  id: z.number(),
})

export type GetOrderParams = z.infer<typeof GetOrderParams>

// GetOrderWithCustomer - Parameters
export const GetOrderWithCustomerParams = z.object({
  id: z.number(),
})

export type GetOrderWithCustomerParams = z.infer<typeof GetOrderWithCustomerParams>

// ListOrdersByCustomer - Parameters
export const ListOrdersByCustomerParams = z.object({
  customerId: z.number(),
})

export type ListOrdersByCustomerParams = z.infer<typeof ListOrdersByCustomerParams>

// ListOrdersByStatus - Parameters
export const ListOrdersByStatusParams = z.object({
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
})

export type ListOrdersByStatusParams = z.infer<typeof ListOrdersByStatusParams>

// ListOrdersPaginated - Parameters
export const ListOrdersPaginatedParams = z.object({
  limit: z.number(),
  offset: z.number(),
})

export type ListOrdersPaginatedParams = z.infer<typeof ListOrdersPaginatedParams>

// ListOrdersByDateRange - Parameters
export const ListOrdersByDateRangeParams = z.object({
  createdAt: z.coerce.date(),
  createdAt2: z.coerce.date(),
})

export type ListOrdersByDateRangeParams = z.infer<typeof ListOrdersByDateRangeParams>

// ListOrdersByDateRangeNamed - Parameters
export const ListOrdersByDateRangeNamedParams = z.object({
  startDate: z.coerce.date(),
  endDate: z.coerce.date(),
})

export type ListOrdersByDateRangeNamedParams = z.infer<typeof ListOrdersByDateRangeNamedParams>

// ListRecentOrdersWithCustomer - Parameters
export const ListRecentOrdersWithCustomerParams = z.object({
  limit: z.number(),
})

export type ListRecentOrdersWithCustomerParams = z.infer<typeof ListRecentOrdersWithCustomerParams>

// SearchOrders - Parameters
export const SearchOrdersParams = z.object({
  websearchToTsquery: z.string(),
})

export type SearchOrdersParams = z.infer<typeof SearchOrdersParams>

// CreateOrder - Parameters
export const CreateOrderParams = z.object({
  customerId: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
  shippingAddress: z.string().optional(),
  billingAddress: z.string().optional(),
  notes: z.string().optional(),
})

export type CreateOrderParams = z.infer<typeof CreateOrderParams>

// UpdateOrderStatus - Parameters
export const UpdateOrderStatusParams = z.object({
  id: z.number(),
  status: z.union([z.literal("pending"), z.literal("confirmed"), z.literal("processing"), z.literal("shipped"), z.literal("delivered"), z.literal("cancelled"), z.literal("refunded")]),
})

export type UpdateOrderStatusParams = z.infer<typeof UpdateOrderStatusParams>

// UpdateOrderAddresses - Parameters
export const UpdateOrderAddressesParams = z.object({
  id: z.number(),
  shippingAddress: z.string().optional(),
  billingAddress: z.string().optional(),
})

export type UpdateOrderAddressesParams = z.infer<typeof UpdateOrderAddressesParams>

// UpdateOrderTotal - Parameters
export const UpdateOrderTotalParams = z.object({
  orderId: z.number(),
})

export type UpdateOrderTotalParams = z.infer<typeof UpdateOrderTotalParams>

// DeleteOrder - Parameters
export const DeleteOrderParams = z.object({
  id: z.number(),
})

export type DeleteOrderParams = z.infer<typeof DeleteOrderParams>

// GetCustomerOrderStats - Parameters
export const GetCustomerOrderStatsParams = z.object({
  customerId: z.number(),
})

export type GetCustomerOrderStatsParams = z.infer<typeof GetCustomerOrderStatsParams>

// GetOrdersWithLineCount - Parameters
export const GetOrdersWithLineCountParams = z.object({
  limit: z.number(),
  offset: z.number(),
})

export type GetOrdersWithLineCountParams = z.infer<typeof GetOrdersWithLineCountParams>

// GetOrderLine - Parameters
export const GetOrderLineParams = z.object({
  id: z.number(),
})

export type GetOrderLineParams = z.infer<typeof GetOrderLineParams>

// ListOrderLines - Parameters
export const ListOrderLinesParams = z.object({
  orderId: z.number(),
})

export type ListOrderLinesParams = z.infer<typeof ListOrderLinesParams>

// ListOrderLinesWithProduct - Parameters
export const ListOrderLinesWithProductParams = z.object({
  orderId: z.number(),
})

export type ListOrderLinesWithProductParams = z.infer<typeof ListOrderLinesWithProductParams>

// GetFullOrderDetails - Parameters
export const GetFullOrderDetailsParams = z.object({
  id: z.number(),
})

export type GetFullOrderDetailsParams = z.infer<typeof GetFullOrderDetailsParams>

// CreateOrderLine - Parameters
export const CreateOrderLineParams = z.object({
  orderId: z.number(),
  productId: z.number(),
  quantity: z.number(),
  unitPriceCents: z.number(),
  discountCents: z.number(),
})

export type CreateOrderLineParams = z.infer<typeof CreateOrderLineParams>

// UpdateOrderLineQuantity - Parameters
export const UpdateOrderLineQuantityParams = z.object({
  id: z.number(),
  quantity: z.number(),
})

export type UpdateOrderLineQuantityParams = z.infer<typeof UpdateOrderLineQuantityParams>

// DeleteOrderLine - Parameters
export const DeleteOrderLineParams = z.object({
  id: z.number(),
})

export type DeleteOrderLineParams = z.infer<typeof DeleteOrderLineParams>

// DeleteOrderLines - Parameters
export const DeleteOrderLinesParams = z.object({
  orderId: z.number(),
})

export type DeleteOrderLinesParams = z.infer<typeof DeleteOrderLinesParams>

// GetOrderLineTotal - Parameters
export const GetOrderLineTotalParams = z.object({
  orderId: z.number(),
})

export type GetOrderLineTotalParams = z.infer<typeof GetOrderLineTotalParams>

// GetProductSalesStats - Parameters
export const GetProductSalesStatsParams = z.object({
  id: z.number(),
})

export type GetProductSalesStatsParams = z.infer<typeof GetProductSalesStatsParams>

// GetTopSellingProducts - Parameters
export const GetTopSellingProductsParams = z.object({
  limit: z.number(),
})

export type GetTopSellingProductsParams = z.infer<typeof GetTopSellingProductsParams>

// GetOrdersByProductIds - Parameters
export const GetOrdersByProductIdsParams = z.object({
  productIds: z.array(z.number()),
})

export type GetOrdersByProductIdsParams = z.infer<typeof GetOrdersByProductIdsParams>
