// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { z } from "zod"

// GetProduct - Result
export const GetProductResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetProductResult = z.infer<typeof GetProductResult>

// GetProductBySku - Result
export const GetProductBySkuResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetProductBySkuResult = z.infer<typeof GetProductBySkuResult>

// ListProducts - Result
export const ListProductsResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListProductsResult = z.infer<typeof ListProductsResult>

// ListActiveProducts - Result
export const ListActiveProductsResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListActiveProductsResult = z.infer<typeof ListActiveProductsResult>

// ListProductsByCategory - Result
export const ListProductsByCategoryResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListProductsByCategoryResult = z.infer<typeof ListProductsByCategoryResult>

// ListProductsPaginated - Result
export const ListProductsPaginatedResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListProductsPaginatedResult = z.infer<typeof ListProductsPaginatedResult>

// ListProductsCursor - Result
export const ListProductsCursorResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListProductsCursorResult = z.infer<typeof ListProductsCursorResult>

// SearchProducts - Result
export const SearchProductsResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  category: z.string().nullable(),
})

export type SearchProductsResult = z.infer<typeof SearchProductsResult>

// SearchProductsRanked - Result
export const SearchProductsRankedResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  category: z.string().nullable(),
  rank: z.number(),
})

export type SearchProductsRankedResult = z.infer<typeof SearchProductsRankedResult>

// SearchProductsWithHighlight - Result
export const SearchProductsWithHighlightResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  highlighted_description: z.unknown(),
  price_cents: z.number(),
  category: z.string().nullable(),
})

export type SearchProductsWithHighlightResult = z.infer<typeof SearchProductsWithHighlightResult>

// SearchProductsWebStyle - Result
export const SearchProductsWebStyleResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  category: z.string().nullable(),
})

export type SearchProductsWebStyleResult = z.infer<typeof SearchProductsWebStyleResult>

// CreateProduct - Result
export const CreateProductResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type CreateProductResult = z.infer<typeof CreateProductResult>

// UpdateProduct - Result
export const UpdateProductResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type UpdateProductResult = z.infer<typeof UpdateProductResult>

// GetProductsByIds - Result
export const GetProductsByIdsResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetProductsByIdsResult = z.infer<typeof GetProductsByIdsResult>

// CountProductsByCategory - Result
export const CountProductsByCategoryResult = z.object({
  category: z.string().nullable(),
  product_count: z.coerce.bigint(),
})

export type CountProductsByCategoryResult = z.infer<typeof CountProductsByCategoryResult>

// GetLowStockProducts - Result
export const GetLowStockProductsResult = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  stock_quantity: z.number(),
  category: z.string().nullable(),
})

export type GetLowStockProductsResult = z.infer<typeof GetLowStockProductsResult>
