// Generated by sqlc v1.31.1, plugin: sqlc-effect dev
import { z } from "zod"

// GetProduct - Row
export const GetProductRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetProductRow = z.infer<typeof GetProductRow>

// GetProduct - Result
export const GetProductResult = GetProductRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  stock_quantity: row.stock_quantity,
  is_active: row.is_active,
  category: row.category,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type GetProductResult = z.infer<typeof GetProductResult>

// GetProductBySku - Row
export const GetProductBySkuRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetProductBySkuRow = z.infer<typeof GetProductBySkuRow>

// GetProductBySku - Result
export const GetProductBySkuResult = GetProductBySkuRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  stock_quantity: row.stock_quantity,
  is_active: row.is_active,
  category: row.category,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type GetProductBySkuResult = z.infer<typeof GetProductBySkuResult>

// ListProducts - Row
export const ListProductsRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListProductsRow = z.infer<typeof ListProductsRow>

// ListProducts - Result
export const ListProductsResult = ListProductsRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  stock_quantity: row.stock_quantity,
  is_active: row.is_active,
  category: row.category,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListProductsResult = z.infer<typeof ListProductsResult>

// ListActiveProducts - Row
export const ListActiveProductsRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListActiveProductsRow = z.infer<typeof ListActiveProductsRow>

// ListActiveProducts - Result
export const ListActiveProductsResult = ListActiveProductsRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  stock_quantity: row.stock_quantity,
  is_active: row.is_active,
  category: row.category,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListActiveProductsResult = z.infer<typeof ListActiveProductsResult>

// ListProductsByCategory - Row
export const ListProductsByCategoryRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListProductsByCategoryRow = z.infer<typeof ListProductsByCategoryRow>

// ListProductsByCategory - Result
export const ListProductsByCategoryResult = ListProductsByCategoryRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  stock_quantity: row.stock_quantity,
  is_active: row.is_active,
  category: row.category,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListProductsByCategoryResult = z.infer<typeof ListProductsByCategoryResult>

// ListProductsPaginated - Row
export const ListProductsPaginatedRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListProductsPaginatedRow = z.infer<typeof ListProductsPaginatedRow>

// ListProductsPaginated - Result
export const ListProductsPaginatedResult = ListProductsPaginatedRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  stock_quantity: row.stock_quantity,
  is_active: row.is_active,
  category: row.category,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListProductsPaginatedResult = z.infer<typeof ListProductsPaginatedResult>

// ListProductsCursor - Row
export const ListProductsCursorRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type ListProductsCursorRow = z.infer<typeof ListProductsCursorRow>

// ListProductsCursor - Result
export const ListProductsCursorResult = ListProductsCursorRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  stock_quantity: row.stock_quantity,
  is_active: row.is_active,
  category: row.category,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type ListProductsCursorResult = z.infer<typeof ListProductsCursorResult>

// SearchProducts - Row
export const SearchProductsRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  category: z.string().nullable(),
})

export type SearchProductsRow = z.infer<typeof SearchProductsRow>

// SearchProducts - Result
export const SearchProductsResult = SearchProductsRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  stock_quantity: row.stock_quantity,
  category: row.category,
}))

export type SearchProductsResult = z.infer<typeof SearchProductsResult>

// SearchProductsRanked - Row
export const SearchProductsRankedRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  category: z.string().nullable(),
  rank: z.number(),
})

export type SearchProductsRankedRow = z.infer<typeof SearchProductsRankedRow>

// SearchProductsRanked - Result
export const SearchProductsRankedResult = SearchProductsRankedRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  stock_quantity: row.stock_quantity,
  category: row.category,
  rank: row.rank,
}))

export type SearchProductsRankedResult = z.infer<typeof SearchProductsRankedResult>

// SearchProductsWithHighlight - Row
export const SearchProductsWithHighlightRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  highlighted_description: z.unknown(),
  price_cents: z.number(),
  category: z.string().nullable(),
})

export type SearchProductsWithHighlightRow = z.infer<typeof SearchProductsWithHighlightRow>

// SearchProductsWithHighlight - Result
export const SearchProductsWithHighlightResult = SearchProductsWithHighlightRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  highlighted_description: row.highlighted_description,
  price_cents: row.price_cents,
  category: row.category,
}))

export type SearchProductsWithHighlightResult = z.infer<typeof SearchProductsWithHighlightResult>

// SearchProductsWebStyle - Row
export const SearchProductsWebStyleRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  category: z.string().nullable(),
})

export type SearchProductsWebStyleRow = z.infer<typeof SearchProductsWebStyleRow>

// SearchProductsWebStyle - Result
export const SearchProductsWebStyleResult = SearchProductsWebStyleRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  category: row.category,
}))

export type SearchProductsWebStyleResult = z.infer<typeof SearchProductsWebStyleResult>

// CreateProduct - Row
export const CreateProductRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type CreateProductRow = z.infer<typeof CreateProductRow>

// CreateProduct - Result
export const CreateProductResult = CreateProductRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  stock_quantity: row.stock_quantity,
  is_active: row.is_active,
  category: row.category,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type CreateProductResult = z.infer<typeof CreateProductResult>

// UpdateProduct - Row
export const UpdateProductRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type UpdateProductRow = z.infer<typeof UpdateProductRow>

// UpdateProduct - Result
export const UpdateProductResult = UpdateProductRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  stock_quantity: row.stock_quantity,
  is_active: row.is_active,
  category: row.category,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type UpdateProductResult = z.infer<typeof UpdateProductResult>

// GetProductsByIds - Row
export const GetProductsByIdsRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  price_cents: z.number(),
  stock_quantity: z.number(),
  is_active: z.boolean(),
  category: z.string().nullable(),
  created_at: z.coerce.date(),
  updated_at: z.coerce.date(),
})

export type GetProductsByIdsRow = z.infer<typeof GetProductsByIdsRow>

// GetProductsByIds - Result
export const GetProductsByIdsResult = GetProductsByIdsRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  description: row.description,
  price_cents: row.price_cents,
  stock_quantity: row.stock_quantity,
  is_active: row.is_active,
  category: row.category,
  created_at: row.created_at,
  updated_at: row.updated_at,
}))

export type GetProductsByIdsResult = z.infer<typeof GetProductsByIdsResult>

// CountProductsByCategory - Row
export const CountProductsByCategoryRow = z.object({
  category: z.string().nullable(),
  product_count: z.coerce.bigint(),
})

export type CountProductsByCategoryRow = z.infer<typeof CountProductsByCategoryRow>

// CountProductsByCategory - Result
export const CountProductsByCategoryResult = CountProductsByCategoryRow.transform((row) => ({
  category: row.category,
  product_count: row.product_count,
}))

export type CountProductsByCategoryResult = z.infer<typeof CountProductsByCategoryResult>

// GetLowStockProducts - Row
export const GetLowStockProductsRow = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  stock_quantity: z.number(),
  category: z.string().nullable(),
})

export type GetLowStockProductsRow = z.infer<typeof GetLowStockProductsRow>

// GetLowStockProducts - Result
export const GetLowStockProductsResult = GetLowStockProductsRow.transform((row) => ({
  id: row.id,
  sku: row.sku,
  name: row.name,
  stock_quantity: row.stock_quantity,
  category: row.category,
}))

export type GetLowStockProductsResult = z.infer<typeof GetLowStockProductsResult>
