// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { z } from "zod"

// GetProduct - Parameters
export const GetProductParams = z.object({
  id: z.number(),
})

export type GetProductParams = z.infer<typeof GetProductParams>

// GetProductBySku - Parameters
export const GetProductBySkuParams = z.object({
  sku: z.string(),
})

export type GetProductBySkuParams = z.infer<typeof GetProductBySkuParams>

// ListProductsByCategory - Parameters
export const ListProductsByCategoryParams = z.object({
  category: z.string().optional(),
})

export type ListProductsByCategoryParams = z.infer<typeof ListProductsByCategoryParams>

// ListProductsPaginated - Parameters
export const ListProductsPaginatedParams = z.object({
  limit: z.number(),
  offset: z.number(),
})

export type ListProductsPaginatedParams = z.infer<typeof ListProductsPaginatedParams>

// ListProductsCursor - Parameters
export const ListProductsCursorParams = z.object({
  id: z.number(),
  limit: z.number(),
})

export type ListProductsCursorParams = z.infer<typeof ListProductsCursorParams>

// SearchProducts - Parameters
export const SearchProductsParams = z.object({
  plaintoTsquery: z.string(),
})

export type SearchProductsParams = z.infer<typeof SearchProductsParams>

// SearchProductsRanked - Parameters
export const SearchProductsRankedParams = z.object({
  plaintoTsquery: z.string(),
  limit: z.number(),
  offset: z.number(),
})

export type SearchProductsRankedParams = z.infer<typeof SearchProductsRankedParams>

// SearchProductsWithHighlight - Parameters
export const SearchProductsWithHighlightParams = z.object({
  plaintoTsquery: z.string(),
})

export type SearchProductsWithHighlightParams = z.infer<typeof SearchProductsWithHighlightParams>

// SearchProductsWebStyle - Parameters
export const SearchProductsWebStyleParams = z.object({
  websearchToTsquery: z.string(),
})

export type SearchProductsWebStyleParams = z.infer<typeof SearchProductsWebStyleParams>

// CreateProduct - Parameters
export const CreateProductParams = z.object({
  sku: z.string(),
  name: z.string(),
  description: z.string().optional(),
  priceCents: z.number(),
  stockQuantity: z.number(),
  isActive: z.boolean(),
  category: z.string().optional(),
})

export type CreateProductParams = z.infer<typeof CreateProductParams>

// UpdateProduct - Parameters
export const UpdateProductParams = z.object({
  id: z.number(),
  sku: z.string(),
  name: z.string(),
  description: z.string().optional(),
  priceCents: z.number(),
  stockQuantity: z.number(),
  isActive: z.boolean(),
  category: z.string().optional(),
})

export type UpdateProductParams = z.infer<typeof UpdateProductParams>

// UpdateProductStock - Parameters
export const UpdateProductStockParams = z.object({
  id: z.number(),
  stockQuantity: z.number(),
})

export type UpdateProductStockParams = z.infer<typeof UpdateProductStockParams>

// DeactivateProduct - Parameters
export const DeactivateProductParams = z.object({
  id: z.number(),
})

export type DeactivateProductParams = z.infer<typeof DeactivateProductParams>

// DeleteProduct - Parameters
export const DeleteProductParams = z.object({
  id: z.number(),
})

export type DeleteProductParams = z.infer<typeof DeleteProductParams>

// GetProductsByIds - Parameters
export const GetProductsByIdsParams = z.object({
  ids: z.array(z.number()),
})

export type GetProductsByIdsParams = z.infer<typeof GetProductsByIdsParams>

// GetLowStockProducts - Parameters
export const GetLowStockProductsParams = z.object({
  stockQuantity: z.number(),
})

export type GetLowStockProductsParams = z.infer<typeof GetLowStockProductsParams>
