// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import type { SqlClient, QueryResult } from "./models.js"

import type { GetProductParams } from "./productsRequests.js"
import { GetProductParams as GetProductParamsSchema } from "./productsRequests.js"
import type { GetProductResult } from "./productsResponses.js"
import { GetProductResult as GetProductResultSchema } from "./productsResponses.js"

import type { GetProductBySkuParams } from "./productsRequests.js"
import { GetProductBySkuParams as GetProductBySkuParamsSchema } from "./productsRequests.js"
import type { GetProductBySkuResult } from "./productsResponses.js"
import { GetProductBySkuResult as GetProductBySkuResultSchema } from "./productsResponses.js"
import type { ListProductsResult } from "./productsResponses.js"
import { ListProductsResult as ListProductsResultSchema } from "./productsResponses.js"
import type { ListActiveProductsResult } from "./productsResponses.js"
import { ListActiveProductsResult as ListActiveProductsResultSchema } from "./productsResponses.js"

import type { ListProductsByCategoryParams } from "./productsRequests.js"
import { ListProductsByCategoryParams as ListProductsByCategoryParamsSchema } from "./productsRequests.js"
import type { ListProductsByCategoryResult } from "./productsResponses.js"
import { ListProductsByCategoryResult as ListProductsByCategoryResultSchema } from "./productsResponses.js"

import type { ListProductsPaginatedParams } from "./productsRequests.js"
import { ListProductsPaginatedParams as ListProductsPaginatedParamsSchema } from "./productsRequests.js"
import type { ListProductsPaginatedResult } from "./productsResponses.js"
import { ListProductsPaginatedResult as ListProductsPaginatedResultSchema } from "./productsResponses.js"

import type { ListProductsCursorParams } from "./productsRequests.js"
import { ListProductsCursorParams as ListProductsCursorParamsSchema } from "./productsRequests.js"
import type { ListProductsCursorResult } from "./productsResponses.js"
import { ListProductsCursorResult as ListProductsCursorResultSchema } from "./productsResponses.js"

import type { SearchProductsParams } from "./productsRequests.js"
import { SearchProductsParams as SearchProductsParamsSchema } from "./productsRequests.js"
import type { SearchProductsResult } from "./productsResponses.js"
import { SearchProductsResult as SearchProductsResultSchema } from "./productsResponses.js"

import type { SearchProductsRankedParams } from "./productsRequests.js"
import { SearchProductsRankedParams as SearchProductsRankedParamsSchema } from "./productsRequests.js"
import type { SearchProductsRankedResult } from "./productsResponses.js"
import { SearchProductsRankedResult as SearchProductsRankedResultSchema } from "./productsResponses.js"

import type { SearchProductsWithHighlightParams } from "./productsRequests.js"
import { SearchProductsWithHighlightParams as SearchProductsWithHighlightParamsSchema } from "./productsRequests.js"
import type { SearchProductsWithHighlightResult } from "./productsResponses.js"
import { SearchProductsWithHighlightResult as SearchProductsWithHighlightResultSchema } from "./productsResponses.js"

import type { SearchProductsWebStyleParams } from "./productsRequests.js"
import { SearchProductsWebStyleParams as SearchProductsWebStyleParamsSchema } from "./productsRequests.js"
import type { SearchProductsWebStyleResult } from "./productsResponses.js"
import { SearchProductsWebStyleResult as SearchProductsWebStyleResultSchema } from "./productsResponses.js"

import type { CreateProductParams } from "./productsRequests.js"
import { CreateProductParams as CreateProductParamsSchema } from "./productsRequests.js"
import type { CreateProductResult } from "./productsResponses.js"
import { CreateProductResult as CreateProductResultSchema } from "./productsResponses.js"

import type { UpdateProductParams } from "./productsRequests.js"
import { UpdateProductParams as UpdateProductParamsSchema } from "./productsRequests.js"
import type { UpdateProductResult } from "./productsResponses.js"
import { UpdateProductResult as UpdateProductResultSchema } from "./productsResponses.js"

import type { UpdateProductStockParams } from "./productsRequests.js"
import { UpdateProductStockParams as UpdateProductStockParamsSchema } from "./productsRequests.js"

import type { DeactivateProductParams } from "./productsRequests.js"
import { DeactivateProductParams as DeactivateProductParamsSchema } from "./productsRequests.js"

import type { DeleteProductParams } from "./productsRequests.js"
import { DeleteProductParams as DeleteProductParamsSchema } from "./productsRequests.js"

import type { GetProductsByIdsParams } from "./productsRequests.js"
import { GetProductsByIdsParams as GetProductsByIdsParamsSchema } from "./productsRequests.js"
import type { GetProductsByIdsResult } from "./productsResponses.js"
import { GetProductsByIdsResult as GetProductsByIdsResultSchema } from "./productsResponses.js"
import type { CountProductsByCategoryResult } from "./productsResponses.js"
import { CountProductsByCategoryResult as CountProductsByCategoryResultSchema } from "./productsResponses.js"

import type { GetLowStockProductsParams } from "./productsRequests.js"
import { GetLowStockProductsParams as GetLowStockProductsParamsSchema } from "./productsRequests.js"
import type { GetLowStockProductsResult } from "./productsResponses.js"
import { GetLowStockProductsResult as GetLowStockProductsResultSchema } from "./productsResponses.js"

// GetProduct
// SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
// FROM products
// WHERE id = $1
export async function getProduct(client: SqlClient, params: GetProductParams): Promise<QueryResult<GetProductResult | null>> {
  const inputParsed = GetProductParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE id = $1`,
    [inputParsed.data.id]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = GetProductResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetProductBySku
// SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
// FROM products
// WHERE sku = $1
export async function getProductBySku(client: SqlClient, params: GetProductBySkuParams): Promise<QueryResult<GetProductBySkuResult | null>> {
  const inputParsed = GetProductBySkuParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE sku = $1`,
    [inputParsed.data.sku]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = GetProductBySkuResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListProducts
// SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
// FROM products
// ORDER BY name
export async function listProducts(client: SqlClient): Promise<QueryResult<ListProductsResult[]>> {
  const result = await client.query(
    `SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
ORDER BY name`,
    []
  )

  const outputParsed = ListProductsResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListActiveProducts
// SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
// FROM products
// WHERE is_active = TRUE
// ORDER BY name
export async function listActiveProducts(client: SqlClient): Promise<QueryResult<ListActiveProductsResult[]>> {
  const result = await client.query(
    `SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE is_active = TRUE
ORDER BY name`,
    []
  )

  const outputParsed = ListActiveProductsResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListProductsByCategory
// SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
// FROM products
// WHERE category = $1 AND is_active = TRUE
// ORDER BY name
export async function listProductsByCategory(client: SqlClient, params: ListProductsByCategoryParams): Promise<QueryResult<ListProductsByCategoryResult[]>> {
  const inputParsed = ListProductsByCategoryParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE category = $1 AND is_active = TRUE
ORDER BY name`,
    [inputParsed.data.category]
  )

  const outputParsed = ListProductsByCategoryResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListProductsPaginated
// SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
// FROM products
// WHERE is_active = TRUE
// ORDER BY created_at DESC
// LIMIT $1 OFFSET $2
export async function listProductsPaginated(client: SqlClient, params: ListProductsPaginatedParams): Promise<QueryResult<ListProductsPaginatedResult[]>> {
  const inputParsed = ListProductsPaginatedParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE is_active = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2`,
    [inputParsed.data.limit, inputParsed.data.offset]
  )

  const outputParsed = ListProductsPaginatedResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// ListProductsCursor
// SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
// FROM products
// WHERE is_active = TRUE AND id > $1
// ORDER BY id
// LIMIT $2
export async function listProductsCursor(client: SqlClient, params: ListProductsCursorParams): Promise<QueryResult<ListProductsCursorResult[]>> {
  const inputParsed = ListProductsCursorParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE is_active = TRUE AND id > $1
ORDER BY id
LIMIT $2`,
    [inputParsed.data.id, inputParsed.data.limit]
  )

  const outputParsed = ListProductsCursorResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// SearchProducts
// SELECT id, sku, name, description, price_cents, stock_quantity, category
// FROM products
// WHERE search_vector @@ plainto_tsquery('english', $1)
//   AND is_active = TRUE
// ORDER BY name
export async function searchProducts(client: SqlClient, params: SearchProductsParams): Promise<QueryResult<SearchProductsResult[]>> {
  const inputParsed = SearchProductsParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, sku, name, description, price_cents, stock_quantity, category
FROM products
WHERE search_vector @@ plainto_tsquery('english', $1)
  AND is_active = TRUE
ORDER BY name`,
    [inputParsed.data.plaintoTsquery]
  )

  const outputParsed = SearchProductsResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// SearchProductsRanked
// SELECT id, sku, name, description, price_cents, stock_quantity, category,
//        ts_rank(search_vector, query) AS rank
// FROM products, plainto_tsquery('english', $1) query
// WHERE search_vector @@ query
//   AND is_active = TRUE
// ORDER BY rank DESC
// LIMIT $2 OFFSET $3
export async function searchProductsRanked(client: SqlClient, params: SearchProductsRankedParams): Promise<QueryResult<SearchProductsRankedResult[]>> {
  const inputParsed = SearchProductsRankedParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, sku, name, description, price_cents, stock_quantity, category,
       ts_rank(search_vector, query) AS rank
FROM products, plainto_tsquery('english', $1) query
WHERE search_vector @@ query
  AND is_active = TRUE
ORDER BY rank DESC
LIMIT $2 OFFSET $3`,
    [inputParsed.data.plaintoTsquery, inputParsed.data.limit, inputParsed.data.offset]
  )

  const outputParsed = SearchProductsRankedResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// SearchProductsWithHighlight
// SELECT id, sku, name,
//        ts_headline('english', COALESCE(description, ''), plainto_tsquery('english', $1)) AS highlighted_description,
//        price_cents, category
// FROM products
// WHERE search_vector @@ plainto_tsquery('english', $1)
//   AND is_active = TRUE
export async function searchProductsWithHighlight(client: SqlClient, params: SearchProductsWithHighlightParams): Promise<QueryResult<SearchProductsWithHighlightResult[]>> {
  const inputParsed = SearchProductsWithHighlightParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, sku, name,
       ts_headline('english', COALESCE(description, ''), plainto_tsquery('english', $1)) AS highlighted_description,
       price_cents, category
FROM products
WHERE search_vector @@ plainto_tsquery('english', $1)
  AND is_active = TRUE`,
    [inputParsed.data.plaintoTsquery]
  )

  const outputParsed = SearchProductsWithHighlightResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// SearchProductsWebStyle
// SELECT id, sku, name, description, price_cents, category
// FROM products
// WHERE search_vector @@ websearch_to_tsquery('english', $1)
//   AND is_active = TRUE
// ORDER BY name
export async function searchProductsWebStyle(client: SqlClient, params: SearchProductsWebStyleParams): Promise<QueryResult<SearchProductsWebStyleResult[]>> {
  const inputParsed = SearchProductsWebStyleParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, sku, name, description, price_cents, category
FROM products
WHERE search_vector @@ websearch_to_tsquery('english', $1)
  AND is_active = TRUE
ORDER BY name`,
    [inputParsed.data.websearchToTsquery]
  )

  const outputParsed = SearchProductsWebStyleResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// CreateProduct
// INSERT INTO products (sku, name, description, price_cents, stock_quantity, is_active, category)
// VALUES ($1, $2, $3, $4, $5, $6, $7)
// RETURNING id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
export async function createProduct(client: SqlClient, params: CreateProductParams): Promise<QueryResult<CreateProductResult | null>> {
  const inputParsed = CreateProductParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `INSERT INTO products (sku, name, description, price_cents, stock_quantity, is_active, category)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at`,
    [inputParsed.data.sku, inputParsed.data.name, inputParsed.data.description, inputParsed.data.priceCents, inputParsed.data.stockQuantity, inputParsed.data.isActive, inputParsed.data.category]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = CreateProductResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// UpdateProduct
// UPDATE products
// SET sku = $2, name = $3, description = $4, price_cents = $5, stock_quantity = $6, is_active = $7, category = $8, updated_at = NOW()
// WHERE id = $1
// RETURNING id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
export async function updateProduct(client: SqlClient, params: UpdateProductParams): Promise<QueryResult<UpdateProductResult | null>> {
  const inputParsed = UpdateProductParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `UPDATE products
SET sku = $2, name = $3, description = $4, price_cents = $5, stock_quantity = $6, is_active = $7, category = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at`,
    [inputParsed.data.id, inputParsed.data.sku, inputParsed.data.name, inputParsed.data.description, inputParsed.data.priceCents, inputParsed.data.stockQuantity, inputParsed.data.isActive, inputParsed.data.category]
  )

  if (result.rows.length === 0) {
    return { success: true, data: null }
  }

  const outputParsed = UpdateProductResultSchema.safeParse(result.rows[0])
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// UpdateProductStock
// UPDATE products
// SET stock_quantity = stock_quantity + $2, updated_at = NOW()
// WHERE id = $1
export async function updateProductStock(client: SqlClient, params: UpdateProductStockParams): Promise<QueryResult<number>> {
  const inputParsed = UpdateProductStockParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `UPDATE products
SET stock_quantity = stock_quantity + $2, updated_at = NOW()
WHERE id = $1`,
    [inputParsed.data.id, inputParsed.data.stockQuantity]
  )

  return { success: true, data: result.rowCount || 0 }
}

// DeactivateProduct
// UPDATE products
// SET is_active = FALSE, updated_at = NOW()
// WHERE id = $1
export async function deactivateProduct(client: SqlClient, params: DeactivateProductParams): Promise<QueryResult<void>> {
  const inputParsed = DeactivateProductParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  await client.query(
    `UPDATE products
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1`,
    [inputParsed.data.id]
  )

  return { success: true, data: undefined }
}

// DeleteProduct
// DELETE FROM products
// WHERE id = $1
export async function deleteProduct(client: SqlClient, params: DeleteProductParams): Promise<QueryResult<void>> {
  const inputParsed = DeleteProductParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  await client.query(
    `DELETE FROM products
WHERE id = $1`,
    [inputParsed.data.id]
  )

  return { success: true, data: undefined }
}

// GetProductsByIds
// SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
// FROM products
// WHERE id = ANY($1::int[])
export async function getProductsByIds(client: SqlClient, params: GetProductsByIdsParams): Promise<QueryResult<GetProductsByIdsResult[]>> {
  const inputParsed = GetProductsByIdsParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE id = ANY($1::int[])`,
    [inputParsed.data.ids]
  )

  const outputParsed = GetProductsByIdsResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// CountProductsByCategory
// SELECT category, COUNT(*) AS product_count
// FROM products
// WHERE is_active = TRUE
// GROUP BY category
// ORDER BY product_count DESC
export async function countProductsByCategory(client: SqlClient): Promise<QueryResult<CountProductsByCategoryResult[]>> {
  const result = await client.query(
    `SELECT category, COUNT(*) AS product_count
FROM products
WHERE is_active = TRUE
GROUP BY category
ORDER BY product_count DESC`,
    []
  )

  const outputParsed = CountProductsByCategoryResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}

// GetLowStockProducts
// SELECT id, sku, name, stock_quantity, category
// FROM products
// WHERE stock_quantity < $1 AND is_active = TRUE
// ORDER BY stock_quantity
export async function getLowStockProducts(client: SqlClient, params: GetLowStockProductsParams): Promise<QueryResult<GetLowStockProductsResult[]>> {
  const inputParsed = GetLowStockProductsParamsSchema.safeParse(params)
  if (!inputParsed.success) {
    return { success: false, error: inputParsed.error, phase: "input" }
  }

  const result = await client.query(
    `SELECT id, sku, name, stock_quantity, category
FROM products
WHERE stock_quantity < $1 AND is_active = TRUE
ORDER BY stock_quantity`,
    [inputParsed.data.stockQuantity]
  )

  const outputParsed = GetLowStockProductsResultSchema.array().safeParse(result.rows)
  if (!outputParsed.success) {
    return { success: false, error: outputParsed.error, phase: "output" }
  }

  return { success: true, data: outputParsed.data }
}
