// Generated by sqlc v1.30.0, plugin: sqlc-effect v0.1.0
import { ServiceMap, Effect, Layer, Schema, Option } from "effect"
import { SqlClient, SqlError, SqlSchema } from "effect/unstable/sql"

// GetSMSProducts - Result Schema
export const GetSMSProductsResult = Schema.Struct({
  id: Schema.String,
  name: Schema.String
})

export type GetSMSProductsResult = typeof GetSMSProductsResult.Type

// GetByIds - Parameters Schema
export const GetByIdsParams = Schema.Struct({
  ids: Schema.String
})

export type GetByIdsParams = typeof GetByIdsParams.Type

// GetByIds - Result Schema
export const GetByIdsResult = Schema.Struct({
  id: Schema.String,
  name: Schema.String
})

export type GetByIdsResult = typeof GetByIdsResult.Type

// GetStory - Parameters Schema
export const GetStoryParams = Schema.Struct({
  id: Schema.String
})

export type GetStoryParams = typeof GetStoryParams.Type

// GetStory - Result Schema
export const GetStoryResult = Schema.Struct({
  id: Schema.String,
  name: Schema.String
})

export type GetStoryResult = typeof GetStoryResult.Type

// AddStory - Parameters Schema
export const AddStoryParams = Schema.Struct({
  id: Schema.String,
  name: Schema.String
})

export type AddStoryParams = typeof AddStoryParams.Type

// GetStories - Result Schema
export const GetStoriesResult = Schema.Struct({
  id: Schema.String,
  name: Schema.String,
  sender: Schema.String,
  sms_episodes_id: Schema.String,
  story_id: Schema.String,
  send_date: Schema.Date,
  singular_content: Schema.String
})

export type GetStoriesResult = typeof GetStoriesResult.Type


// Repository interface for queries.sql
export interface QueriesRepositoryShape {
  readonly getSMSProducts: () => Effect.Effect<
    GetSMSProductsResult[],
    SqlError.SqlError | Schema.SchemaError,
    SqlClient.SqlClient
  >
  readonly getByIds: (params: GetByIdsParams) => Effect.Effect<
    GetByIdsResult[],
    SqlError.SqlError | Schema.SchemaError,
    SqlClient.SqlClient
  >
  readonly getStory: (params: GetStoryParams) => Effect.Effect<
    Option.Option<GetStoryResult>,
    SqlError.SqlError | Schema.SchemaError,
    SqlClient.SqlClient
  >
  readonly addStory: (params: AddStoryParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError,
    SqlClient.SqlClient
  >
  readonly getStories: () => Effect.Effect<
    GetStoriesResult[],
    SqlError.SqlError | Schema.SchemaError,
    SqlClient.SqlClient
  >
}

// Service Tag
export class QueriesRepository extends ServiceMap.Service<QueriesRepository, QueriesRepositoryShape>()("QueriesRepository") { }

// Implementation
const queriesRepositoryImpl = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient

  // GetSMSProducts
  const getSMSProducts = SqlSchema.findAll({
    Request: Schema.Void,
    Result: GetSMSProductsResult,
    execute: () => sql.unsafe(`select id, name from sms_stories`)
  })
  // GetByIds
  const getByIds = SqlSchema.findAll({
    Request: GetByIdsParams,
    Result: GetByIdsResult,
    execute: (params) => sql.unsafe(`select id, name from sms_stories where id in ($1)`, [params.ids])
  })
  // GetStory
  const getStory = SqlSchema.findOneOption({
    Request: GetStoryParams,
    Result: GetStoryResult,
    execute: (params) => sql.unsafe(`select id, name from sms_stories where id = $1`, [params.id])
  })
  // AddStory
  const addStory = SqlSchema.void({
    Request: AddStoryParams,
    execute: (params) => sql.unsafe(`insert into sms_stories (id, name) values ($1,$2)`, [params.id, params.name])
  })
  // GetStories
  const getStories = SqlSchema.findAll({
    Request: Schema.Void,
    Result: GetStoriesResult,
    execute: () => sql.unsafe(`SELECT sms_stories.id, name, sender, sms_episodes.id AS sms_episodes_id, story_id, send_date, singular_content FROM sms_stories
inner join sms_episodes on sms_stories.id = sms_episodes.story_id`)
  })

  return {
    getSMSProducts,
    getByIds,
    getStory,
    addStory,
    getStories,
  } satisfies QueriesRepositoryShape
})

// Live Layer
export const queriesRepositoryLive = Layer.effect(QueriesRepository, queriesRepositoryImpl)
