// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { Schema } from "effect"

// EchoBigInts - Result Schema
export const EchoBigIntsResult = Schema.Struct({
  value: Schema.BigInt,
  values: Schema.Array(Schema.BigInt),
})

export type EchoBigIntsResult = typeof EchoBigIntsResult.Type
