// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { EchoBigIntsParams } from "./BinaryTypesRepositoryRequest.js"
import { EchoBigIntsResult } from "./BinaryTypesRepositoryResponse.js"
import { Context, Effect, Layer, Schema } from "effect"
import { SqlClient, SqlSchema } from "effect/sql"

// Implementation
const binaryTypesRepositoryMake = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient

  // EchoBigInts
  // SELECT
  //     $1::bigint AS value,
  //     ARRAY[$1::bigint]::bigint[] AS values
  const echoBigInts = SqlSchema.findOneOption({
    Request: EchoBigIntsParams,
    Result: EchoBigIntsResult,
    execute: (params) => sql`SELECT
    ${params.value}::bigint AS value,
    ARRAY[${params.value}::bigint]::bigint[] AS values`
  })

  return {
    echoBigInts: Effect.fn("BinaryTypesRepository.echoBigInts")(echoBigInts),
  } as const
})

// Service Tag
export class BinaryTypesRepository extends Context.Service<BinaryTypesRepository>()("BinaryTypesRepository", { make: binaryTypesRepositoryMake }) {
  static readonly layer = Layer.effect(this, this.make)
}

export type BinaryTypesRepositoryService = BinaryTypesRepository["Service"]

// Live Layer
export const binaryTypesRepositoryLive = BinaryTypesRepository.layer
