// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { Schema } from "effect"

// EchoBigInts - Parameters Schema
export const EchoBigIntsParams = Schema.Struct({
  value: Schema.BigInt,
})

export type EchoBigIntsParams = typeof EchoBigIntsParams.Type
