// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { CreateCustomerParams, DeleteCustomerParams, GetCustomerByEmailParams, GetCustomerParams, GetCustomersByIdsParams, ListCustomersPaginatedParams, SearchCustomersByNameParams, UpdateCustomerEmailParams, UpdateCustomerParams } from "./CustomersRepositoryRequest.js"
import { CountCustomersResult, CreateCustomerResult, GetCustomerByEmailResult, GetCustomerResult, GetCustomersByIdsResult, ListCustomersPaginatedResult, ListCustomersResult, SearchCustomersByNameResult, UpdateCustomerResult } from "./CustomersRepositoryResponse.js"
import { Effect, Layer, Option, Schema, ServiceMap } from "effect"
import { SqlClient, SqlError, SqlSchema } from "effect/unstable/sql"

// Repository interface for customers.sql
export interface CustomersRepositoryShape {
  readonly getCustomer: (params: GetCustomerParams) => Effect.Effect<
    Option.Option<GetCustomerResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getCustomerByEmail: (params: GetCustomerByEmailParams) => Effect.Effect<
    Option.Option<GetCustomerByEmailResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listCustomers: () => Effect.Effect<
    ListCustomersResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listCustomersPaginated: (params: ListCustomersPaginatedParams) => Effect.Effect<
    ListCustomersPaginatedResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly searchCustomersByName: (params: SearchCustomersByNameParams) => Effect.Effect<
    SearchCustomersByNameResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly createCustomer: (params: CreateCustomerParams) => Effect.Effect<
    Option.Option<CreateCustomerResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly updateCustomer: (params: UpdateCustomerParams) => Effect.Effect<
    Option.Option<UpdateCustomerResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly updateCustomerEmail: (params: UpdateCustomerEmailParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly deleteCustomer: (params: DeleteCustomerParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly countCustomers: () => Effect.Effect<
    Option.Option<CountCustomersResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getCustomersByIds: (params: GetCustomersByIdsParams) => Effect.Effect<
    GetCustomersByIdsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
}

// Service Tag
export class CustomersRepository extends ServiceMap.Service<CustomersRepository, CustomersRepositoryShape>()("CustomersRepository") { }

// Implementation
const customersRepositoryImpl = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient

  // GetCustomer
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // WHERE id = $1
  const getCustomer = SqlSchema.findOneOption({
    Request: GetCustomerParams,
    Result: GetCustomerResult,
    execute: (params) => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
WHERE id = ${params.id}`
  })

  // GetCustomerByEmail
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // WHERE email = $1
  const getCustomerByEmail = SqlSchema.findOneOption({
    Request: GetCustomerByEmailParams,
    Result: GetCustomerByEmailResult,
    execute: (params) => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
WHERE email = ${params.email}`
  })

  // ListCustomers
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // ORDER BY created_at DESC
  const listCustomers = SqlSchema.findAll({
    Request: Schema.Void,
    Result: ListCustomersResult,
    execute: () => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
ORDER BY created_at DESC`
  })

  // ListCustomersPaginated
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // ORDER BY created_at DESC
  // LIMIT $1 OFFSET $2
  const listCustomersPaginated = SqlSchema.findAll({
    Request: ListCustomersPaginatedParams,
    Result: ListCustomersPaginatedResult,
    execute: (params) => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
ORDER BY created_at DESC
LIMIT ${params.limit} OFFSET ${params.offset}`
  })

  // SearchCustomersByName
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // WHERE name ILIKE '%' || $1 || '%'
  // ORDER BY name
  const searchCustomersByName = SqlSchema.findAll({
    Request: SearchCustomersByNameParams,
    Result: SearchCustomersByNameResult,
    execute: (params) => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
WHERE name ILIKE '%' || ${params.arg1} || '%'
ORDER BY name`
  })

  // CreateCustomer
  // INSERT INTO customers (email, name, phone)
  // VALUES ($1, $2, $3)
  // RETURNING id, email, name, phone, created_at, updated_at
  const createCustomer = SqlSchema.findOneOption({
    Request: CreateCustomerParams,
    Result: CreateCustomerResult,
    execute: (params) => sql`INSERT INTO customers (email, name, phone)
VALUES (${params.email}, ${params.name}, ${params.phone})
RETURNING id, email, name, phone, created_at, updated_at`
  })

  // UpdateCustomer
  // UPDATE customers
  // SET email = $2, name = $3, phone = $4, updated_at = NOW()
  // WHERE id = $1
  // RETURNING id, email, name, phone, created_at, updated_at
  const updateCustomer = SqlSchema.findOneOption({
    Request: UpdateCustomerParams,
    Result: UpdateCustomerResult,
    execute: (params) => sql`UPDATE customers
SET email = ${params.email}, name = ${params.name}, phone = ${params.phone}, updated_at = NOW()
WHERE id = ${params.id}
RETURNING id, email, name, phone, created_at, updated_at`
  })

  // UpdateCustomerEmail
  // UPDATE customers
  // SET email = $2, updated_at = NOW()
  // WHERE id = $1
  const updateCustomerEmail = SqlSchema.void({
    Request: UpdateCustomerEmailParams,
    execute: (params) => sql`UPDATE customers
SET email = ${params.email}, updated_at = NOW()
WHERE id = ${params.id}`
  })

  // DeleteCustomer
  // DELETE FROM customers
  // WHERE id = $1
  const deleteCustomer = SqlSchema.void({
    Request: DeleteCustomerParams,
    execute: (params) => sql`DELETE FROM customers
WHERE id = ${params.id}`
  })

  // CountCustomers
  // SELECT COUNT(*) AS total
  // FROM customers
  const countCustomers = SqlSchema.findOneOption({
    Request: Schema.Void,
    Result: CountCustomersResult,
    execute: () => sql`SELECT COUNT(*) AS total
FROM customers`
  })

  // GetCustomersByIds
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // WHERE id = ANY($1::int[])
  const getCustomersByIds = SqlSchema.findAll({
    Request: GetCustomersByIdsParams,
    Result: GetCustomersByIdsResult,
    execute: (params) => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
WHERE id = ANY(${params.ids}::int[])`
  })

  return {
    getCustomer,
    getCustomerByEmail,
    listCustomers,
    listCustomersPaginated,
    searchCustomersByName,
    createCustomer,
    updateCustomer,
    updateCustomerEmail,
    deleteCustomer,
    countCustomers,
    getCustomersByIds,
  } satisfies CustomersRepositoryShape
})

// Live Layer
export const customersRepositoryLive = Layer.effect(CustomersRepository, customersRepositoryImpl)
