// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { CreateCustomerParams, DeleteCustomerParams, DeleteCustomerResultParams, GetCustomerByEmailParams, GetCustomerParams, GetCustomersByIdsParams, GetCustomersByIdsSliceParams, ListCustomersPaginatedParams, PatchCustomerParams, SearchCustomersByEmailDomainParams, SearchCustomersByNameParams, UpdateCustomerEmailParams, UpdateCustomerParams } from "./CustomersRepositoryRequest.js"
import { CountCustomersResult, CreateCustomerResult, GetCustomerByEmailResult, GetCustomerResult, GetCustomersByIdsResult, GetCustomersByIdsSliceResult, ListCustomersPaginatedResult, ListCustomersResult, PatchCustomerResult, SearchCustomersByEmailDomainResult, SearchCustomersByNameResult, UpdateCustomerResult } from "./CustomersRepositoryResponse.js"
import { execResult } from "./models.js"
import { Context, Effect, Layer, Schema } from "effect"
import { SqlClient, SqlSchema } from "effect/unstable/sql"

// Implementation
const customersRepositoryMake = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient

  // GetCustomer
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // WHERE id = $1
  const getCustomer = SqlSchema.findOneOption({
    Request: GetCustomerParams,
    Result: GetCustomerResult,
    execute: (params) => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
WHERE id = ${params.id}`
  })

  // GetCustomerByEmail
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // WHERE email = $1
  const getCustomerByEmail = SqlSchema.findOneOption({
    Request: GetCustomerByEmailParams,
    Result: GetCustomerByEmailResult,
    execute: (params) => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
WHERE email = ${params.email}`
  })

  // ListCustomers
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // ORDER BY created_at DESC
  const listCustomers = SqlSchema.findAll({
    Request: Schema.Void,
    Result: ListCustomersResult,
    execute: () => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
ORDER BY created_at DESC`
  })

  // ListCustomersPaginated
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // ORDER BY created_at DESC
  // LIMIT $1 OFFSET $2
  const listCustomersPaginated = SqlSchema.findAll({
    Request: ListCustomersPaginatedParams,
    Result: ListCustomersPaginatedResult,
    execute: (params) => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
ORDER BY created_at DESC
LIMIT ${params.limit} OFFSET ${params.offset}`
  })

  // SearchCustomersByName
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // WHERE name ILIKE '%' || $1 || '%'
  // ORDER BY name
  const searchCustomersByName = SqlSchema.findAll({
    Request: SearchCustomersByNameParams,
    Result: SearchCustomersByNameResult,
    execute: (params) => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
WHERE name ILIKE '%' || ${params.name} || '%'
ORDER BY name`
  })

  // SearchCustomersByEmailDomain
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // WHERE email ILIKE '%' || $1
  // ORDER BY email
  const searchCustomersByEmailDomain = SqlSchema.findAll({
    Request: SearchCustomersByEmailDomainParams,
    Result: SearchCustomersByEmailDomainResult,
    execute: (params) => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
WHERE email ILIKE '%' || ${params.domain}
ORDER BY email`
  })

  // CreateCustomer
  // INSERT INTO customers (email, name, phone)
  // VALUES ($1, $2, $3)
  // RETURNING id, email, name, phone, created_at, updated_at
  const createCustomer = SqlSchema.findOneOption({
    Request: CreateCustomerParams,
    Result: CreateCustomerResult,
    execute: (params) => sql`INSERT INTO customers (email, name, phone)
VALUES (${params.email}, ${params.name}, ${params.phone})
RETURNING id, email, name, phone, created_at, updated_at`
  })

  // UpdateCustomer
  // UPDATE customers
  // SET email = $2, name = $3, phone = $4, updated_at = NOW()
  // WHERE id = $1
  // RETURNING id, email, name, phone, created_at, updated_at
  const updateCustomer = SqlSchema.findOneOption({
    Request: UpdateCustomerParams,
    Result: UpdateCustomerResult,
    execute: (params) => sql`UPDATE customers
SET email = ${params.email}, name = ${params.name}, phone = ${params.phone}, updated_at = NOW()
WHERE id = ${params.id}
RETURNING id, email, name, phone, created_at, updated_at`
  })

  // PatchCustomer
  // UPDATE customers
  // SET
  //   email = COALESCE($1, email),
  //   name = COALESCE($2, name),
  //   phone = COALESCE($3, phone),
  //   updated_at = NOW()
  // WHERE id = $4
  // RETURNING id, email, name, phone, created_at, updated_at
  const patchCustomer = SqlSchema.findOneOption({
    Request: PatchCustomerParams,
    Result: PatchCustomerResult,
    execute: (params) => sql`UPDATE customers
SET
  email = COALESCE(${params.email}, email),
  name = COALESCE(${params.name}, name),
  phone = COALESCE(${params.phone}, phone),
  updated_at = NOW()
WHERE id = ${params.id}
RETURNING id, email, name, phone, created_at, updated_at`
  })

  // UpdateCustomerEmail
  // UPDATE customers
  // SET email = $2, updated_at = NOW()
  // WHERE id = $1
  const updateCustomerEmail = SqlSchema.void({
    Request: UpdateCustomerEmailParams,
    execute: (params) => sql`UPDATE customers
SET email = ${params.email}, updated_at = NOW()
WHERE id = ${params.id}`
  })

  // DeleteCustomer
  // DELETE FROM customers
  // WHERE id = $1
  const deleteCustomer = SqlSchema.void({
    Request: DeleteCustomerParams,
    execute: (params) => sql`DELETE FROM customers
WHERE id = ${params.id}`
  })

  // DeleteCustomerResult
  // DELETE FROM customers
  // WHERE id = $1
  const deleteCustomerResult = execResult({
    Request: DeleteCustomerResultParams,
    execute: (params) => sql`DELETE FROM customers
WHERE id = ${params.id}`
  })

  // CountCustomers
  // SELECT COUNT(*) AS total
  // FROM customers
  const countCustomers = SqlSchema.findOneOption({
    Request: Schema.Void,
    Result: CountCustomersResult,
    execute: () => sql`SELECT COUNT(*) AS total
FROM customers`
  })

  // GetCustomersByIds
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // WHERE id = ANY($1::int[])
  const getCustomersByIds = SqlSchema.findAll({
    Request: GetCustomersByIdsParams,
    Result: GetCustomersByIdsResult,
    execute: (params) => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
WHERE id = ANY(${params.ids}::int[])`
  })

  // GetCustomersByIdsSlice
  // SELECT id, email, name, phone, created_at, updated_at
  // FROM customers
  // WHERE id IN ($1)
  // ORDER BY id
  const getCustomersByIdsSlice = SqlSchema.findAll({
    Request: GetCustomersByIdsSliceParams,
    Result: GetCustomersByIdsSliceResult,
    execute: (params) => sql`SELECT id, email, name, phone, created_at, updated_at
FROM customers
WHERE ${sql.in("id", params.ids)}
ORDER BY id`
  })

  return {
    getCustomer,
    getCustomerByEmail,
    listCustomers,
    listCustomersPaginated,
    searchCustomersByName,
    searchCustomersByEmailDomain,
    createCustomer,
    updateCustomer,
    patchCustomer,
    updateCustomerEmail,
    deleteCustomer,
    deleteCustomerResult,
    countCustomers,
    getCustomersByIds,
    getCustomersByIdsSlice,
  } as const
})

// Service Tag
export class CustomersRepository extends Context.Service<CustomersRepository>()("CustomersRepository", { make: customersRepositoryMake }) {
  static readonly layer = Layer.effect(this, this.make)
}

export type CustomersRepositoryService = CustomersRepository["Service"]

// Live Layer
export const customersRepositoryLive = CustomersRepository.layer
