// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { BigIntFromString } from "./models.js"
import { Schema } from "effect"

// GetCustomer - Result Schema
export const GetCustomerResult = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
  name: Schema.String,
  phone: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type GetCustomerResult = typeof GetCustomerResult.Type
// GetCustomerByEmail - Result Schema
export const GetCustomerByEmailResult = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
  name: Schema.String,
  phone: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type GetCustomerByEmailResult = typeof GetCustomerByEmailResult.Type
// ListCustomers - Result Schema
export const ListCustomersResult = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
  name: Schema.String,
  phone: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListCustomersResult = typeof ListCustomersResult.Type
// ListCustomersPaginated - Result Schema
export const ListCustomersPaginatedResult = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
  name: Schema.String,
  phone: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListCustomersPaginatedResult = typeof ListCustomersPaginatedResult.Type
// SearchCustomersByName - Result Schema
export const SearchCustomersByNameResult = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
  name: Schema.String,
  phone: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type SearchCustomersByNameResult = typeof SearchCustomersByNameResult.Type
// CreateCustomer - Result Schema
export const CreateCustomerResult = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
  name: Schema.String,
  phone: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type CreateCustomerResult = typeof CreateCustomerResult.Type
// UpdateCustomer - Result Schema
export const UpdateCustomerResult = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
  name: Schema.String,
  phone: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type UpdateCustomerResult = typeof UpdateCustomerResult.Type
// CountCustomers - Result Schema
export const CountCustomersResult = Schema.Struct({
  total: BigIntFromString,
})

export type CountCustomersResult = typeof CountCustomersResult.Type
// GetCustomersByIds - Result Schema
export const GetCustomersByIdsResult = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
  name: Schema.String,
  phone: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type GetCustomersByIdsResult = typeof GetCustomersByIdsResult.Type
