// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { Schema } from "effect"

// GetCustomer - Parameters Schema
export const GetCustomerParams = Schema.Struct({
  id: Schema.Int,
})

export type GetCustomerParams = typeof GetCustomerParams.Type

// GetCustomerByEmail - Parameters Schema
export const GetCustomerByEmailParams = Schema.Struct({
  email: Schema.String,
})

export type GetCustomerByEmailParams = typeof GetCustomerByEmailParams.Type

// ListCustomersPaginated - Parameters Schema
export const ListCustomersPaginatedParams = Schema.Struct({
  limit: Schema.Int,
  offset: Schema.Int,
})

export type ListCustomersPaginatedParams = typeof ListCustomersPaginatedParams.Type

// SearchCustomersByName - Parameters Schema
export const SearchCustomersByNameParams = Schema.Struct({
  arg1: Schema.optional(Schema.String),
})

export type SearchCustomersByNameParams = typeof SearchCustomersByNameParams.Type

// CreateCustomer - Parameters Schema
export const CreateCustomerParams = Schema.Struct({
  email: Schema.String,
  name: Schema.String,
  phone: Schema.optional(Schema.String),
})

export type CreateCustomerParams = typeof CreateCustomerParams.Type

// UpdateCustomer - Parameters Schema
export const UpdateCustomerParams = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
  name: Schema.String,
  phone: Schema.optional(Schema.String),
})

export type UpdateCustomerParams = typeof UpdateCustomerParams.Type

// UpdateCustomerEmail - Parameters Schema
export const UpdateCustomerEmailParams = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
})

export type UpdateCustomerEmailParams = typeof UpdateCustomerEmailParams.Type

// DeleteCustomer - Parameters Schema
export const DeleteCustomerParams = Schema.Struct({
  id: Schema.Int,
})

export type DeleteCustomerParams = typeof DeleteCustomerParams.Type

// GetCustomersByIds - Parameters Schema
export const GetCustomersByIdsParams = Schema.Struct({
  ids: Schema.Array(Schema.Int),
})

export type GetCustomersByIdsParams = typeof GetCustomersByIdsParams.Type
