// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { CustomersRow, OrderStatusSchema, OrdersRow } from "./models.js"
import { Schema, SchemaTransformation } from "effect"

// GetOrderWithCustomerEmbed - Row Schema (flat database result)
const GetOrderWithCustomerEmbedRow = Schema.Struct({
  orders_id: Schema.Int,
  orders_customer_id: Schema.Int,
  orders_status: OrderStatusSchema,
  orders_total_cents: Schema.Int,
  orders_shipping_address: Schema.NullOr(Schema.String),
  orders_billing_address: Schema.NullOr(Schema.String),
  orders_notes: Schema.NullOr(Schema.String),
  orders_created_at: Schema.Date,
  orders_updated_at: Schema.Date,
  orders_search_vector: Schema.NullOr(Schema.String),
  customers_id: Schema.Int,
  customers_email: Schema.String,
  customers_name: Schema.String,
  customers_phone: Schema.NullOr(Schema.String),
  customers_created_at: Schema.Date,
  customers_updated_at: Schema.Date,
})

// GetOrderWithCustomerEmbed - Nested Result Schema
const GetOrderWithCustomerEmbedResultNested = Schema.Struct({
  order: OrdersRow,
  customer: CustomersRow,
})

// GetOrderWithCustomerEmbed - Result Schema (transformed to nested structure)
export const GetOrderWithCustomerEmbedResult = GetOrderWithCustomerEmbedRow.pipe(
  Schema.decodeTo(
    GetOrderWithCustomerEmbedResultNested,
    SchemaTransformation.transform({
      decode: (row) => ({
        order: {
          id: row.orders_id,
          customer_id: row.orders_customer_id,
          status: row.orders_status,
          total_cents: row.orders_total_cents,
          shipping_address: row.orders_shipping_address,
          billing_address: row.orders_billing_address,
          notes: row.orders_notes,
          created_at: row.orders_created_at,
          updated_at: row.orders_updated_at,
          search_vector: row.orders_search_vector,
        },
        customer: {
          id: row.customers_id,
          email: row.customers_email,
          name: row.customers_name,
          phone: row.customers_phone,
          created_at: row.customers_created_at,
          updated_at: row.customers_updated_at,
        },
      }),
      // Encode is never used for sqlc.embed queries (read-only), but required by the API
      encode: (_nested) => { throw new Error("Encode not supported for sqlc.embed queries"); },
    })
  )
)

export type GetOrderWithCustomerEmbedResult = typeof GetOrderWithCustomerEmbedResult.Type
// ListOrdersWithCustomerEmbed - Row Schema (flat database result)
const ListOrdersWithCustomerEmbedRow = Schema.Struct({
  orders_id: Schema.Int,
  orders_customer_id: Schema.Int,
  orders_status: OrderStatusSchema,
  orders_total_cents: Schema.Int,
  orders_shipping_address: Schema.NullOr(Schema.String),
  orders_billing_address: Schema.NullOr(Schema.String),
  orders_notes: Schema.NullOr(Schema.String),
  orders_created_at: Schema.Date,
  orders_updated_at: Schema.Date,
  orders_search_vector: Schema.NullOr(Schema.String),
  customers_id: Schema.Int,
  customers_email: Schema.String,
  customers_name: Schema.String,
  customers_phone: Schema.NullOr(Schema.String),
  customers_created_at: Schema.Date,
  customers_updated_at: Schema.Date,
})

// ListOrdersWithCustomerEmbed - Nested Result Schema
const ListOrdersWithCustomerEmbedResultNested = Schema.Struct({
  order: OrdersRow,
  customer: CustomersRow,
})

// ListOrdersWithCustomerEmbed - Result Schema (transformed to nested structure)
export const ListOrdersWithCustomerEmbedResult = ListOrdersWithCustomerEmbedRow.pipe(
  Schema.decodeTo(
    ListOrdersWithCustomerEmbedResultNested,
    SchemaTransformation.transform({
      decode: (row) => ({
        order: {
          id: row.orders_id,
          customer_id: row.orders_customer_id,
          status: row.orders_status,
          total_cents: row.orders_total_cents,
          shipping_address: row.orders_shipping_address,
          billing_address: row.orders_billing_address,
          notes: row.orders_notes,
          created_at: row.orders_created_at,
          updated_at: row.orders_updated_at,
          search_vector: row.orders_search_vector,
        },
        customer: {
          id: row.customers_id,
          email: row.customers_email,
          name: row.customers_name,
          phone: row.customers_phone,
          created_at: row.customers_created_at,
          updated_at: row.customers_updated_at,
        },
      }),
      // Encode is never used for sqlc.embed queries (read-only), but required by the API
      encode: (_nested) => { throw new Error("Encode not supported for sqlc.embed queries"); },
    })
  )
)

export type ListOrdersWithCustomerEmbedResult = typeof ListOrdersWithCustomerEmbedResult.Type
