// Generated by sqlc v1.31.1, plugin: sqlc-effect dev
import { Schema } from "effect"

// GetOrderWithCustomerEmbed - Parameters Schema
export const GetOrderWithCustomerEmbedParams = Schema.Struct({
  id: Schema.Int,
})

export type GetOrderWithCustomerEmbedParams = typeof GetOrderWithCustomerEmbedParams.Type
