// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { CustomersRow, OrderStatusSchema, OrdersRow } from "./models.js"
import { Schema } from "effect"

// GetOrderWithCustomerEmbed - Row Schema (flat database result)
export const GetOrderWithCustomerEmbedRow = Schema.Struct({
  orders_id: Schema.Int,
  orders_customer_id: Schema.Int,
  orders_status: OrderStatusSchema,
  orders_total_cents: Schema.Int,
  orders_shipping_address: Schema.OptionFromNullOr(Schema.String),
  orders_billing_address: Schema.OptionFromNullOr(Schema.String),
  orders_notes: Schema.OptionFromNullOr(Schema.String),
  orders_created_at: Schema.Date,
  orders_updated_at: Schema.Date,
  orders_search_vector: Schema.OptionFromNullOr(Schema.String),
  customers_id: Schema.Int,
  customers_email: Schema.String,
  customers_name: Schema.String,
  customers_phone: Schema.OptionFromNullOr(Schema.String),
  customers_created_at: Schema.Date,
  customers_updated_at: Schema.Date,
})

export type GetOrderWithCustomerEmbedRow = typeof GetOrderWithCustomerEmbedRow.Type

// GetOrderWithCustomerEmbed - Result Schema (nested public result)
export const GetOrderWithCustomerEmbedResult = Schema.Struct({
  order: OrdersRow,
  customer: CustomersRow,
})

export type GetOrderWithCustomerEmbedResult = typeof GetOrderWithCustomerEmbedResult.Type

// GetOrderWithCustomerEmbed - One-way projection from the decoded database row
export const mapGetOrderWithCustomerEmbedRowToResult = (
  row: GetOrderWithCustomerEmbedRow,
): GetOrderWithCustomerEmbedResult => ({
  order: {
    id: row.orders_id,
    customer_id: row.orders_customer_id,
    status: row.orders_status,
    total_cents: row.orders_total_cents,
    shipping_address: row.orders_shipping_address,
    billing_address: row.orders_billing_address,
    notes: row.orders_notes,
    created_at: row.orders_created_at,
    updated_at: row.orders_updated_at,
    search_vector: row.orders_search_vector,
  },
  customer: {
    id: row.customers_id,
    email: row.customers_email,
    name: row.customers_name,
    phone: row.customers_phone,
    created_at: row.customers_created_at,
    updated_at: row.customers_updated_at,
  },
})
// ListOrdersWithCustomerEmbed - Row Schema (flat database result)
export const ListOrdersWithCustomerEmbedRow = Schema.Struct({
  orders_id: Schema.Int,
  orders_customer_id: Schema.Int,
  orders_status: OrderStatusSchema,
  orders_total_cents: Schema.Int,
  orders_shipping_address: Schema.OptionFromNullOr(Schema.String),
  orders_billing_address: Schema.OptionFromNullOr(Schema.String),
  orders_notes: Schema.OptionFromNullOr(Schema.String),
  orders_created_at: Schema.Date,
  orders_updated_at: Schema.Date,
  orders_search_vector: Schema.OptionFromNullOr(Schema.String),
  customers_id: Schema.Int,
  customers_email: Schema.String,
  customers_name: Schema.String,
  customers_phone: Schema.OptionFromNullOr(Schema.String),
  customers_created_at: Schema.Date,
  customers_updated_at: Schema.Date,
})

export type ListOrdersWithCustomerEmbedRow = typeof ListOrdersWithCustomerEmbedRow.Type

// ListOrdersWithCustomerEmbed - Result Schema (nested public result)
export const ListOrdersWithCustomerEmbedResult = Schema.Struct({
  order: OrdersRow,
  customer: CustomersRow,
})

export type ListOrdersWithCustomerEmbedResult = typeof ListOrdersWithCustomerEmbedResult.Type

// ListOrdersWithCustomerEmbed - One-way projection from the decoded database row
export const mapListOrdersWithCustomerEmbedRowToResult = (
  row: ListOrdersWithCustomerEmbedRow,
): ListOrdersWithCustomerEmbedResult => ({
  order: {
    id: row.orders_id,
    customer_id: row.orders_customer_id,
    status: row.orders_status,
    total_cents: row.orders_total_cents,
    shipping_address: row.orders_shipping_address,
    billing_address: row.orders_billing_address,
    notes: row.orders_notes,
    created_at: row.orders_created_at,
    updated_at: row.orders_updated_at,
    search_vector: row.orders_search_vector,
  },
  customer: {
    id: row.customers_id,
    email: row.customers_email,
    name: row.customers_name,
    phone: row.customers_phone,
    created_at: row.customers_created_at,
    updated_at: row.customers_updated_at,
  },
})
