// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { CustomersRow, OrderDetailsRow, OrderStatusSchema } from "./models.js"
import { Schema } from "effect"

// GetOrderWithCustomerEmbed - Row Schema (flat database result)
export const GetOrderWithCustomerEmbedRow = Schema.Struct({
  order_details_id: Schema.Int,
  order_details_customer_id: Schema.Int,
  order_details_status: OrderStatusSchema,
  order_details_total_cents: Schema.Int,
  order_details_shipping_address: Schema.OptionFromNullOr(Schema.String),
  order_details_billing_address: Schema.OptionFromNullOr(Schema.String),
  order_details_notes: Schema.OptionFromNullOr(Schema.String),
  order_details_created_at: Schema.Date,
  order_details_updated_at: Schema.Date,
  order_details_search_vector: Schema.String,
  customers_id: Schema.Int,
  customers_email: Schema.String,
  customers_name: Schema.String,
  customers_phone: Schema.OptionFromNullOr(Schema.String),
  customers_created_at: Schema.Date,
  customers_updated_at: Schema.Date,
})

export type GetOrderWithCustomerEmbedRow = typeof GetOrderWithCustomerEmbedRow.Type

// GetOrderWithCustomerEmbed - Result Schema (nested public result)
export const GetOrderWithCustomerEmbedResult = Schema.Struct({
  orderDetail: OrderDetailsRow,
  customer: CustomersRow,
})

export type GetOrderWithCustomerEmbedResult = typeof GetOrderWithCustomerEmbedResult.Type

// GetOrderWithCustomerEmbed - One-way projection from the decoded database row
export const mapGetOrderWithCustomerEmbedRowToResult = (
  row: GetOrderWithCustomerEmbedRow,
): GetOrderWithCustomerEmbedResult => ({
  orderDetail: {
    id: row.order_details_id,
    customer_id: row.order_details_customer_id,
    status: row.order_details_status,
    total_cents: row.order_details_total_cents,
    shipping_address: row.order_details_shipping_address,
    billing_address: row.order_details_billing_address,
    notes: row.order_details_notes,
    created_at: row.order_details_created_at,
    updated_at: row.order_details_updated_at,
    search_vector: row.order_details_search_vector,
  },
  customer: {
    id: row.customers_id,
    email: row.customers_email,
    name: row.customers_name,
    phone: row.customers_phone,
    created_at: row.customers_created_at,
    updated_at: row.customers_updated_at,
  },
})
// ListOrdersWithCustomerEmbed - Row Schema (flat database result)
export const ListOrdersWithCustomerEmbedRow = Schema.Struct({
  order_details_id: Schema.Int,
  order_details_customer_id: Schema.Int,
  order_details_status: OrderStatusSchema,
  order_details_total_cents: Schema.Int,
  order_details_shipping_address: Schema.OptionFromNullOr(Schema.String),
  order_details_billing_address: Schema.OptionFromNullOr(Schema.String),
  order_details_notes: Schema.OptionFromNullOr(Schema.String),
  order_details_created_at: Schema.Date,
  order_details_updated_at: Schema.Date,
  order_details_search_vector: Schema.String,
  customers_id: Schema.Int,
  customers_email: Schema.String,
  customers_name: Schema.String,
  customers_phone: Schema.OptionFromNullOr(Schema.String),
  customers_created_at: Schema.Date,
  customers_updated_at: Schema.Date,
})

export type ListOrdersWithCustomerEmbedRow = typeof ListOrdersWithCustomerEmbedRow.Type

// ListOrdersWithCustomerEmbed - Result Schema (nested public result)
export const ListOrdersWithCustomerEmbedResult = Schema.Struct({
  orderDetail: OrderDetailsRow,
  customer: CustomersRow,
})

export type ListOrdersWithCustomerEmbedResult = typeof ListOrdersWithCustomerEmbedResult.Type

// ListOrdersWithCustomerEmbed - One-way projection from the decoded database row
export const mapListOrdersWithCustomerEmbedRowToResult = (
  row: ListOrdersWithCustomerEmbedRow,
): ListOrdersWithCustomerEmbedResult => ({
  orderDetail: {
    id: row.order_details_id,
    customer_id: row.order_details_customer_id,
    status: row.order_details_status,
    total_cents: row.order_details_total_cents,
    shipping_address: row.order_details_shipping_address,
    billing_address: row.order_details_billing_address,
    notes: row.order_details_notes,
    created_at: row.order_details_created_at,
    updated_at: row.order_details_updated_at,
    search_vector: row.order_details_search_vector,
  },
  customer: {
    id: row.customers_id,
    email: row.customers_email,
    name: row.customers_name,
    phone: row.customers_phone,
    created_at: row.customers_created_at,
    updated_at: row.customers_updated_at,
  },
})
