// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { GetOrderWithCustomerEmbedParams } from "./EmbedRepositoryRequest.js"
import { GetOrderWithCustomerEmbedRow, ListOrdersWithCustomerEmbedRow, mapGetOrderWithCustomerEmbedRowToResult, mapListOrdersWithCustomerEmbedRowToResult } from "./EmbedRepositoryResponse.js"
import { Context, Effect, Layer, Option, Schema } from "effect"
import { SqlClient, SqlSchema } from "effect/sql"

// Implementation
const embedRepositoryMake = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient

  // GetOrderWithCustomerEmbed
  //
  // SELECT order_details.id AS order_details_id, order_details.customer_id AS order_details_customer_id, order_details.status AS order_details_status, order_details.total_cents AS order_details_total_cents, order_details.shipping_address AS order_details_shipping_address, order_details.billing_address AS order_details_billing_address, order_details.notes AS order_details_notes, order_details.created_at AS order_details_created_at, order_details.updated_at AS order_details_updated_at, order_details.search_vector AS order_details_search_vector, customers.id AS customers_id, customers.email AS customers_email, customers.name AS customers_name, customers.phone AS customers_phone, customers.created_at AS customers_created_at, customers.updated_at AS customers_updated_at
  // FROM order_details
  // JOIN customers ON order_details.customer_id = customers.id
  // WHERE order_details.id = $1
  const getOrderWithCustomerEmbedRaw = SqlSchema.findOneOption({
    Request: GetOrderWithCustomerEmbedParams,
    Result: GetOrderWithCustomerEmbedRow,
    execute: (params) => sql`
SELECT order_details.id AS order_details_id, order_details.customer_id AS order_details_customer_id, order_details.status AS order_details_status, order_details.total_cents AS order_details_total_cents, order_details.shipping_address AS order_details_shipping_address, order_details.billing_address AS order_details_billing_address, order_details.notes AS order_details_notes, order_details.created_at AS order_details_created_at, order_details.updated_at AS order_details_updated_at, order_details.search_vector AS order_details_search_vector, customers.id AS customers_id, customers.email AS customers_email, customers.name AS customers_name, customers.phone AS customers_phone, customers.created_at AS customers_created_at, customers.updated_at AS customers_updated_at
FROM order_details
JOIN customers ON order_details.customer_id = customers.id
WHERE order_details.id = ${params.id}`
  })

  const getOrderWithCustomerEmbed = (params: GetOrderWithCustomerEmbedParams) =>
    getOrderWithCustomerEmbedRaw(params).pipe(
      Effect.map(Option.map(mapGetOrderWithCustomerEmbedRowToResult))
    )

  // ListOrdersWithCustomerEmbed
  // SELECT order_details.id AS order_details_id, order_details.customer_id AS order_details_customer_id, order_details.status AS order_details_status, order_details.total_cents AS order_details_total_cents, order_details.shipping_address AS order_details_shipping_address, order_details.billing_address AS order_details_billing_address, order_details.notes AS order_details_notes, order_details.created_at AS order_details_created_at, order_details.updated_at AS order_details_updated_at, order_details.search_vector AS order_details_search_vector, customers.id AS customers_id, customers.email AS customers_email, customers.name AS customers_name, customers.phone AS customers_phone, customers.created_at AS customers_created_at, customers.updated_at AS customers_updated_at
  // FROM order_details
  // JOIN customers ON order_details.customer_id = customers.id
  // ORDER BY order_details.created_at DESC
  const listOrdersWithCustomerEmbedRaw = SqlSchema.findAll({
    Request: Schema.Void,
    Result: ListOrdersWithCustomerEmbedRow,
    execute: () => sql`SELECT order_details.id AS order_details_id, order_details.customer_id AS order_details_customer_id, order_details.status AS order_details_status, order_details.total_cents AS order_details_total_cents, order_details.shipping_address AS order_details_shipping_address, order_details.billing_address AS order_details_billing_address, order_details.notes AS order_details_notes, order_details.created_at AS order_details_created_at, order_details.updated_at AS order_details_updated_at, order_details.search_vector AS order_details_search_vector, customers.id AS customers_id, customers.email AS customers_email, customers.name AS customers_name, customers.phone AS customers_phone, customers.created_at AS customers_created_at, customers.updated_at AS customers_updated_at
FROM order_details
JOIN customers ON order_details.customer_id = customers.id
ORDER BY order_details.created_at DESC`
  })

  const listOrdersWithCustomerEmbed = () =>
    listOrdersWithCustomerEmbedRaw().pipe(
      Effect.map((rows) => rows.map(mapListOrdersWithCustomerEmbedRowToResult))
    )

  return {
    getOrderWithCustomerEmbed: Effect.fn("EmbedRepository.getOrderWithCustomerEmbed")(getOrderWithCustomerEmbed),
    listOrdersWithCustomerEmbed: Effect.fn("EmbedRepository.listOrdersWithCustomerEmbed")(listOrdersWithCustomerEmbed),
  } as const
})

// Service Tag
export class EmbedRepository extends Context.Service<EmbedRepository>()("EmbedRepository", { make: embedRepositoryMake }) {
  static readonly layer = Layer.effect(this, this.make)
}

export type EmbedRepositoryService = EmbedRepository["Service"]

// Live Layer
export const embedRepositoryLive = EmbedRepository.layer
