// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { GetOrderWithCustomerEmbedParams } from "./EmbedRepositoryRequest.js"
import { GetOrderWithCustomerEmbedResult, ListOrdersWithCustomerEmbedResult } from "./EmbedRepositoryResponse.js"
import { Effect, Layer, Option, Schema, ServiceMap } from "effect"
import { SqlClient, SqlError, SqlSchema } from "effect/unstable/sql"

// Repository interface for embed.sql
export interface EmbedRepositoryShape {
  readonly getOrderWithCustomerEmbed: (params: GetOrderWithCustomerEmbedParams) => Effect.Effect<
    Option.Option<GetOrderWithCustomerEmbedResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listOrdersWithCustomerEmbed: () => Effect.Effect<
    ListOrdersWithCustomerEmbedResult[],
    SqlError.SqlError | Schema.SchemaError
  >
}

// Service Tag
export class EmbedRepository extends ServiceMap.Service<EmbedRepository, EmbedRepositoryShape>()("EmbedRepository") { }

// Implementation
const embedRepositoryImpl = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient

  // GetOrderWithCustomerEmbed
  //
  // SELECT orders.id AS orders_id, orders.customer_id AS orders_customer_id, orders.status AS orders_status, orders.total_cents AS orders_total_cents, orders.shipping_address AS orders_shipping_address, orders.billing_address AS orders_billing_address, orders.notes AS orders_notes, orders.created_at AS orders_created_at, orders.updated_at AS orders_updated_at, orders.search_vector AS orders_search_vector, customers.id AS customers_id, customers.email AS customers_email, customers.name AS customers_name, customers.phone AS customers_phone, customers.created_at AS customers_created_at, customers.updated_at AS customers_updated_at
  // FROM orders
  // JOIN customers ON orders.customer_id = customers.id
  // WHERE orders.id = $1
  const getOrderWithCustomerEmbed = SqlSchema.findOneOption({
    Request: GetOrderWithCustomerEmbedParams,
    Result: GetOrderWithCustomerEmbedResult,
    execute: (params) => sql`
SELECT orders.id AS orders_id, orders.customer_id AS orders_customer_id, orders.status AS orders_status, orders.total_cents AS orders_total_cents, orders.shipping_address AS orders_shipping_address, orders.billing_address AS orders_billing_address, orders.notes AS orders_notes, orders.created_at AS orders_created_at, orders.updated_at AS orders_updated_at, orders.search_vector AS orders_search_vector, customers.id AS customers_id, customers.email AS customers_email, customers.name AS customers_name, customers.phone AS customers_phone, customers.created_at AS customers_created_at, customers.updated_at AS customers_updated_at
FROM orders
JOIN customers ON orders.customer_id = customers.id
WHERE orders.id = ${params.id}`
  })

  // ListOrdersWithCustomerEmbed
  // SELECT orders.id AS orders_id, orders.customer_id AS orders_customer_id, orders.status AS orders_status, orders.total_cents AS orders_total_cents, orders.shipping_address AS orders_shipping_address, orders.billing_address AS orders_billing_address, orders.notes AS orders_notes, orders.created_at AS orders_created_at, orders.updated_at AS orders_updated_at, orders.search_vector AS orders_search_vector, customers.id AS customers_id, customers.email AS customers_email, customers.name AS customers_name, customers.phone AS customers_phone, customers.created_at AS customers_created_at, customers.updated_at AS customers_updated_at
  // FROM orders
  // JOIN customers ON orders.customer_id = customers.id
  // ORDER BY orders.created_at DESC
  const listOrdersWithCustomerEmbed = SqlSchema.findAll({
    Request: Schema.Void,
    Result: ListOrdersWithCustomerEmbedResult,
    execute: () => sql`SELECT orders.id AS orders_id, orders.customer_id AS orders_customer_id, orders.status AS orders_status, orders.total_cents AS orders_total_cents, orders.shipping_address AS orders_shipping_address, orders.billing_address AS orders_billing_address, orders.notes AS orders_notes, orders.created_at AS orders_created_at, orders.updated_at AS orders_updated_at, orders.search_vector AS orders_search_vector, customers.id AS customers_id, customers.email AS customers_email, customers.name AS customers_name, customers.phone AS customers_phone, customers.created_at AS customers_created_at, customers.updated_at AS customers_updated_at
FROM orders
JOIN customers ON orders.customer_id = customers.id
ORDER BY orders.created_at DESC`
  })

  return {
    getOrderWithCustomerEmbed,
    listOrdersWithCustomerEmbed,
  } satisfies EmbedRepositoryShape
})

// Live Layer
export const embedRepositoryLive = Layer.effect(EmbedRepository, embedRepositoryImpl)
