// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { ServiceMap, Effect, Layer, Schema, Option, SchemaTransformation } from "effect"
import { SqlClient, SqlError, SqlSchema } from "effect/unstable/sql"

// order_status enum schema
export const OrderStatusSchema = Schema.Literals(["pending", "confirmed", "processing", "shipped", "delivered", "cancelled", "refunded"])

// GetOrderWithCustomerEmbed - Parameters Schema
export const GetOrderWithCustomerEmbedParams = Schema.Struct({
  id: Schema.Int,
})

export type GetOrderWithCustomerEmbedParams = typeof GetOrderWithCustomerEmbedParams.Type

// GetOrderWithCustomerEmbed - Row Schema (flat database result)
const GetOrderWithCustomerEmbedRow = Schema.Struct({
  orders_id: Schema.Int,
  orders_customer_id: Schema.Int,
  orders_status: OrderStatusSchema,
  orders_total_cents: Schema.Int,
  orders_shipping_address: Schema.NullOr(Schema.String),
  orders_billing_address: Schema.NullOr(Schema.String),
  orders_notes: Schema.NullOr(Schema.String),
  orders_created_at: Schema.Date,
  orders_updated_at: Schema.Date,
  orders_search_vector: Schema.NullOr(Schema.String),
  customers_id: Schema.Int,
  customers_email: Schema.String,
  customers_name: Schema.String,
  customers_phone: Schema.NullOr(Schema.String),
  customers_created_at: Schema.Date,
  customers_updated_at: Schema.Date,
})

// orders embed schema
const GetOrderWithCustomerEmbedOrdersEmbed = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
  search_vector: Schema.OptionFromNullOr(Schema.String),
})
// customers embed schema
const GetOrderWithCustomerEmbedCustomersEmbed = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
  name: Schema.String,
  phone: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

// GetOrderWithCustomerEmbed - Nested Result Schema
const GetOrderWithCustomerEmbedResultNested = Schema.Struct({
  order: GetOrderWithCustomerEmbedOrdersEmbed,
  customer: GetOrderWithCustomerEmbedCustomersEmbed,
})

// GetOrderWithCustomerEmbed - Result Schema (transformed to nested structure)
export const GetOrderWithCustomerEmbedResult = GetOrderWithCustomerEmbedRow.pipe(
  Schema.decodeTo(
    GetOrderWithCustomerEmbedResultNested,
    SchemaTransformation.transform({
      decode: (row) => ({
        order: {
          id: row.orders_id,
          customer_id: row.orders_customer_id,
          status: row.orders_status,
          total_cents: row.orders_total_cents,
          shipping_address: row.orders_shipping_address,
          billing_address: row.orders_billing_address,
          notes: row.orders_notes,
          created_at: row.orders_created_at,
          updated_at: row.orders_updated_at,
          search_vector: row.orders_search_vector,
        },
        customer: {
          id: row.customers_id,
          email: row.customers_email,
          name: row.customers_name,
          phone: row.customers_phone,
          created_at: row.customers_created_at,
          updated_at: row.customers_updated_at,
        },
      }),
      // Encode is never used for sqlc.embed queries (read-only), but required by the API
      encode: (_nested) => { throw new Error("Encode not supported for sqlc.embed queries"); },
    })
  )
)

export type GetOrderWithCustomerEmbedResult = typeof GetOrderWithCustomerEmbedResult.Type

// ListOrdersWithCustomerEmbed - Row Schema (flat database result)
const ListOrdersWithCustomerEmbedRow = Schema.Struct({
  orders_id: Schema.Int,
  orders_customer_id: Schema.Int,
  orders_status: OrderStatusSchema,
  orders_total_cents: Schema.Int,
  orders_shipping_address: Schema.NullOr(Schema.String),
  orders_billing_address: Schema.NullOr(Schema.String),
  orders_notes: Schema.NullOr(Schema.String),
  orders_created_at: Schema.Date,
  orders_updated_at: Schema.Date,
  orders_search_vector: Schema.NullOr(Schema.String),
  customers_id: Schema.Int,
  customers_email: Schema.String,
  customers_name: Schema.String,
  customers_phone: Schema.NullOr(Schema.String),
  customers_created_at: Schema.Date,
  customers_updated_at: Schema.Date,
})

// orders embed schema
const ListOrdersWithCustomerEmbedOrdersEmbed = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
  search_vector: Schema.OptionFromNullOr(Schema.String),
})
// customers embed schema
const ListOrdersWithCustomerEmbedCustomersEmbed = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
  name: Schema.String,
  phone: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

// ListOrdersWithCustomerEmbed - Nested Result Schema
const ListOrdersWithCustomerEmbedResultNested = Schema.Struct({
  order: ListOrdersWithCustomerEmbedOrdersEmbed,
  customer: ListOrdersWithCustomerEmbedCustomersEmbed,
})

// ListOrdersWithCustomerEmbed - Result Schema (transformed to nested structure)
export const ListOrdersWithCustomerEmbedResult = ListOrdersWithCustomerEmbedRow.pipe(
  Schema.decodeTo(
    ListOrdersWithCustomerEmbedResultNested,
    SchemaTransformation.transform({
      decode: (row) => ({
        order: {
          id: row.orders_id,
          customer_id: row.orders_customer_id,
          status: row.orders_status,
          total_cents: row.orders_total_cents,
          shipping_address: row.orders_shipping_address,
          billing_address: row.orders_billing_address,
          notes: row.orders_notes,
          created_at: row.orders_created_at,
          updated_at: row.orders_updated_at,
          search_vector: row.orders_search_vector,
        },
        customer: {
          id: row.customers_id,
          email: row.customers_email,
          name: row.customers_name,
          phone: row.customers_phone,
          created_at: row.customers_created_at,
          updated_at: row.customers_updated_at,
        },
      }),
      // Encode is never used for sqlc.embed queries (read-only), but required by the API
      encode: (_nested) => { throw new Error("Encode not supported for sqlc.embed queries"); },
    })
  )
)

export type ListOrdersWithCustomerEmbedResult = typeof ListOrdersWithCustomerEmbedResult.Type

// Repository interface for embed.sql
export interface EmbedRepositoryShape {
  readonly getOrderWithCustomerEmbed: (params: GetOrderWithCustomerEmbedParams) => Effect.Effect<
    Option.Option<GetOrderWithCustomerEmbedResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listOrdersWithCustomerEmbed: () => Effect.Effect<
    ListOrdersWithCustomerEmbedResult[],
    SqlError.SqlError | Schema.SchemaError
  >
}

// Service Tag
export class EmbedRepository extends ServiceMap.Service<EmbedRepository, EmbedRepositoryShape>()("EmbedRepository") { }

// Implementation
const embedRepositoryImpl = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient

  // GetOrderWithCustomerEmbed
  //
  // SELECT orders.id, orders.customer_id, orders.status, orders.total_cents, orders.shipping_address, orders.billing_address, orders.notes, orders.created_at, orders.updated_at, orders.search_vector, customers.id, customers.email, customers.name, customers.phone, customers.created_at, customers.updated_at
  // FROM orders
  // JOIN customers ON orders.customer_id = customers.id
  // WHERE orders.id = $1
  const getOrderWithCustomerEmbed = SqlSchema.findOneOption({
    Request: GetOrderWithCustomerEmbedParams,
    Result: GetOrderWithCustomerEmbedResult,
    execute: (params) => sql`
SELECT orders.id, orders.customer_id, orders.status, orders.total_cents, orders.shipping_address, orders.billing_address, orders.notes, orders.created_at, orders.updated_at, orders.search_vector, customers.id, customers.email, customers.name, customers.phone, customers.created_at, customers.updated_at
FROM orders
JOIN customers ON orders.customer_id = customers.id
WHERE orders.id = ${params.id}`
  })

  // ListOrdersWithCustomerEmbed
  // SELECT orders.id, orders.customer_id, orders.status, orders.total_cents, orders.shipping_address, orders.billing_address, orders.notes, orders.created_at, orders.updated_at, orders.search_vector, customers.id, customers.email, customers.name, customers.phone, customers.created_at, customers.updated_at
  // FROM orders
  // JOIN customers ON orders.customer_id = customers.id
  // ORDER BY orders.created_at DESC
  const listOrdersWithCustomerEmbed = SqlSchema.findAll({
    Request: Schema.Void,
    Result: ListOrdersWithCustomerEmbedResult,
    execute: () => sql`SELECT orders.id, orders.customer_id, orders.status, orders.total_cents, orders.shipping_address, orders.billing_address, orders.notes, orders.created_at, orders.updated_at, orders.search_vector, customers.id, customers.email, customers.name, customers.phone, customers.created_at, customers.updated_at
FROM orders
JOIN customers ON orders.customer_id = customers.id
ORDER BY orders.created_at DESC`
  })

  return {
    getOrderWithCustomerEmbed,
    listOrdersWithCustomerEmbed,
  } satisfies EmbedRepositoryShape
})

// Live Layer
export const embedRepositoryLive = Layer.effect(EmbedRepository, embedRepositoryImpl)
