// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { Effect, Schema, SchemaGetter } from "effect"

// PostgreSQL returns bigint as string to preserve precision, so we need to transform it
export const BigIntFromString = Schema.String.pipe(
  Schema.decodeTo(
    Schema.BigInt,
    {
      decode: SchemaGetter.transform((s) => BigInt(s)),
      encode: SchemaGetter.transform((n) => String(n))
    }
  )
)

// PostgreSQL returns affected row count in the raw result metadata
export const ExecResult = Schema.Struct({ rowCount: Schema.NullOr(Schema.Int) })

// Helper for :execrows queries - returns affected row count (similar to SqlSchema.void but returns count)
export const execRows = <Req extends Schema.Top, E, R>(options: {
  readonly Request: Req
  readonly execute: (request: Req["Encoded"]) => { raw: Effect.Effect<unknown, E, R> }
}) => {
  const encode = Schema.encodeEffect(options.Request)
  const decodeResult = Schema.decodeUnknownEffect(ExecResult)
  return (request: Req["Type"]): Effect.Effect<number, E | Schema.SchemaError, R | Req["EncodingServices"]> =>
    Effect.flatMap(
      Effect.flatMap(encode(request), (encoded) => options.execute(encoded).raw),
      (raw) => Effect.map(decodeResult(raw), (r) => r.rowCount ?? 0)
    )
}

// OrderStatus enum schema
export const OrderStatusSchema = Schema.Literals(["pending", "confirmed", "processing", "shipped", "delivered", "cancelled", "refunded"])

// Customers table row schema
export const CustomersRow = Schema.Struct({
  id: Schema.Int,
  email: Schema.String,
  name: Schema.String,
  phone: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

// Orders table row schema
export const OrdersRow = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
  search_vector: Schema.OptionFromNullOr(Schema.String),
})
