// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { OrderStatusSchema } from "./models.js"
import { Schema } from "effect"

// GetOrder - Parameters Schema
export const GetOrderParams = Schema.Struct({
  id: Schema.Int,
})

export type GetOrderParams = typeof GetOrderParams.Type

// GetOrderWithCustomer - Parameters Schema
export const GetOrderWithCustomerParams = Schema.Struct({
  id: Schema.Int,
})

export type GetOrderWithCustomerParams = typeof GetOrderWithCustomerParams.Type

// ListOrdersByCustomer - Parameters Schema
export const ListOrdersByCustomerParams = Schema.Struct({
  customerId: Schema.Int,
})

export type ListOrdersByCustomerParams = typeof ListOrdersByCustomerParams.Type

// ListOrdersByStatus - Parameters Schema
export const ListOrdersByStatusParams = Schema.Struct({
  status: OrderStatusSchema,
})

export type ListOrdersByStatusParams = typeof ListOrdersByStatusParams.Type

// ListOrdersPaginated - Parameters Schema
export const ListOrdersPaginatedParams = Schema.Struct({
  limit: Schema.Int,
  offset: Schema.Int,
})

export type ListOrdersPaginatedParams = typeof ListOrdersPaginatedParams.Type

// ListOrdersByDateRange - Parameters Schema
export const ListOrdersByDateRangeParams = Schema.Struct({
  createdAt: Schema.Date,
  createdAt2: Schema.Date,
})

export type ListOrdersByDateRangeParams = typeof ListOrdersByDateRangeParams.Type

// ListOrdersByDateRangeNamed - Parameters Schema
export const ListOrdersByDateRangeNamedParams = Schema.Struct({
  startDate: Schema.Date,
  endDate: Schema.Date,
})

export type ListOrdersByDateRangeNamedParams = typeof ListOrdersByDateRangeNamedParams.Type

// ListRecentOrdersWithCustomer - Parameters Schema
export const ListRecentOrdersWithCustomerParams = Schema.Struct({
  limit: Schema.Int,
})

export type ListRecentOrdersWithCustomerParams = typeof ListRecentOrdersWithCustomerParams.Type

// SearchOrders - Parameters Schema
export const SearchOrdersParams = Schema.Struct({
  websearchToTsquery: Schema.String,
})

export type SearchOrdersParams = typeof SearchOrdersParams.Type

// CreateOrder - Parameters Schema
export const CreateOrderParams = Schema.Struct({
  customerId: Schema.Int,
  status: OrderStatusSchema,
  shippingAddress: Schema.optional(Schema.String),
  billingAddress: Schema.optional(Schema.String),
  notes: Schema.optional(Schema.String),
})

export type CreateOrderParams = typeof CreateOrderParams.Type

// UpdateOrderStatus - Parameters Schema
export const UpdateOrderStatusParams = Schema.Struct({
  id: Schema.Int,
  status: OrderStatusSchema,
})

export type UpdateOrderStatusParams = typeof UpdateOrderStatusParams.Type

// UpdateOrderAddresses - Parameters Schema
export const UpdateOrderAddressesParams = Schema.Struct({
  id: Schema.Int,
  shippingAddress: Schema.optional(Schema.String),
  billingAddress: Schema.optional(Schema.String),
})

export type UpdateOrderAddressesParams = typeof UpdateOrderAddressesParams.Type

// UpdateOrderTotal - Parameters Schema
export const UpdateOrderTotalParams = Schema.Struct({
  orderId: Schema.Int,
})

export type UpdateOrderTotalParams = typeof UpdateOrderTotalParams.Type

// DeleteOrder - Parameters Schema
export const DeleteOrderParams = Schema.Struct({
  id: Schema.Int,
})

export type DeleteOrderParams = typeof DeleteOrderParams.Type

// GetCustomerOrderStats - Parameters Schema
export const GetCustomerOrderStatsParams = Schema.Struct({
  customerId: Schema.Int,
})

export type GetCustomerOrderStatsParams = typeof GetCustomerOrderStatsParams.Type

// GetOrdersWithLineCount - Parameters Schema
export const GetOrdersWithLineCountParams = Schema.Struct({
  limit: Schema.Int,
  offset: Schema.Int,
})

export type GetOrdersWithLineCountParams = typeof GetOrdersWithLineCountParams.Type

// GetOrderLine - Parameters Schema
export const GetOrderLineParams = Schema.Struct({
  id: Schema.Int,
})

export type GetOrderLineParams = typeof GetOrderLineParams.Type

// ListOrderLines - Parameters Schema
export const ListOrderLinesParams = Schema.Struct({
  orderId: Schema.Int,
})

export type ListOrderLinesParams = typeof ListOrderLinesParams.Type

// ListOrderLinesWithProduct - Parameters Schema
export const ListOrderLinesWithProductParams = Schema.Struct({
  orderId: Schema.Int,
})

export type ListOrderLinesWithProductParams = typeof ListOrderLinesWithProductParams.Type

// GetFullOrderDetails - Parameters Schema
export const GetFullOrderDetailsParams = Schema.Struct({
  id: Schema.Int,
})

export type GetFullOrderDetailsParams = typeof GetFullOrderDetailsParams.Type

// CreateOrderLine - Parameters Schema
export const CreateOrderLineParams = Schema.Struct({
  orderId: Schema.Int,
  productId: Schema.Int,
  quantity: Schema.Int,
  unitPriceCents: Schema.Int,
  discountCents: Schema.Int,
})

export type CreateOrderLineParams = typeof CreateOrderLineParams.Type

// UpdateOrderLineQuantity - Parameters Schema
export const UpdateOrderLineQuantityParams = Schema.Struct({
  id: Schema.Int,
  quantity: Schema.Int,
})

export type UpdateOrderLineQuantityParams = typeof UpdateOrderLineQuantityParams.Type

// DeleteOrderLine - Parameters Schema
export const DeleteOrderLineParams = Schema.Struct({
  id: Schema.Int,
})

export type DeleteOrderLineParams = typeof DeleteOrderLineParams.Type

// DeleteOrderLines - Parameters Schema
export const DeleteOrderLinesParams = Schema.Struct({
  orderId: Schema.Int,
})

export type DeleteOrderLinesParams = typeof DeleteOrderLinesParams.Type

// GetOrderLineTotal - Parameters Schema
export const GetOrderLineTotalParams = Schema.Struct({
  orderId: Schema.Int,
})

export type GetOrderLineTotalParams = typeof GetOrderLineTotalParams.Type

// GetProductSalesStats - Parameters Schema
export const GetProductSalesStatsParams = Schema.Struct({
  id: Schema.Int,
})

export type GetProductSalesStatsParams = typeof GetProductSalesStatsParams.Type

// GetTopSellingProducts - Parameters Schema
export const GetTopSellingProductsParams = Schema.Struct({
  limit: Schema.Int,
})

export type GetTopSellingProductsParams = typeof GetTopSellingProductsParams.Type

// GetOrdersByProductIds - Parameters Schema
export const GetOrdersByProductIdsParams = Schema.Struct({
  productIds: Schema.Array(Schema.Int),
})

export type GetOrdersByProductIdsParams = typeof GetOrdersByProductIdsParams.Type
