// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { ServiceMap, Effect, Layer, Schema, Option, SchemaGetter } from "effect"
import { SqlClient, SqlError, SqlSchema } from "effect/unstable/sql"


// PostgreSQL returns bigint as string to preserve precision, so we need to transform it
const BigIntFromString = Schema.String.pipe(
  Schema.decodeTo(
    Schema.BigInt,
    {
      decode: SchemaGetter.transform((s) => BigInt(s)),
      encode: SchemaGetter.transform((n) => String(n))
    }
  )
)

// PostgreSQL returns affected row count in the raw result metadata
const ExecResult = Schema.Struct({ rowCount: Schema.NullOr(Schema.Int) })

// Helper for :execrows queries - returns affected row count (similar to SqlSchema.void but returns count)
const execRows = <Req extends Schema.Top, E, R>(options: {
  readonly Request: Req
  readonly execute: (request: Req["Encoded"]) => { raw: Effect.Effect<unknown, E, R> }
}) => {
  const encode = Schema.encodeEffect(options.Request)
  const decodeResult = Schema.decodeUnknownEffect(ExecResult)
  return (request: Req["Type"]): Effect.Effect<number, E | Schema.SchemaError, R | Req["EncodingServices"]> =>
    Effect.flatMap(
      Effect.flatMap(encode(request), (encoded) => options.execute(encoded).raw),
      (raw) => Effect.map(decodeResult(raw), (r) => r.rowCount ?? 0)
    )
}


// order_status enum schema
export const OrderStatusSchema = Schema.Literals(["pending", "confirmed", "processing", "shipped", "delivered", "cancelled", "refunded"])


// GetOrder - Parameters Schema
export const GetOrderParams = Schema.Struct({
  id: Schema.Int,
})

export type GetOrderParams = typeof GetOrderParams.Type

// GetOrder - Result Schema
export const GetOrderResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type GetOrderResult = typeof GetOrderResult.Type

// GetOrderWithCustomer - Parameters Schema
export const GetOrderWithCustomerParams = Schema.Struct({
  id: Schema.Int,
})

export type GetOrderWithCustomerParams = typeof GetOrderWithCustomerParams.Type

// GetOrderWithCustomer - Result Schema
export const GetOrderWithCustomerResult = Schema.Struct({
  id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
  customer_id: Schema.Int,
  customer_email: Schema.String,
  customer_name: Schema.String,
  customer_phone: Schema.OptionFromNullOr(Schema.String),
})

export type GetOrderWithCustomerResult = typeof GetOrderWithCustomerResult.Type

// ListOrders - Result Schema
export const ListOrdersResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListOrdersResult = typeof ListOrdersResult.Type

// ListOrdersByCustomer - Parameters Schema
export const ListOrdersByCustomerParams = Schema.Struct({
  customerId: Schema.Int,
})

export type ListOrdersByCustomerParams = typeof ListOrdersByCustomerParams.Type

// ListOrdersByCustomer - Result Schema
export const ListOrdersByCustomerResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListOrdersByCustomerResult = typeof ListOrdersByCustomerResult.Type

// ListOrdersByStatus - Parameters Schema
export const ListOrdersByStatusParams = Schema.Struct({
  status: OrderStatusSchema,
})

export type ListOrdersByStatusParams = typeof ListOrdersByStatusParams.Type

// ListOrdersByStatus - Result Schema
export const ListOrdersByStatusResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListOrdersByStatusResult = typeof ListOrdersByStatusResult.Type

// ListOrdersPaginated - Parameters Schema
export const ListOrdersPaginatedParams = Schema.Struct({
  limit: Schema.Int,
  offset: Schema.Int,
})

export type ListOrdersPaginatedParams = typeof ListOrdersPaginatedParams.Type

// ListOrdersPaginated - Result Schema
export const ListOrdersPaginatedResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListOrdersPaginatedResult = typeof ListOrdersPaginatedResult.Type

// ListOrdersByDateRange - Parameters Schema
export const ListOrdersByDateRangeParams = Schema.Struct({
  createdAt: Schema.Date,
  createdAt2: Schema.Date,
})

export type ListOrdersByDateRangeParams = typeof ListOrdersByDateRangeParams.Type

// ListOrdersByDateRange - Result Schema
export const ListOrdersByDateRangeResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListOrdersByDateRangeResult = typeof ListOrdersByDateRangeResult.Type

// ListOrdersByDateRangeNamed - Parameters Schema
export const ListOrdersByDateRangeNamedParams = Schema.Struct({
  startDate: Schema.Date,
  endDate: Schema.Date,
})

export type ListOrdersByDateRangeNamedParams = typeof ListOrdersByDateRangeNamedParams.Type

// ListOrdersByDateRangeNamed - Result Schema
export const ListOrdersByDateRangeNamedResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListOrdersByDateRangeNamedResult = typeof ListOrdersByDateRangeNamedResult.Type

// ListRecentOrdersWithCustomer - Parameters Schema
export const ListRecentOrdersWithCustomerParams = Schema.Struct({
  limit: Schema.Int,
})

export type ListRecentOrdersWithCustomerParams = typeof ListRecentOrdersWithCustomerParams.Type

// ListRecentOrdersWithCustomer - Result Schema
export const ListRecentOrdersWithCustomerResult = Schema.Struct({
  id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  created_at: Schema.Date,
  customer_name: Schema.String,
  customer_email: Schema.String,
})

export type ListRecentOrdersWithCustomerResult = typeof ListRecentOrdersWithCustomerResult.Type

// SearchOrders - Parameters Schema
export const SearchOrdersParams = Schema.Struct({
  websearchToTsquery: Schema.String,
})

export type SearchOrdersParams = typeof SearchOrdersParams.Type

// SearchOrders - Result Schema
export const SearchOrdersResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
})

export type SearchOrdersResult = typeof SearchOrdersResult.Type

// CreateOrder - Parameters Schema
export const CreateOrderParams = Schema.Struct({
  customerId: Schema.Int,
  status: OrderStatusSchema,
  shippingAddress: Schema.optional(Schema.String),
  billingAddress: Schema.optional(Schema.String),
  notes: Schema.optional(Schema.String),
})

export type CreateOrderParams = typeof CreateOrderParams.Type

// CreateOrder - Result Schema
export const CreateOrderResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type CreateOrderResult = typeof CreateOrderResult.Type

// UpdateOrderStatus - Parameters Schema
export const UpdateOrderStatusParams = Schema.Struct({
  id: Schema.Int,
  status: OrderStatusSchema,
})

export type UpdateOrderStatusParams = typeof UpdateOrderStatusParams.Type

// UpdateOrderAddresses - Parameters Schema
export const UpdateOrderAddressesParams = Schema.Struct({
  id: Schema.Int,
  shippingAddress: Schema.optional(Schema.String),
  billingAddress: Schema.optional(Schema.String),
})

export type UpdateOrderAddressesParams = typeof UpdateOrderAddressesParams.Type

// UpdateOrderTotal - Parameters Schema
export const UpdateOrderTotalParams = Schema.Struct({
  orderId: Schema.Int,
})

export type UpdateOrderTotalParams = typeof UpdateOrderTotalParams.Type

// DeleteOrder - Parameters Schema
export const DeleteOrderParams = Schema.Struct({
  id: Schema.Int,
})

export type DeleteOrderParams = typeof DeleteOrderParams.Type

// CountOrdersByStatus - Result Schema
export const CountOrdersByStatusResult = Schema.Struct({
  status: OrderStatusSchema,
  order_count: BigIntFromString,
})

export type CountOrdersByStatusResult = typeof CountOrdersByStatusResult.Type

// GetCustomerOrderStats - Parameters Schema
export const GetCustomerOrderStatsParams = Schema.Struct({
  customerId: Schema.Int,
})

export type GetCustomerOrderStatsParams = typeof GetCustomerOrderStatsParams.Type

// GetCustomerOrderStats - Result Schema
export const GetCustomerOrderStatsResult = Schema.Struct({
  total_orders: BigIntFromString,
  total_spent: Schema.OptionFromNullOr(Schema.String),
  avg_order_value: Schema.OptionFromNullOr(Schema.String),
})

export type GetCustomerOrderStatsResult = typeof GetCustomerOrderStatsResult.Type

// GetOrdersWithLineCount - Parameters Schema
export const GetOrdersWithLineCountParams = Schema.Struct({
  limit: Schema.Int,
  offset: Schema.Int,
})

export type GetOrdersWithLineCountParams = typeof GetOrdersWithLineCountParams.Type

// GetOrdersWithLineCount - Result Schema
export const GetOrdersWithLineCountResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  created_at: Schema.Date,
  line_count: BigIntFromString,
})

export type GetOrdersWithLineCountResult = typeof GetOrdersWithLineCountResult.Type

// GetOrderLine - Parameters Schema
export const GetOrderLineParams = Schema.Struct({
  id: Schema.Int,
})

export type GetOrderLineParams = typeof GetOrderLineParams.Type

// GetOrderLine - Result Schema
export const GetOrderLineResult = Schema.Struct({
  id: Schema.Int,
  order_id: Schema.Int,
  product_id: Schema.Int,
  quantity: Schema.Int,
  unit_price_cents: Schema.Int,
  discount_cents: Schema.Int,
  created_at: Schema.Date,
})

export type GetOrderLineResult = typeof GetOrderLineResult.Type

// ListOrderLines - Parameters Schema
export const ListOrderLinesParams = Schema.Struct({
  orderId: Schema.Int,
})

export type ListOrderLinesParams = typeof ListOrderLinesParams.Type

// ListOrderLines - Result Schema
export const ListOrderLinesResult = Schema.Struct({
  id: Schema.Int,
  order_id: Schema.Int,
  product_id: Schema.Int,
  quantity: Schema.Int,
  unit_price_cents: Schema.Int,
  discount_cents: Schema.Int,
  created_at: Schema.Date,
})

export type ListOrderLinesResult = typeof ListOrderLinesResult.Type

// ListOrderLinesWithProduct - Parameters Schema
export const ListOrderLinesWithProductParams = Schema.Struct({
  orderId: Schema.Int,
})

export type ListOrderLinesWithProductParams = typeof ListOrderLinesWithProductParams.Type

// ListOrderLinesWithProduct - Result Schema
export const ListOrderLinesWithProductResult = Schema.Struct({
  id: Schema.Int,
  order_id: Schema.Int,
  quantity: Schema.Int,
  unit_price_cents: Schema.Int,
  discount_cents: Schema.Int,
  created_at: Schema.Date,
  product_id: Schema.Int,
  product_sku: Schema.String,
  product_name: Schema.String,
})

export type ListOrderLinesWithProductResult = typeof ListOrderLinesWithProductResult.Type

// GetFullOrderDetails - Parameters Schema
export const GetFullOrderDetailsParams = Schema.Struct({
  id: Schema.Int,
})

export type GetFullOrderDetailsParams = typeof GetFullOrderDetailsParams.Type

// GetFullOrderDetails - Result Schema
export const GetFullOrderDetailsResult = Schema.Struct({
  order_id: Schema.Int,
  status: OrderStatusSchema,
  order_total: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  order_date: Schema.Date,
  customer_id: Schema.Int,
  customer_name: Schema.String,
  customer_email: Schema.String,
  line_id: Schema.Int,
  quantity: Schema.Int,
  unit_price_cents: Schema.Int,
  discount_cents: Schema.Int,
  product_id: Schema.Int,
  sku: Schema.String,
  product_name: Schema.String,
})

export type GetFullOrderDetailsResult = typeof GetFullOrderDetailsResult.Type

// CreateOrderLine - Parameters Schema
export const CreateOrderLineParams = Schema.Struct({
  orderId: Schema.Int,
  productId: Schema.Int,
  quantity: Schema.Int,
  unitPriceCents: Schema.Int,
  discountCents: Schema.Int,
})

export type CreateOrderLineParams = typeof CreateOrderLineParams.Type

// CreateOrderLine - Result Schema
export const CreateOrderLineResult = Schema.Struct({
  id: Schema.Int,
  order_id: Schema.Int,
  product_id: Schema.Int,
  quantity: Schema.Int,
  unit_price_cents: Schema.Int,
  discount_cents: Schema.Int,
  created_at: Schema.Date,
})

export type CreateOrderLineResult = typeof CreateOrderLineResult.Type

// UpdateOrderLineQuantity - Parameters Schema
export const UpdateOrderLineQuantityParams = Schema.Struct({
  id: Schema.Int,
  quantity: Schema.Int,
})

export type UpdateOrderLineQuantityParams = typeof UpdateOrderLineQuantityParams.Type

// DeleteOrderLine - Parameters Schema
export const DeleteOrderLineParams = Schema.Struct({
  id: Schema.Int,
})

export type DeleteOrderLineParams = typeof DeleteOrderLineParams.Type

// DeleteOrderLines - Parameters Schema
export const DeleteOrderLinesParams = Schema.Struct({
  orderId: Schema.Int,
})

export type DeleteOrderLinesParams = typeof DeleteOrderLinesParams.Type

// GetOrderLineTotal - Parameters Schema
export const GetOrderLineTotalParams = Schema.Struct({
  orderId: Schema.Int,
})

export type GetOrderLineTotalParams = typeof GetOrderLineTotalParams.Type

// GetOrderLineTotal - Result Schema
export const GetOrderLineTotalResult = Schema.Struct({
  total: Schema.OptionFromNullOr(Schema.String),
})

export type GetOrderLineTotalResult = typeof GetOrderLineTotalResult.Type

// GetProductSalesStats - Parameters Schema
export const GetProductSalesStatsParams = Schema.Struct({
  id: Schema.Int,
})

export type GetProductSalesStatsParams = typeof GetProductSalesStatsParams.Type

// GetProductSalesStats - Result Schema
export const GetProductSalesStatsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  total_sold: Schema.OptionFromNullOr(Schema.String),
  total_revenue: Schema.OptionFromNullOr(Schema.String),
})

export type GetProductSalesStatsResult = typeof GetProductSalesStatsResult.Type

// GetTopSellingProducts - Parameters Schema
export const GetTopSellingProductsParams = Schema.Struct({
  limit: Schema.Int,
})

export type GetTopSellingProductsParams = typeof GetTopSellingProductsParams.Type

// GetTopSellingProducts - Result Schema
export const GetTopSellingProductsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  category: Schema.OptionFromNullOr(Schema.String),
  total_sold: BigIntFromString,
  total_revenue: BigIntFromString,
})

export type GetTopSellingProductsResult = typeof GetTopSellingProductsResult.Type

// GetOrdersByProductIds - Parameters Schema
export const GetOrdersByProductIdsParams = Schema.Struct({
  productIds: Schema.Array(Schema.Int),
})

export type GetOrdersByProductIdsParams = typeof GetOrdersByProductIdsParams.Type

// GetOrdersByProductIds - Result Schema
export const GetOrdersByProductIdsResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  created_at: Schema.Date,
})

export type GetOrdersByProductIdsResult = typeof GetOrdersByProductIdsResult.Type


// Repository interface for orders.sql
export interface OrdersRepositoryShape {
  readonly getOrder: (params: GetOrderParams) => Effect.Effect<
    Option.Option<GetOrderResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getOrderWithCustomer: (params: GetOrderWithCustomerParams) => Effect.Effect<
    Option.Option<GetOrderWithCustomerResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listOrders: () => Effect.Effect<
    ListOrdersResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listOrdersByCustomer: (params: ListOrdersByCustomerParams) => Effect.Effect<
    ListOrdersByCustomerResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listOrdersByStatus: (params: ListOrdersByStatusParams) => Effect.Effect<
    ListOrdersByStatusResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listOrdersPaginated: (params: ListOrdersPaginatedParams) => Effect.Effect<
    ListOrdersPaginatedResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listOrdersByDateRange: (params: ListOrdersByDateRangeParams) => Effect.Effect<
    ListOrdersByDateRangeResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listOrdersByDateRangeNamed: (params: ListOrdersByDateRangeNamedParams) => Effect.Effect<
    ListOrdersByDateRangeNamedResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listRecentOrdersWithCustomer: (params: ListRecentOrdersWithCustomerParams) => Effect.Effect<
    ListRecentOrdersWithCustomerResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly searchOrders: (params: SearchOrdersParams) => Effect.Effect<
    SearchOrdersResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly createOrder: (params: CreateOrderParams) => Effect.Effect<
    Option.Option<CreateOrderResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly updateOrderStatus: (params: UpdateOrderStatusParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly updateOrderAddresses: (params: UpdateOrderAddressesParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly updateOrderTotal: (params: UpdateOrderTotalParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly deleteOrder: (params: DeleteOrderParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly countOrdersByStatus: () => Effect.Effect<
    CountOrdersByStatusResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getCustomerOrderStats: (params: GetCustomerOrderStatsParams) => Effect.Effect<
    Option.Option<GetCustomerOrderStatsResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getOrdersWithLineCount: (params: GetOrdersWithLineCountParams) => Effect.Effect<
    GetOrdersWithLineCountResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getOrderLine: (params: GetOrderLineParams) => Effect.Effect<
    Option.Option<GetOrderLineResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listOrderLines: (params: ListOrderLinesParams) => Effect.Effect<
    ListOrderLinesResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listOrderLinesWithProduct: (params: ListOrderLinesWithProductParams) => Effect.Effect<
    ListOrderLinesWithProductResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getFullOrderDetails: (params: GetFullOrderDetailsParams) => Effect.Effect<
    GetFullOrderDetailsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly createOrderLine: (params: CreateOrderLineParams) => Effect.Effect<
    Option.Option<CreateOrderLineResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly updateOrderLineQuantity: (params: UpdateOrderLineQuantityParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly deleteOrderLine: (params: DeleteOrderLineParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly deleteOrderLines: (params: DeleteOrderLinesParams) => Effect.Effect<
    number,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getOrderLineTotal: (params: GetOrderLineTotalParams) => Effect.Effect<
    Option.Option<GetOrderLineTotalResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getProductSalesStats: (params: GetProductSalesStatsParams) => Effect.Effect<
    Option.Option<GetProductSalesStatsResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getTopSellingProducts: (params: GetTopSellingProductsParams) => Effect.Effect<
    GetTopSellingProductsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getOrdersByProductIds: (params: GetOrdersByProductIdsParams) => Effect.Effect<
    GetOrdersByProductIdsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
}

// Service Tag
export class OrdersRepository extends ServiceMap.Service<OrdersRepository, OrdersRepositoryShape>()("OrdersRepository") { }

// Implementation
const ordersRepositoryImpl = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient


  // GetOrder
  // SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
  // FROM orders
  // WHERE id = $1
  const getOrder = SqlSchema.findOneOption({
    Request: GetOrderParams,
    Result: GetOrderResult,
    execute: (params) => sql`SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
WHERE id = ${params.id}`
  })

  // GetOrderWithCustomer
  // SELECT
  //     o.id, o.status, o.total_cents, o.shipping_address, o.billing_address, o.notes, o.created_at, o.updated_at,
  //     c.id AS customer_id, c.email AS customer_email, c.name AS customer_name, c.phone AS customer_phone
  // FROM orders o
  // JOIN customers c ON o.customer_id = c.id
  // WHERE o.id = $1
  const getOrderWithCustomer = SqlSchema.findOneOption({
    Request: GetOrderWithCustomerParams,
    Result: GetOrderWithCustomerResult,
    execute: (params) => sql`SELECT
    o.id, o.status, o.total_cents, o.shipping_address, o.billing_address, o.notes, o.created_at, o.updated_at,
    c.id AS customer_id, c.email AS customer_email, c.name AS customer_name, c.phone AS customer_phone
FROM orders o
JOIN customers c ON o.customer_id = c.id
WHERE o.id = ${params.id}`
  })

  // ListOrders
  // SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
  // FROM orders
  // ORDER BY created_at DESC
  const listOrders = SqlSchema.findAll({
    Request: Schema.Void,
    Result: ListOrdersResult,
    execute: () => sql`SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
ORDER BY created_at DESC`
  })

  // ListOrdersByCustomer
  // SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
  // FROM orders
  // WHERE customer_id = $1
  // ORDER BY created_at DESC
  const listOrdersByCustomer = SqlSchema.findAll({
    Request: ListOrdersByCustomerParams,
    Result: ListOrdersByCustomerResult,
    execute: (params) => sql`SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
WHERE customer_id = ${params.customerId}
ORDER BY created_at DESC`
  })

  // ListOrdersByStatus
  // SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
  // FROM orders
  // WHERE status = $1
  // ORDER BY created_at DESC
  const listOrdersByStatus = SqlSchema.findAll({
    Request: ListOrdersByStatusParams,
    Result: ListOrdersByStatusResult,
    execute: (params) => sql`SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
WHERE status = ${params.status}
ORDER BY created_at DESC`
  })

  // ListOrdersPaginated
  // SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
  // FROM orders
  // ORDER BY created_at DESC
  // LIMIT $1 OFFSET $2
  const listOrdersPaginated = SqlSchema.findAll({
    Request: ListOrdersPaginatedParams,
    Result: ListOrdersPaginatedResult,
    execute: (params) => sql`SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
ORDER BY created_at DESC
LIMIT ${params.limit} OFFSET ${params.offset}`
  })

  // ListOrdersByDateRange
  // SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
  // FROM orders
  // WHERE created_at >= $1 AND created_at < $2
  // ORDER BY created_at DESC
  const listOrdersByDateRange = SqlSchema.findAll({
    Request: ListOrdersByDateRangeParams,
    Result: ListOrdersByDateRangeResult,
    execute: (params) => sql`SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
WHERE created_at >= ${params.createdAt} AND created_at < ${params.createdAt2}
ORDER BY created_at DESC`
  })

  // ListOrdersByDateRangeNamed
  // SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
  // FROM orders
  // WHERE created_at >= $1 AND created_at < $2
  // ORDER BY created_at DESC
  const listOrdersByDateRangeNamed = SqlSchema.findAll({
    Request: ListOrdersByDateRangeNamedParams,
    Result: ListOrdersByDateRangeNamedResult,
    execute: (params) => sql`SELECT id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
FROM orders
WHERE created_at >= ${params.startDate} AND created_at < ${params.endDate}
ORDER BY created_at DESC`
  })

  // ListRecentOrdersWithCustomer
  // SELECT
  //     o.id, o.status, o.total_cents, o.created_at,
  //     c.name AS customer_name, c.email AS customer_email
  // FROM orders o
  // JOIN customers c ON o.customer_id = c.id
  // ORDER BY o.created_at DESC
  // LIMIT $1
  const listRecentOrdersWithCustomer = SqlSchema.findAll({
    Request: ListRecentOrdersWithCustomerParams,
    Result: ListRecentOrdersWithCustomerResult,
    execute: (params) => sql`SELECT
    o.id, o.status, o.total_cents, o.created_at,
    c.name AS customer_name, c.email AS customer_email
FROM orders o
JOIN customers c ON o.customer_id = c.id
ORDER BY o.created_at DESC
LIMIT ${params.limit}`
  })

  // SearchOrders
  // SELECT id, customer_id, status, total_cents, shipping_address, notes, created_at
  // FROM orders
  // WHERE search_vector @@ websearch_to_tsquery('english', $1)
  // ORDER BY created_at DESC
  const searchOrders = SqlSchema.findAll({
    Request: SearchOrdersParams,
    Result: SearchOrdersResult,
    execute: (params) => sql`SELECT id, customer_id, status, total_cents, shipping_address, notes, created_at
FROM orders
WHERE search_vector @@ websearch_to_tsquery('english', ${params.websearchToTsquery})
ORDER BY created_at DESC`
  })

  // CreateOrder
  // INSERT INTO orders (customer_id, status, shipping_address, billing_address, notes)
  // VALUES ($1, $2, $3, $4, $5)
  // RETURNING id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at
  const createOrder = SqlSchema.findOneOption({
    Request: CreateOrderParams,
    Result: CreateOrderResult,
    execute: (params) => sql`INSERT INTO orders (customer_id, status, shipping_address, billing_address, notes)
VALUES (${params.customerId}, ${params.status}, ${params.shippingAddress}, ${params.billingAddress}, ${params.notes})
RETURNING id, customer_id, status, total_cents, shipping_address, billing_address, notes, created_at, updated_at`
  })

  // UpdateOrderStatus
  // UPDATE orders
  // SET status = $2, updated_at = NOW()
  // WHERE id = $1
  const updateOrderStatus = SqlSchema.void({
    Request: UpdateOrderStatusParams,
    execute: (params) => sql`UPDATE orders
SET status = ${params.status}, updated_at = NOW()
WHERE id = ${params.id}`
  })

  // UpdateOrderAddresses
  // UPDATE orders
  // SET shipping_address = $2, billing_address = $3, updated_at = NOW()
  // WHERE id = $1
  const updateOrderAddresses = SqlSchema.void({
    Request: UpdateOrderAddressesParams,
    execute: (params) => sql`UPDATE orders
SET shipping_address = ${params.shippingAddress}, billing_address = ${params.billingAddress}, updated_at = NOW()
WHERE id = ${params.id}`
  })

  // UpdateOrderTotal
  // UPDATE orders
  // SET total_cents = (
  //     SELECT COALESCE(SUM((unit_price_cents * quantity) - discount_cents), 0)
  //     FROM order_lines
  //     WHERE order_id = $1
  // ), updated_at = NOW()
  // WHERE id = $1
  const updateOrderTotal = SqlSchema.void({
    Request: UpdateOrderTotalParams,
    execute: (params) => sql`UPDATE orders
SET total_cents = (
    SELECT COALESCE(SUM((unit_price_cents * quantity) - discount_cents), 0)
    FROM order_lines
    WHERE order_id = ${params.orderId}
), updated_at = NOW()
WHERE id = ${params.orderId}`
  })

  // DeleteOrder
  // DELETE FROM orders
  // WHERE id = $1
  const deleteOrder = SqlSchema.void({
    Request: DeleteOrderParams,
    execute: (params) => sql`DELETE FROM orders
WHERE id = ${params.id}`
  })

  // CountOrdersByStatus
  // SELECT status, COUNT(*) AS order_count
  // FROM orders
  // GROUP BY status
  // ORDER BY order_count DESC
  const countOrdersByStatus = SqlSchema.findAll({
    Request: Schema.Void,
    Result: CountOrdersByStatusResult,
    execute: () => sql`SELECT status, COUNT(*) AS order_count
FROM orders
GROUP BY status
ORDER BY order_count DESC`
  })

  // GetCustomerOrderStats
  // SELECT
  //     COUNT(*) AS total_orders,
  //     COALESCE(SUM(total_cents), 0) AS total_spent,
  //     COALESCE(AVG(total_cents), 0) AS avg_order_value
  // FROM orders
  // WHERE customer_id = $1
  const getCustomerOrderStats = SqlSchema.findOneOption({
    Request: GetCustomerOrderStatsParams,
    Result: GetCustomerOrderStatsResult,
    execute: (params) => sql`SELECT
    COUNT(*) AS total_orders,
    COALESCE(SUM(total_cents), 0) AS total_spent,
    COALESCE(AVG(total_cents), 0) AS avg_order_value
FROM orders
WHERE customer_id = ${params.customerId}`
  })

  // GetOrdersWithLineCount
  // SELECT
  //     o.id, o.customer_id, o.status, o.total_cents, o.created_at,
  //     COUNT(ol.id) AS line_count
  // FROM orders o
  // LEFT JOIN order_lines ol ON o.id = ol.order_id
  // GROUP BY o.id
  // ORDER BY o.created_at DESC
  // LIMIT $1 OFFSET $2
  const getOrdersWithLineCount = SqlSchema.findAll({
    Request: GetOrdersWithLineCountParams,
    Result: GetOrdersWithLineCountResult,
    execute: (params) => sql`SELECT
    o.id, o.customer_id, o.status, o.total_cents, o.created_at,
    COUNT(ol.id) AS line_count
FROM orders o
LEFT JOIN order_lines ol ON o.id = ol.order_id
GROUP BY o.id
ORDER BY o.created_at DESC
LIMIT ${params.limit} OFFSET ${params.offset}`
  })

  // GetOrderLine
  //
  // SELECT id, order_id, product_id, quantity, unit_price_cents, discount_cents, created_at
  // FROM order_lines
  // WHERE id = $1
  const getOrderLine = SqlSchema.findOneOption({
    Request: GetOrderLineParams,
    Result: GetOrderLineResult,
    execute: (params) => sql`
SELECT id, order_id, product_id, quantity, unit_price_cents, discount_cents, created_at
FROM order_lines
WHERE id = ${params.id}`
  })

  // ListOrderLines
  // SELECT id, order_id, product_id, quantity, unit_price_cents, discount_cents, created_at
  // FROM order_lines
  // WHERE order_id = $1
  // ORDER BY created_at
  const listOrderLines = SqlSchema.findAll({
    Request: ListOrderLinesParams,
    Result: ListOrderLinesResult,
    execute: (params) => sql`SELECT id, order_id, product_id, quantity, unit_price_cents, discount_cents, created_at
FROM order_lines
WHERE order_id = ${params.orderId}
ORDER BY created_at`
  })

  // ListOrderLinesWithProduct
  // SELECT
  //     ol.id, ol.order_id, ol.quantity, ol.unit_price_cents, ol.discount_cents, ol.created_at,
  //     p.id AS product_id, p.sku AS product_sku, p.name AS product_name
  // FROM order_lines ol
  // JOIN products p ON ol.product_id = p.id
  // WHERE ol.order_id = $1
  // ORDER BY ol.created_at
  const listOrderLinesWithProduct = SqlSchema.findAll({
    Request: ListOrderLinesWithProductParams,
    Result: ListOrderLinesWithProductResult,
    execute: (params) => sql`SELECT
    ol.id, ol.order_id, ol.quantity, ol.unit_price_cents, ol.discount_cents, ol.created_at,
    p.id AS product_id, p.sku AS product_sku, p.name AS product_name
FROM order_lines ol
JOIN products p ON ol.product_id = p.id
WHERE ol.order_id = ${params.orderId}
ORDER BY ol.created_at`
  })

  // GetFullOrderDetails
  // SELECT
  //     o.id AS order_id, o.status, o.total_cents AS order_total, o.shipping_address, o.created_at AS order_date,
  //     c.id AS customer_id, c.name AS customer_name, c.email AS customer_email,
  //     ol.id AS line_id, ol.quantity, ol.unit_price_cents, ol.discount_cents,
  //     p.id AS product_id, p.sku, p.name AS product_name
  // FROM orders o
  // JOIN customers c ON o.customer_id = c.id
  // JOIN order_lines ol ON o.id = ol.order_id
  // JOIN products p ON ol.product_id = p.id
  // WHERE o.id = $1
  // ORDER BY ol.created_at
  const getFullOrderDetails = SqlSchema.findAll({
    Request: GetFullOrderDetailsParams,
    Result: GetFullOrderDetailsResult,
    execute: (params) => sql`SELECT
    o.id AS order_id, o.status, o.total_cents AS order_total, o.shipping_address, o.created_at AS order_date,
    c.id AS customer_id, c.name AS customer_name, c.email AS customer_email,
    ol.id AS line_id, ol.quantity, ol.unit_price_cents, ol.discount_cents,
    p.id AS product_id, p.sku, p.name AS product_name
FROM orders o
JOIN customers c ON o.customer_id = c.id
JOIN order_lines ol ON o.id = ol.order_id
JOIN products p ON ol.product_id = p.id
WHERE o.id = ${params.id}
ORDER BY ol.created_at`
  })

  // CreateOrderLine
  // INSERT INTO order_lines (order_id, product_id, quantity, unit_price_cents, discount_cents)
  // VALUES ($1, $2, $3, $4, $5)
  // RETURNING id, order_id, product_id, quantity, unit_price_cents, discount_cents, created_at
  const createOrderLine = SqlSchema.findOneOption({
    Request: CreateOrderLineParams,
    Result: CreateOrderLineResult,
    execute: (params) => sql`INSERT INTO order_lines (order_id, product_id, quantity, unit_price_cents, discount_cents)
VALUES (${params.orderId}, ${params.productId}, ${params.quantity}, ${params.unitPriceCents}, ${params.discountCents})
RETURNING id, order_id, product_id, quantity, unit_price_cents, discount_cents, created_at`
  })

  // UpdateOrderLineQuantity
  // UPDATE order_lines
  // SET quantity = $2
  // WHERE id = $1
  const updateOrderLineQuantity = SqlSchema.void({
    Request: UpdateOrderLineQuantityParams,
    execute: (params) => sql`UPDATE order_lines
SET quantity = ${params.quantity}
WHERE id = ${params.id}`
  })

  // DeleteOrderLine
  // DELETE FROM order_lines
  // WHERE id = $1
  const deleteOrderLine = SqlSchema.void({
    Request: DeleteOrderLineParams,
    execute: (params) => sql`DELETE FROM order_lines
WHERE id = ${params.id}`
  })

  // DeleteOrderLines
  // DELETE FROM order_lines
  // WHERE order_id = $1
  const deleteOrderLines = execRows({
    Request: DeleteOrderLinesParams,
    execute: (params) => sql`DELETE FROM order_lines
WHERE order_id = ${params.orderId}`
  })

  // GetOrderLineTotal
  // SELECT
  //     COALESCE(SUM((unit_price_cents * quantity) - discount_cents), 0) AS total
  // FROM order_lines
  // WHERE order_id = $1
  const getOrderLineTotal = SqlSchema.findOneOption({
    Request: GetOrderLineTotalParams,
    Result: GetOrderLineTotalResult,
    execute: (params) => sql`SELECT
    COALESCE(SUM((unit_price_cents * quantity) - discount_cents), 0) AS total
FROM order_lines
WHERE order_id = ${params.orderId}`
  })

  // GetProductSalesStats
  // SELECT
  //     p.id, p.sku, p.name,
  //     COALESCE(SUM(ol.quantity), 0) AS total_sold,
  //     COALESCE(SUM(ol.quantity * ol.unit_price_cents), 0) AS total_revenue
  // FROM products p
  // LEFT JOIN order_lines ol ON p.id = ol.product_id
  // WHERE p.id = $1
  // GROUP BY p.id
  const getProductSalesStats = SqlSchema.findOneOption({
    Request: GetProductSalesStatsParams,
    Result: GetProductSalesStatsResult,
    execute: (params) => sql`SELECT
    p.id, p.sku, p.name,
    COALESCE(SUM(ol.quantity), 0) AS total_sold,
    COALESCE(SUM(ol.quantity * ol.unit_price_cents), 0) AS total_revenue
FROM products p
LEFT JOIN order_lines ol ON p.id = ol.product_id
WHERE p.id = ${params.id}
GROUP BY p.id`
  })

  // GetTopSellingProducts
  // SELECT
  //     p.id, p.sku, p.name, p.category,
  //     SUM(ol.quantity) AS total_sold,
  //     SUM(ol.quantity * ol.unit_price_cents) AS total_revenue
  // FROM products p
  // JOIN order_lines ol ON p.id = ol.product_id
  // GROUP BY p.id
  // ORDER BY total_sold DESC
  // LIMIT $1
  const getTopSellingProducts = SqlSchema.findAll({
    Request: GetTopSellingProductsParams,
    Result: GetTopSellingProductsResult,
    execute: (params) => sql`SELECT
    p.id, p.sku, p.name, p.category,
    SUM(ol.quantity) AS total_sold,
    SUM(ol.quantity * ol.unit_price_cents) AS total_revenue
FROM products p
JOIN order_lines ol ON p.id = ol.product_id
GROUP BY p.id
ORDER BY total_sold DESC
LIMIT ${params.limit}`
  })

  // GetOrdersByProductIds
  // SELECT DISTINCT o.id, o.customer_id, o.status, o.total_cents, o.created_at
  // FROM orders o
  // JOIN order_lines ol ON o.id = ol.order_id
  // WHERE ol.product_id = ANY($1::int[])
  // ORDER BY o.created_at DESC
  const getOrdersByProductIds = SqlSchema.findAll({
    Request: GetOrdersByProductIdsParams,
    Result: GetOrdersByProductIdsResult,
    execute: (params) => sql`SELECT DISTINCT o.id, o.customer_id, o.status, o.total_cents, o.created_at
FROM orders o
JOIN order_lines ol ON o.id = ol.order_id
WHERE ol.product_id = ANY(${params.productIds}::int[])
ORDER BY o.created_at DESC`
  })

  return {
    getOrder,
    getOrderWithCustomer,
    listOrders,
    listOrdersByCustomer,
    listOrdersByStatus,
    listOrdersPaginated,
    listOrdersByDateRange,
    listOrdersByDateRangeNamed,
    listRecentOrdersWithCustomer,
    searchOrders,
    createOrder,
    updateOrderStatus,
    updateOrderAddresses,
    updateOrderTotal,
    deleteOrder,
    countOrdersByStatus,
    getCustomerOrderStats,
    getOrdersWithLineCount,
    getOrderLine,
    listOrderLines,
    listOrderLinesWithProduct,
    getFullOrderDetails,
    createOrderLine,
    updateOrderLineQuantity,
    deleteOrderLine,
    deleteOrderLines,
    getOrderLineTotal,
    getProductSalesStats,
    getTopSellingProducts,
    getOrdersByProductIds,
  } satisfies OrdersRepositoryShape
})

// Live Layer
export const ordersRepositoryLive = Layer.effect(OrdersRepository, ordersRepositoryImpl)
