// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { BigIntFromString, OrderStatusSchema } from "./models.js"
import { Schema } from "effect"

// GetOrder - Result Schema
export const GetOrderResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type GetOrderResult = typeof GetOrderResult.Type
// GetOrderWithCustomer - Result Schema
export const GetOrderWithCustomerResult = Schema.Struct({
  id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
  customer_id: Schema.Int,
  customer_email: Schema.String,
  customer_name: Schema.String,
  customer_phone: Schema.OptionFromNullOr(Schema.String),
})

export type GetOrderWithCustomerResult = typeof GetOrderWithCustomerResult.Type
// ListOrders - Result Schema
export const ListOrdersResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListOrdersResult = typeof ListOrdersResult.Type
// ListOrdersByCustomer - Result Schema
export const ListOrdersByCustomerResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListOrdersByCustomerResult = typeof ListOrdersByCustomerResult.Type
// ListOrdersByStatus - Result Schema
export const ListOrdersByStatusResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListOrdersByStatusResult = typeof ListOrdersByStatusResult.Type
// ListOrdersPaginated - Result Schema
export const ListOrdersPaginatedResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListOrdersPaginatedResult = typeof ListOrdersPaginatedResult.Type
// ListOrdersByDateRange - Result Schema
export const ListOrdersByDateRangeResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListOrdersByDateRangeResult = typeof ListOrdersByDateRangeResult.Type
// ListOrdersByDateRangeNamed - Result Schema
export const ListOrdersByDateRangeNamedResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListOrdersByDateRangeNamedResult = typeof ListOrdersByDateRangeNamedResult.Type
// ListRecentOrdersWithCustomer - Result Schema
export const ListRecentOrdersWithCustomerResult = Schema.Struct({
  id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  created_at: Schema.Date,
  customer_name: Schema.String,
  customer_email: Schema.String,
})

export type ListRecentOrdersWithCustomerResult = typeof ListRecentOrdersWithCustomerResult.Type
// SearchOrders - Result Schema
export const SearchOrdersResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
})

export type SearchOrdersResult = typeof SearchOrdersResult.Type
// CreateOrder - Result Schema
export const CreateOrderResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  billing_address: Schema.OptionFromNullOr(Schema.String),
  notes: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type CreateOrderResult = typeof CreateOrderResult.Type
// CountOrdersByStatus - Result Schema
export const CountOrdersByStatusResult = Schema.Struct({
  status: OrderStatusSchema,
  order_count: BigIntFromString,
})

export type CountOrdersByStatusResult = typeof CountOrdersByStatusResult.Type
// GetCustomerOrderStats - Result Schema
export const GetCustomerOrderStatsResult = Schema.Struct({
  total_orders: BigIntFromString,
  total_spent: Schema.OptionFromNullOr(Schema.String),
  avg_order_value: Schema.OptionFromNullOr(Schema.String),
})

export type GetCustomerOrderStatsResult = typeof GetCustomerOrderStatsResult.Type
// GetOrdersWithLineCount - Result Schema
export const GetOrdersWithLineCountResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  created_at: Schema.Date,
  line_count: BigIntFromString,
})

export type GetOrdersWithLineCountResult = typeof GetOrdersWithLineCountResult.Type
// GetOrderLine - Result Schema
export const GetOrderLineResult = Schema.Struct({
  id: Schema.Int,
  order_id: Schema.Int,
  product_id: Schema.Int,
  quantity: Schema.Int,
  unit_price_cents: Schema.Int,
  discount_cents: Schema.Int,
  created_at: Schema.Date,
})

export type GetOrderLineResult = typeof GetOrderLineResult.Type
// ListOrderLines - Result Schema
export const ListOrderLinesResult = Schema.Struct({
  id: Schema.Int,
  order_id: Schema.Int,
  product_id: Schema.Int,
  quantity: Schema.Int,
  unit_price_cents: Schema.Int,
  discount_cents: Schema.Int,
  created_at: Schema.Date,
})

export type ListOrderLinesResult = typeof ListOrderLinesResult.Type
// ListOrderLinesWithProduct - Result Schema
export const ListOrderLinesWithProductResult = Schema.Struct({
  id: Schema.Int,
  order_id: Schema.Int,
  quantity: Schema.Int,
  unit_price_cents: Schema.Int,
  discount_cents: Schema.Int,
  created_at: Schema.Date,
  product_id: Schema.Int,
  product_sku: Schema.String,
  product_name: Schema.String,
})

export type ListOrderLinesWithProductResult = typeof ListOrderLinesWithProductResult.Type
// GetFullOrderDetails - Result Schema
export const GetFullOrderDetailsResult = Schema.Struct({
  order_id: Schema.Int,
  status: OrderStatusSchema,
  order_total: Schema.Int,
  shipping_address: Schema.OptionFromNullOr(Schema.String),
  order_date: Schema.Date,
  customer_id: Schema.Int,
  customer_name: Schema.String,
  customer_email: Schema.String,
  line_id: Schema.Int,
  quantity: Schema.Int,
  unit_price_cents: Schema.Int,
  discount_cents: Schema.Int,
  product_id: Schema.Int,
  sku: Schema.String,
  product_name: Schema.String,
})

export type GetFullOrderDetailsResult = typeof GetFullOrderDetailsResult.Type
// CreateOrderLine - Result Schema
export const CreateOrderLineResult = Schema.Struct({
  id: Schema.Int,
  order_id: Schema.Int,
  product_id: Schema.Int,
  quantity: Schema.Int,
  unit_price_cents: Schema.Int,
  discount_cents: Schema.Int,
  created_at: Schema.Date,
})

export type CreateOrderLineResult = typeof CreateOrderLineResult.Type
// GetOrderLineTotal - Result Schema
export const GetOrderLineTotalResult = Schema.Struct({
  total: Schema.OptionFromNullOr(Schema.String),
})

export type GetOrderLineTotalResult = typeof GetOrderLineTotalResult.Type
// GetProductSalesStats - Result Schema
export const GetProductSalesStatsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  total_sold: Schema.OptionFromNullOr(Schema.String),
  total_revenue: Schema.OptionFromNullOr(Schema.String),
})

export type GetProductSalesStatsResult = typeof GetProductSalesStatsResult.Type
// GetTopSellingProducts - Result Schema
export const GetTopSellingProductsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  category: Schema.OptionFromNullOr(Schema.String),
  total_sold: BigIntFromString,
  total_revenue: BigIntFromString,
})

export type GetTopSellingProductsResult = typeof GetTopSellingProductsResult.Type
// GetOrdersByProductIds - Result Schema
export const GetOrdersByProductIdsResult = Schema.Struct({
  id: Schema.Int,
  customer_id: Schema.Int,
  status: OrderStatusSchema,
  total_cents: Schema.Int,
  created_at: Schema.Date,
})

export type GetOrdersByProductIdsResult = typeof GetOrdersByProductIdsResult.Type
