// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { Schema } from "effect"

// GetProduct - Parameters Schema
export const GetProductParams = Schema.Struct({
  id: Schema.Int,
})

export type GetProductParams = typeof GetProductParams.Type

// GetProductBySku - Parameters Schema
export const GetProductBySkuParams = Schema.Struct({
  sku: Schema.String,
})

export type GetProductBySkuParams = typeof GetProductBySkuParams.Type

// ListProductsByCategory - Parameters Schema
export const ListProductsByCategoryParams = Schema.Struct({
  category: Schema.optional(Schema.String),
})

export type ListProductsByCategoryParams = typeof ListProductsByCategoryParams.Type

// ListProductsPaginated - Parameters Schema
export const ListProductsPaginatedParams = Schema.Struct({
  limit: Schema.Int,
  offset: Schema.Int,
})

export type ListProductsPaginatedParams = typeof ListProductsPaginatedParams.Type

// ListProductsCursor - Parameters Schema
export const ListProductsCursorParams = Schema.Struct({
  id: Schema.Int,
  limit: Schema.Int,
})

export type ListProductsCursorParams = typeof ListProductsCursorParams.Type

// SearchProducts - Parameters Schema
export const SearchProductsParams = Schema.Struct({
  plaintoTsquery: Schema.String,
})

export type SearchProductsParams = typeof SearchProductsParams.Type

// SearchProductsRanked - Parameters Schema
export const SearchProductsRankedParams = Schema.Struct({
  plaintoTsquery: Schema.String,
  limit: Schema.Int,
  offset: Schema.Int,
})

export type SearchProductsRankedParams = typeof SearchProductsRankedParams.Type

// SearchProductsWithHighlight - Parameters Schema
export const SearchProductsWithHighlightParams = Schema.Struct({
  plaintoTsquery: Schema.String,
})

export type SearchProductsWithHighlightParams = typeof SearchProductsWithHighlightParams.Type

// SearchProductsWebStyle - Parameters Schema
export const SearchProductsWebStyleParams = Schema.Struct({
  websearchToTsquery: Schema.String,
})

export type SearchProductsWebStyleParams = typeof SearchProductsWebStyleParams.Type

// CreateProduct - Parameters Schema
export const CreateProductParams = Schema.Struct({
  sku: Schema.String,
  name: Schema.String,
  description: Schema.optional(Schema.String),
  priceCents: Schema.Int,
  stockQuantity: Schema.Int,
  isActive: Schema.Boolean,
  category: Schema.optional(Schema.String),
})

export type CreateProductParams = typeof CreateProductParams.Type

// UpdateProduct - Parameters Schema
export const UpdateProductParams = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.optional(Schema.String),
  priceCents: Schema.Int,
  stockQuantity: Schema.Int,
  isActive: Schema.Boolean,
  category: Schema.optional(Schema.String),
})

export type UpdateProductParams = typeof UpdateProductParams.Type

// UpdateProductStock - Parameters Schema
export const UpdateProductStockParams = Schema.Struct({
  id: Schema.Int,
  stockQuantity: Schema.Int,
})

export type UpdateProductStockParams = typeof UpdateProductStockParams.Type

// DeactivateProduct - Parameters Schema
export const DeactivateProductParams = Schema.Struct({
  id: Schema.Int,
})

export type DeactivateProductParams = typeof DeactivateProductParams.Type

// DeleteProduct - Parameters Schema
export const DeleteProductParams = Schema.Struct({
  id: Schema.Int,
})

export type DeleteProductParams = typeof DeleteProductParams.Type

// GetProductsByIds - Parameters Schema
export const GetProductsByIdsParams = Schema.Struct({
  ids: Schema.Array(Schema.Int),
})

export type GetProductsByIdsParams = typeof GetProductsByIdsParams.Type

// GetLowStockProducts - Parameters Schema
export const GetLowStockProductsParams = Schema.Struct({
  stockQuantity: Schema.Int,
})

export type GetLowStockProductsParams = typeof GetLowStockProductsParams.Type
