// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { BigIntFromString } from "./models.js"
import { Schema } from "effect"

// GetProduct - Result Schema
export const GetProductResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type GetProductResult = typeof GetProductResult.Type
// GetProductBySku - Result Schema
export const GetProductBySkuResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type GetProductBySkuResult = typeof GetProductBySkuResult.Type
// ListProducts - Result Schema
export const ListProductsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListProductsResult = typeof ListProductsResult.Type
// ListActiveProducts - Result Schema
export const ListActiveProductsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListActiveProductsResult = typeof ListActiveProductsResult.Type
// ListProductsByCategory - Result Schema
export const ListProductsByCategoryResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListProductsByCategoryResult = typeof ListProductsByCategoryResult.Type
// ListProductsPaginated - Result Schema
export const ListProductsPaginatedResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListProductsPaginatedResult = typeof ListProductsPaginatedResult.Type
// ListProductsCursor - Result Schema
export const ListProductsCursorResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListProductsCursorResult = typeof ListProductsCursorResult.Type
// SearchProducts - Result Schema
export const SearchProductsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  category: Schema.OptionFromNullOr(Schema.String),
})

export type SearchProductsResult = typeof SearchProductsResult.Type
// SearchProductsRanked - Result Schema
export const SearchProductsRankedResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  category: Schema.OptionFromNullOr(Schema.String),
  rank: Schema.Number,
})

export type SearchProductsRankedResult = typeof SearchProductsRankedResult.Type
// SearchProductsWithHighlight - Result Schema
export const SearchProductsWithHighlightResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  highlighted_description: Schema.Unknown,
  price_cents: Schema.Int,
  category: Schema.OptionFromNullOr(Schema.String),
})

export type SearchProductsWithHighlightResult = typeof SearchProductsWithHighlightResult.Type
// SearchProductsWebStyle - Result Schema
export const SearchProductsWebStyleResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  category: Schema.OptionFromNullOr(Schema.String),
})

export type SearchProductsWebStyleResult = typeof SearchProductsWebStyleResult.Type
// CreateProduct - Result Schema
export const CreateProductResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type CreateProductResult = typeof CreateProductResult.Type
// UpdateProduct - Result Schema
export const UpdateProductResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type UpdateProductResult = typeof UpdateProductResult.Type
// GetProductsByIds - Result Schema
export const GetProductsByIdsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type GetProductsByIdsResult = typeof GetProductsByIdsResult.Type
// CountProductsByCategory - Result Schema
export const CountProductsByCategoryResult = Schema.Struct({
  category: Schema.OptionFromNullOr(Schema.String),
  product_count: BigIntFromString,
})

export type CountProductsByCategoryResult = typeof CountProductsByCategoryResult.Type
// GetLowStockProducts - Result Schema
export const GetLowStockProductsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  stock_quantity: Schema.Int,
  category: Schema.OptionFromNullOr(Schema.String),
})

export type GetLowStockProductsResult = typeof GetLowStockProductsResult.Type
