// Generated by sqlc v1.30.0, plugin: sqlc-effect v0.1.0
import { ServiceMap, Effect, Layer, Schema, Option, SchemaGetter } from "effect"
import { SqlClient, SqlError, SqlSchema } from "effect/unstable/sql"


// PostgreSQL returns bigint as string to preserve precision, so we need to transform it
const BigIntFromString = Schema.String.pipe(
  Schema.decodeTo(
    Schema.BigInt,
    {
      decode: SchemaGetter.transform((s) => BigInt(s)),
      encode: SchemaGetter.transform((n) => String(n))
    }
  )
)

// PostgreSQL returns affected row count in the raw result metadata
const ExecResult = Schema.Struct({ rowCount: Schema.NullOr(Schema.Int) })

// Helper for :execrows queries - returns affected row count (similar to SqlSchema.void but returns count)
const execRows = <Req extends Schema.Top, E, R>(options: {
  readonly Request: Req
  readonly execute: (request: Req["Encoded"]) => { raw: Effect.Effect<unknown, E, R> }
}) => {
  const encode = Schema.encodeEffect(options.Request)
  const decodeResult = Schema.decodeUnknownEffect(ExecResult)
  return (request: Req["Type"]): Effect.Effect<number, E | Schema.SchemaError, R | Req["EncodingServices"]> =>
    Effect.flatMap(
      Effect.flatMap(encode(request), (encoded) => options.execute(encoded).raw),
      (raw) => Effect.map(decodeResult(raw), (r) => r.rowCount ?? 0)
    )
}


// order_status enum schema
export const OrderStatusSchema = Schema.Literals(["pending", "confirmed", "processing", "shipped", "delivered", "cancelled", "refunded"])


// GetProduct - Parameters Schema
export const GetProductParams = Schema.Struct({
  id: Schema.Int,
})

export type GetProductParams = typeof GetProductParams.Type

// GetProduct - Result Schema
export const GetProductResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type GetProductResult = typeof GetProductResult.Type

// GetProductBySku - Parameters Schema
export const GetProductBySkuParams = Schema.Struct({
  sku: Schema.String,
})

export type GetProductBySkuParams = typeof GetProductBySkuParams.Type

// GetProductBySku - Result Schema
export const GetProductBySkuResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type GetProductBySkuResult = typeof GetProductBySkuResult.Type

// ListProducts - Result Schema
export const ListProductsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListProductsResult = typeof ListProductsResult.Type

// ListActiveProducts - Result Schema
export const ListActiveProductsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListActiveProductsResult = typeof ListActiveProductsResult.Type

// ListProductsByCategory - Parameters Schema
export const ListProductsByCategoryParams = Schema.Struct({
  category: Schema.optional(Schema.String),
})

export type ListProductsByCategoryParams = typeof ListProductsByCategoryParams.Type

// ListProductsByCategory - Result Schema
export const ListProductsByCategoryResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListProductsByCategoryResult = typeof ListProductsByCategoryResult.Type

// ListProductsPaginated - Parameters Schema
export const ListProductsPaginatedParams = Schema.Struct({
  limit: Schema.Int,
  offset: Schema.Int,
})

export type ListProductsPaginatedParams = typeof ListProductsPaginatedParams.Type

// ListProductsPaginated - Result Schema
export const ListProductsPaginatedResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListProductsPaginatedResult = typeof ListProductsPaginatedResult.Type

// ListProductsCursor - Parameters Schema
export const ListProductsCursorParams = Schema.Struct({
  id: Schema.Int,
  limit: Schema.Int,
})

export type ListProductsCursorParams = typeof ListProductsCursorParams.Type

// ListProductsCursor - Result Schema
export const ListProductsCursorResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type ListProductsCursorResult = typeof ListProductsCursorResult.Type

// SearchProducts - Parameters Schema
export const SearchProductsParams = Schema.Struct({
  plaintoTsquery: Schema.String,
})

export type SearchProductsParams = typeof SearchProductsParams.Type

// SearchProducts - Result Schema
export const SearchProductsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  category: Schema.OptionFromNullOr(Schema.String),
})

export type SearchProductsResult = typeof SearchProductsResult.Type

// SearchProductsRanked - Parameters Schema
export const SearchProductsRankedParams = Schema.Struct({
  plaintoTsquery: Schema.String,
  limit: Schema.Int,
  offset: Schema.Int,
})

export type SearchProductsRankedParams = typeof SearchProductsRankedParams.Type

// SearchProductsRanked - Result Schema
export const SearchProductsRankedResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  category: Schema.OptionFromNullOr(Schema.String),
  rank: Schema.Number,
})

export type SearchProductsRankedResult = typeof SearchProductsRankedResult.Type

// SearchProductsWithHighlight - Parameters Schema
export const SearchProductsWithHighlightParams = Schema.Struct({
  plaintoTsquery: Schema.String,
})

export type SearchProductsWithHighlightParams = typeof SearchProductsWithHighlightParams.Type

// SearchProductsWithHighlight - Result Schema
export const SearchProductsWithHighlightResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  highlighted_description: Schema.Unknown,
  price_cents: Schema.Int,
  category: Schema.OptionFromNullOr(Schema.String),
})

export type SearchProductsWithHighlightResult = typeof SearchProductsWithHighlightResult.Type

// SearchProductsWebStyle - Parameters Schema
export const SearchProductsWebStyleParams = Schema.Struct({
  websearchToTsquery: Schema.String,
})

export type SearchProductsWebStyleParams = typeof SearchProductsWebStyleParams.Type

// SearchProductsWebStyle - Result Schema
export const SearchProductsWebStyleResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  category: Schema.OptionFromNullOr(Schema.String),
})

export type SearchProductsWebStyleResult = typeof SearchProductsWebStyleResult.Type

// CreateProduct - Parameters Schema
export const CreateProductParams = Schema.Struct({
  sku: Schema.String,
  name: Schema.String,
  description: Schema.optional(Schema.String),
  priceCents: Schema.Int,
  stockQuantity: Schema.Int,
  isActive: Schema.Boolean,
  category: Schema.optional(Schema.String),
})

export type CreateProductParams = typeof CreateProductParams.Type

// CreateProduct - Result Schema
export const CreateProductResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type CreateProductResult = typeof CreateProductResult.Type

// UpdateProduct - Parameters Schema
export const UpdateProductParams = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.optional(Schema.String),
  priceCents: Schema.Int,
  stockQuantity: Schema.Int,
  isActive: Schema.Boolean,
  category: Schema.optional(Schema.String),
})

export type UpdateProductParams = typeof UpdateProductParams.Type

// UpdateProduct - Result Schema
export const UpdateProductResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type UpdateProductResult = typeof UpdateProductResult.Type

// UpdateProductStock - Parameters Schema
export const UpdateProductStockParams = Schema.Struct({
  id: Schema.Int,
  stockQuantity: Schema.Int,
})

export type UpdateProductStockParams = typeof UpdateProductStockParams.Type

// DeactivateProduct - Parameters Schema
export const DeactivateProductParams = Schema.Struct({
  id: Schema.Int,
})

export type DeactivateProductParams = typeof DeactivateProductParams.Type

// DeleteProduct - Parameters Schema
export const DeleteProductParams = Schema.Struct({
  id: Schema.Int,
})

export type DeleteProductParams = typeof DeleteProductParams.Type

// GetProductsByIds - Parameters Schema
export const GetProductsByIdsParams = Schema.Struct({
  ids: Schema.Array(Schema.Int),
})

export type GetProductsByIdsParams = typeof GetProductsByIdsParams.Type

// GetProductsByIds - Result Schema
export const GetProductsByIdsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  description: Schema.OptionFromNullOr(Schema.String),
  price_cents: Schema.Int,
  stock_quantity: Schema.Int,
  is_active: Schema.Boolean,
  category: Schema.OptionFromNullOr(Schema.String),
  created_at: Schema.Date,
  updated_at: Schema.Date,
})

export type GetProductsByIdsResult = typeof GetProductsByIdsResult.Type

// CountProductsByCategory - Result Schema
export const CountProductsByCategoryResult = Schema.Struct({
  category: Schema.OptionFromNullOr(Schema.String),
  product_count: BigIntFromString,
})

export type CountProductsByCategoryResult = typeof CountProductsByCategoryResult.Type

// GetLowStockProducts - Parameters Schema
export const GetLowStockProductsParams = Schema.Struct({
  stockQuantity: Schema.Int,
})

export type GetLowStockProductsParams = typeof GetLowStockProductsParams.Type

// GetLowStockProducts - Result Schema
export const GetLowStockProductsResult = Schema.Struct({
  id: Schema.Int,
  sku: Schema.String,
  name: Schema.String,
  stock_quantity: Schema.Int,
  category: Schema.OptionFromNullOr(Schema.String),
})

export type GetLowStockProductsResult = typeof GetLowStockProductsResult.Type


// Repository interface for products.sql
export interface ProductsRepositoryShape {
  readonly getProduct: (params: GetProductParams) => Effect.Effect<
    Option.Option<GetProductResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getProductBySku: (params: GetProductBySkuParams) => Effect.Effect<
    Option.Option<GetProductBySkuResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listProducts: () => Effect.Effect<
    ListProductsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listActiveProducts: () => Effect.Effect<
    ListActiveProductsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listProductsByCategory: (params: ListProductsByCategoryParams) => Effect.Effect<
    ListProductsByCategoryResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listProductsPaginated: (params: ListProductsPaginatedParams) => Effect.Effect<
    ListProductsPaginatedResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listProductsCursor: (params: ListProductsCursorParams) => Effect.Effect<
    ListProductsCursorResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly searchProducts: (params: SearchProductsParams) => Effect.Effect<
    SearchProductsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly searchProductsRanked: (params: SearchProductsRankedParams) => Effect.Effect<
    SearchProductsRankedResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly searchProductsWithHighlight: (params: SearchProductsWithHighlightParams) => Effect.Effect<
    SearchProductsWithHighlightResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly searchProductsWebStyle: (params: SearchProductsWebStyleParams) => Effect.Effect<
    SearchProductsWebStyleResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly createProduct: (params: CreateProductParams) => Effect.Effect<
    Option.Option<CreateProductResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly updateProduct: (params: UpdateProductParams) => Effect.Effect<
    Option.Option<UpdateProductResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly updateProductStock: (params: UpdateProductStockParams) => Effect.Effect<
    number,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly deactivateProduct: (params: DeactivateProductParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly deleteProduct: (params: DeleteProductParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getProductsByIds: (params: GetProductsByIdsParams) => Effect.Effect<
    GetProductsByIdsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly countProductsByCategory: () => Effect.Effect<
    CountProductsByCategoryResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getLowStockProducts: (params: GetLowStockProductsParams) => Effect.Effect<
    GetLowStockProductsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
}

// Service Tag
export class ProductsRepository extends ServiceMap.Service<ProductsRepository, ProductsRepositoryShape>()("ProductsRepository") { }

// Implementation
const productsRepositoryImpl = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient


  // GetProduct
  const getProduct = SqlSchema.findOneOption({
    Request: GetProductParams,
    Result: GetProductResult,
    execute: (params) => sql.unsafe(`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE id = $1`, [params.id])
  })

  // GetProductBySku
  const getProductBySku = SqlSchema.findOneOption({
    Request: GetProductBySkuParams,
    Result: GetProductBySkuResult,
    execute: (params) => sql.unsafe(`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE sku = $1`, [params.sku])
  })

  // ListProducts
  const listProducts = SqlSchema.findAll({
    Request: Schema.Void,
    Result: ListProductsResult,
    execute: () => sql.unsafe(`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
ORDER BY name`)
  })

  // ListActiveProducts
  const listActiveProducts = SqlSchema.findAll({
    Request: Schema.Void,
    Result: ListActiveProductsResult,
    execute: () => sql.unsafe(`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE is_active = TRUE
ORDER BY name`)
  })

  // ListProductsByCategory
  const listProductsByCategory = SqlSchema.findAll({
    Request: ListProductsByCategoryParams,
    Result: ListProductsByCategoryResult,
    execute: (params) => sql.unsafe(`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE category = $1 AND is_active = TRUE
ORDER BY name`, [params.category])
  })

  // ListProductsPaginated
  const listProductsPaginated = SqlSchema.findAll({
    Request: ListProductsPaginatedParams,
    Result: ListProductsPaginatedResult,
    execute: (params) => sql.unsafe(`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE is_active = TRUE
ORDER BY created_at DESC
LIMIT $1 OFFSET $2`, [params.limit, params.offset])
  })

  // ListProductsCursor
  const listProductsCursor = SqlSchema.findAll({
    Request: ListProductsCursorParams,
    Result: ListProductsCursorResult,
    execute: (params) => sql.unsafe(`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE is_active = TRUE AND id > $1
ORDER BY id
LIMIT $2`, [params.id, params.limit])
  })

  // SearchProducts
  const searchProducts = SqlSchema.findAll({
    Request: SearchProductsParams,
    Result: SearchProductsResult,
    execute: (params) => sql.unsafe(`SELECT id, sku, name, description, price_cents, stock_quantity, category
FROM products
WHERE search_vector @@ plainto_tsquery('english', $1)
  AND is_active = TRUE
ORDER BY name`, [params.plaintoTsquery])
  })

  // SearchProductsRanked
  const searchProductsRanked = SqlSchema.findAll({
    Request: SearchProductsRankedParams,
    Result: SearchProductsRankedResult,
    execute: (params) => sql.unsafe(`SELECT id, sku, name, description, price_cents, stock_quantity, category,
       ts_rank(search_vector, query) AS rank
FROM products, plainto_tsquery('english', $1) query
WHERE search_vector @@ query
  AND is_active = TRUE
ORDER BY rank DESC
LIMIT $2 OFFSET $3`, [params.plaintoTsquery, params.limit, params.offset])
  })

  // SearchProductsWithHighlight
  const searchProductsWithHighlight = SqlSchema.findAll({
    Request: SearchProductsWithHighlightParams,
    Result: SearchProductsWithHighlightResult,
    execute: (params) => sql.unsafe(`SELECT id, sku, name,
       ts_headline('english', COALESCE(description, ''), plainto_tsquery('english', $1)) AS highlighted_description,
       price_cents, category
FROM products
WHERE search_vector @@ plainto_tsquery('english', $1)
  AND is_active = TRUE`, [params.plaintoTsquery])
  })

  // SearchProductsWebStyle
  const searchProductsWebStyle = SqlSchema.findAll({
    Request: SearchProductsWebStyleParams,
    Result: SearchProductsWebStyleResult,
    execute: (params) => sql.unsafe(`SELECT id, sku, name, description, price_cents, category
FROM products
WHERE search_vector @@ websearch_to_tsquery('english', $1)
  AND is_active = TRUE
ORDER BY name`, [params.websearchToTsquery])
  })

  // CreateProduct
  const createProduct = SqlSchema.findOneOption({
    Request: CreateProductParams,
    Result: CreateProductResult,
    execute: (params) => sql.unsafe(`INSERT INTO products (sku, name, description, price_cents, stock_quantity, is_active, category)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at`, [params.sku, params.name, params.description, params.priceCents, params.stockQuantity, params.isActive, params.category])
  })

  // UpdateProduct
  const updateProduct = SqlSchema.findOneOption({
    Request: UpdateProductParams,
    Result: UpdateProductResult,
    execute: (params) => sql.unsafe(`UPDATE products
SET sku = $2, name = $3, description = $4, price_cents = $5, stock_quantity = $6, is_active = $7, category = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at`, [params.id, params.sku, params.name, params.description, params.priceCents, params.stockQuantity, params.isActive, params.category])
  })

  // UpdateProductStock
  const updateProductStock = execRows({
    Request: UpdateProductStockParams,
    execute: (params) => sql.unsafe(`UPDATE products
SET stock_quantity = stock_quantity + $2, updated_at = NOW()
WHERE id = $1`, [params.id, params.stockQuantity])
  })

  // DeactivateProduct
  const deactivateProduct = SqlSchema.void({
    Request: DeactivateProductParams,
    execute: (params) => sql.unsafe(`UPDATE products
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1`, [params.id])
  })

  // DeleteProduct
  const deleteProduct = SqlSchema.void({
    Request: DeleteProductParams,
    execute: (params) => sql.unsafe(`DELETE FROM products
WHERE id = $1`, [params.id])
  })

  // GetProductsByIds
  const getProductsByIds = SqlSchema.findAll({
    Request: GetProductsByIdsParams,
    Result: GetProductsByIdsResult,
    execute: (params) => sql.unsafe(`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE id = ANY($1::int[])`, [params.ids])
  })

  // CountProductsByCategory
  const countProductsByCategory = SqlSchema.findAll({
    Request: Schema.Void,
    Result: CountProductsByCategoryResult,
    execute: () => sql.unsafe(`SELECT category, COUNT(*) AS product_count
FROM products
WHERE is_active = TRUE
GROUP BY category
ORDER BY product_count DESC`)
  })

  // GetLowStockProducts
  const getLowStockProducts = SqlSchema.findAll({
    Request: GetLowStockProductsParams,
    Result: GetLowStockProductsResult,
    execute: (params) => sql.unsafe(`SELECT id, sku, name, stock_quantity, category
FROM products
WHERE stock_quantity < $1 AND is_active = TRUE
ORDER BY stock_quantity`, [params.stockQuantity])
  })

  return {
    getProduct,
    getProductBySku,
    listProducts,
    listActiveProducts,
    listProductsByCategory,
    listProductsPaginated,
    listProductsCursor,
    searchProducts,
    searchProductsRanked,
    searchProductsWithHighlight,
    searchProductsWebStyle,
    createProduct,
    updateProduct,
    updateProductStock,
    deactivateProduct,
    deleteProduct,
    getProductsByIds,
    countProductsByCategory,
    getLowStockProducts,
  } satisfies ProductsRepositoryShape
})

// Live Layer
export const productsRepositoryLive = Layer.effect(ProductsRepository, productsRepositoryImpl)
