// Generated by sqlc v1.30.0, plugin: sqlc-effect dev
import { CreateProductParams, DeactivateProductParams, DeleteProductParams, GetLowStockProductsParams, GetProductBySkuParams, GetProductParams, GetProductsByIdsParams, ListProductsByCategoryParams, ListProductsCursorParams, ListProductsPaginatedParams, SearchProductsParams, SearchProductsRankedParams, SearchProductsWebStyleParams, SearchProductsWithHighlightParams, UpdateProductParams, UpdateProductStockParams } from "./ProductsRepositoryRequest.js"
import { CountProductsByCategoryResult, CreateProductResult, GetLowStockProductsResult, GetProductBySkuResult, GetProductResult, GetProductsByIdsResult, ListActiveProductsResult, ListProductsByCategoryResult, ListProductsCursorResult, ListProductsPaginatedResult, ListProductsResult, SearchProductsRankedResult, SearchProductsResult, SearchProductsWebStyleResult, SearchProductsWithHighlightResult, UpdateProductResult } from "./ProductsRepositoryResponse.js"
import { execRows } from "./models.js"
import { Effect, Layer, Option, Schema, ServiceMap } from "effect"
import { SqlClient, SqlError, SqlSchema } from "effect/unstable/sql"

// Repository interface for products.sql
export interface ProductsRepositoryShape {
  readonly getProduct: (params: GetProductParams) => Effect.Effect<
    Option.Option<GetProductResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getProductBySku: (params: GetProductBySkuParams) => Effect.Effect<
    Option.Option<GetProductBySkuResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listProducts: () => Effect.Effect<
    ListProductsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listActiveProducts: () => Effect.Effect<
    ListActiveProductsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listProductsByCategory: (params: ListProductsByCategoryParams) => Effect.Effect<
    ListProductsByCategoryResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listProductsPaginated: (params: ListProductsPaginatedParams) => Effect.Effect<
    ListProductsPaginatedResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly listProductsCursor: (params: ListProductsCursorParams) => Effect.Effect<
    ListProductsCursorResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly searchProducts: (params: SearchProductsParams) => Effect.Effect<
    SearchProductsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly searchProductsRanked: (params: SearchProductsRankedParams) => Effect.Effect<
    SearchProductsRankedResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly searchProductsWithHighlight: (params: SearchProductsWithHighlightParams) => Effect.Effect<
    SearchProductsWithHighlightResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly searchProductsWebStyle: (params: SearchProductsWebStyleParams) => Effect.Effect<
    SearchProductsWebStyleResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly createProduct: (params: CreateProductParams) => Effect.Effect<
    Option.Option<CreateProductResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly updateProduct: (params: UpdateProductParams) => Effect.Effect<
    Option.Option<UpdateProductResult>,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly updateProductStock: (params: UpdateProductStockParams) => Effect.Effect<
    number,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly deactivateProduct: (params: DeactivateProductParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly deleteProduct: (params: DeleteProductParams) => Effect.Effect<
    void,
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getProductsByIds: (params: GetProductsByIdsParams) => Effect.Effect<
    GetProductsByIdsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly countProductsByCategory: () => Effect.Effect<
    CountProductsByCategoryResult[],
    SqlError.SqlError | Schema.SchemaError
  >
  readonly getLowStockProducts: (params: GetLowStockProductsParams) => Effect.Effect<
    GetLowStockProductsResult[],
    SqlError.SqlError | Schema.SchemaError
  >
}

// Service Tag
export class ProductsRepository extends ServiceMap.Service<ProductsRepository, ProductsRepositoryShape>()("ProductsRepository") { }

// Implementation
const productsRepositoryImpl = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient

  // GetProduct
  // SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
  // FROM products
  // WHERE id = $1
  const getProduct = SqlSchema.findOneOption({
    Request: GetProductParams,
    Result: GetProductResult,
    execute: (params) => sql`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE id = ${params.id}`
  })

  // GetProductBySku
  // SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
  // FROM products
  // WHERE sku = $1
  const getProductBySku = SqlSchema.findOneOption({
    Request: GetProductBySkuParams,
    Result: GetProductBySkuResult,
    execute: (params) => sql`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE sku = ${params.sku}`
  })

  // ListProducts
  // SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
  // FROM products
  // ORDER BY name
  const listProducts = SqlSchema.findAll({
    Request: Schema.Void,
    Result: ListProductsResult,
    execute: () => sql`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
ORDER BY name`
  })

  // ListActiveProducts
  // SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
  // FROM products
  // WHERE is_active = TRUE
  // ORDER BY name
  const listActiveProducts = SqlSchema.findAll({
    Request: Schema.Void,
    Result: ListActiveProductsResult,
    execute: () => sql`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE is_active = TRUE
ORDER BY name`
  })

  // ListProductsByCategory
  // SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
  // FROM products
  // WHERE category = $1 AND is_active = TRUE
  // ORDER BY name
  const listProductsByCategory = SqlSchema.findAll({
    Request: ListProductsByCategoryParams,
    Result: ListProductsByCategoryResult,
    execute: (params) => sql`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE category = ${params.category} AND is_active = TRUE
ORDER BY name`
  })

  // ListProductsPaginated
  // SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
  // FROM products
  // WHERE is_active = TRUE
  // ORDER BY created_at DESC
  // LIMIT $1 OFFSET $2
  const listProductsPaginated = SqlSchema.findAll({
    Request: ListProductsPaginatedParams,
    Result: ListProductsPaginatedResult,
    execute: (params) => sql`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE is_active = TRUE
ORDER BY created_at DESC
LIMIT ${params.limit} OFFSET ${params.offset}`
  })

  // ListProductsCursor
  // SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
  // FROM products
  // WHERE is_active = TRUE AND id > $1
  // ORDER BY id
  // LIMIT $2
  const listProductsCursor = SqlSchema.findAll({
    Request: ListProductsCursorParams,
    Result: ListProductsCursorResult,
    execute: (params) => sql`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE is_active = TRUE AND id > ${params.id}
ORDER BY id
LIMIT ${params.limit}`
  })

  // SearchProducts
  // SELECT id, sku, name, description, price_cents, stock_quantity, category
  // FROM products
  // WHERE search_vector @@ plainto_tsquery('english', $1)
  //   AND is_active = TRUE
  // ORDER BY name
  const searchProducts = SqlSchema.findAll({
    Request: SearchProductsParams,
    Result: SearchProductsResult,
    execute: (params) => sql`SELECT id, sku, name, description, price_cents, stock_quantity, category
FROM products
WHERE search_vector @@ plainto_tsquery('english', ${params.plaintoTsquery})
  AND is_active = TRUE
ORDER BY name`
  })

  // SearchProductsRanked
  // SELECT id, sku, name, description, price_cents, stock_quantity, category,
  //        ts_rank(search_vector, query) AS rank
  // FROM products, plainto_tsquery('english', $1) query
  // WHERE search_vector @@ query
  //   AND is_active = TRUE
  // ORDER BY rank DESC
  // LIMIT $2 OFFSET $3
  const searchProductsRanked = SqlSchema.findAll({
    Request: SearchProductsRankedParams,
    Result: SearchProductsRankedResult,
    execute: (params) => sql`SELECT id, sku, name, description, price_cents, stock_quantity, category,
       ts_rank(search_vector, query) AS rank
FROM products, plainto_tsquery('english', ${params.plaintoTsquery}) query
WHERE search_vector @@ query
  AND is_active = TRUE
ORDER BY rank DESC
LIMIT ${params.limit} OFFSET ${params.offset}`
  })

  // SearchProductsWithHighlight
  // SELECT id, sku, name,
  //        ts_headline('english', COALESCE(description, ''), plainto_tsquery('english', $1)) AS highlighted_description,
  //        price_cents, category
  // FROM products
  // WHERE search_vector @@ plainto_tsquery('english', $1)
  //   AND is_active = TRUE
  const searchProductsWithHighlight = SqlSchema.findAll({
    Request: SearchProductsWithHighlightParams,
    Result: SearchProductsWithHighlightResult,
    execute: (params) => sql`SELECT id, sku, name,
       ts_headline('english', COALESCE(description, ''), plainto_tsquery('english', ${params.plaintoTsquery})) AS highlighted_description,
       price_cents, category
FROM products
WHERE search_vector @@ plainto_tsquery('english', ${params.plaintoTsquery})
  AND is_active = TRUE`
  })

  // SearchProductsWebStyle
  // SELECT id, sku, name, description, price_cents, category
  // FROM products
  // WHERE search_vector @@ websearch_to_tsquery('english', $1)
  //   AND is_active = TRUE
  // ORDER BY name
  const searchProductsWebStyle = SqlSchema.findAll({
    Request: SearchProductsWebStyleParams,
    Result: SearchProductsWebStyleResult,
    execute: (params) => sql`SELECT id, sku, name, description, price_cents, category
FROM products
WHERE search_vector @@ websearch_to_tsquery('english', ${params.websearchToTsquery})
  AND is_active = TRUE
ORDER BY name`
  })

  // CreateProduct
  // INSERT INTO products (sku, name, description, price_cents, stock_quantity, is_active, category)
  // VALUES ($1, $2, $3, $4, $5, $6, $7)
  // RETURNING id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
  const createProduct = SqlSchema.findOneOption({
    Request: CreateProductParams,
    Result: CreateProductResult,
    execute: (params) => sql`INSERT INTO products (sku, name, description, price_cents, stock_quantity, is_active, category)
VALUES (${params.sku}, ${params.name}, ${params.description}, ${params.priceCents}, ${params.stockQuantity}, ${params.isActive}, ${params.category})
RETURNING id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at`
  })

  // UpdateProduct
  // UPDATE products
  // SET sku = $2, name = $3, description = $4, price_cents = $5, stock_quantity = $6, is_active = $7, category = $8, updated_at = NOW()
  // WHERE id = $1
  // RETURNING id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
  const updateProduct = SqlSchema.findOneOption({
    Request: UpdateProductParams,
    Result: UpdateProductResult,
    execute: (params) => sql`UPDATE products
SET sku = ${params.sku}, name = ${params.name}, description = ${params.description}, price_cents = ${params.priceCents}, stock_quantity = ${params.stockQuantity}, is_active = ${params.isActive}, category = ${params.category}, updated_at = NOW()
WHERE id = ${params.id}
RETURNING id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at`
  })

  // UpdateProductStock
  // UPDATE products
  // SET stock_quantity = stock_quantity + $2, updated_at = NOW()
  // WHERE id = $1
  const updateProductStock = execRows({
    Request: UpdateProductStockParams,
    execute: (params) => sql`UPDATE products
SET stock_quantity = stock_quantity + ${params.stockQuantity}, updated_at = NOW()
WHERE id = ${params.id}`
  })

  // DeactivateProduct
  // UPDATE products
  // SET is_active = FALSE, updated_at = NOW()
  // WHERE id = $1
  const deactivateProduct = SqlSchema.void({
    Request: DeactivateProductParams,
    execute: (params) => sql`UPDATE products
SET is_active = FALSE, updated_at = NOW()
WHERE id = ${params.id}`
  })

  // DeleteProduct
  // DELETE FROM products
  // WHERE id = $1
  const deleteProduct = SqlSchema.void({
    Request: DeleteProductParams,
    execute: (params) => sql`DELETE FROM products
WHERE id = ${params.id}`
  })

  // GetProductsByIds
  // SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
  // FROM products
  // WHERE id = ANY($1::int[])
  const getProductsByIds = SqlSchema.findAll({
    Request: GetProductsByIdsParams,
    Result: GetProductsByIdsResult,
    execute: (params) => sql`SELECT id, sku, name, description, price_cents, stock_quantity, is_active, category, created_at, updated_at
FROM products
WHERE id = ANY(${params.ids}::int[])`
  })

  // CountProductsByCategory
  // SELECT category, COUNT(*) AS product_count
  // FROM products
  // WHERE is_active = TRUE
  // GROUP BY category
  // ORDER BY product_count DESC
  const countProductsByCategory = SqlSchema.findAll({
    Request: Schema.Void,
    Result: CountProductsByCategoryResult,
    execute: () => sql`SELECT category, COUNT(*) AS product_count
FROM products
WHERE is_active = TRUE
GROUP BY category
ORDER BY product_count DESC`
  })

  // GetLowStockProducts
  // SELECT id, sku, name, stock_quantity, category
  // FROM products
  // WHERE stock_quantity < $1 AND is_active = TRUE
  // ORDER BY stock_quantity
  const getLowStockProducts = SqlSchema.findAll({
    Request: GetLowStockProductsParams,
    Result: GetLowStockProductsResult,
    execute: (params) => sql`SELECT id, sku, name, stock_quantity, category
FROM products
WHERE stock_quantity < ${params.stockQuantity} AND is_active = TRUE
ORDER BY stock_quantity`
  })

  return {
    getProduct,
    getProductBySku,
    listProducts,
    listActiveProducts,
    listProductsByCategory,
    listProductsPaginated,
    listProductsCursor,
    searchProducts,
    searchProductsRanked,
    searchProductsWithHighlight,
    searchProductsWebStyle,
    createProduct,
    updateProduct,
    updateProductStock,
    deactivateProduct,
    deleteProduct,
    getProductsByIds,
    countProductsByCategory,
    getLowStockProducts,
  } satisfies ProductsRepositoryShape
})

// Live Layer
export const productsRepositoryLive = Layer.effect(ProductsRepository, productsRepositoryImpl)
